### ISSUE TITLE
Preview Site is Down

### ISSUE THREAD

**Issue by DavidMANZI-093** [react-icons/react-icons#1003]
@kamijin-fanta

https://react-icons.github.io/react-icons/

The **React-Icons** Preview **Site is down**... Please **address the issue**!

Thanks!

**Comment by kamijin-fanta** [comment]
I can access it.

**Comment by DavidMANZI-093** [comment]
My bad! I still can't access it though... It is up I can tell by looking at github pages deployments but when I ping it, it reports a request timeout...

**Comment by DavidMANZI-093** [comment]
**I just got around the issue**... I think it **might be of some help** to somebody else... I just used **a VPN Proxy and it works** now... Thanks!
