### ISSUE TITLE
Add Feather icons

### ISSUE THREAD

**Issue by wbobeirne** [react-icons/react-icons#101]
Feather is open source and a pretty robust set of icons, would make a good addition: https://feathericons.com/

I'll try to put together a PR in a bit, but thought I'd make an issue for it first.

**Comment by kumarharsh** [comment]
The icons are really beautiful. Would love to see this included in react-icons. Seems like the icons already have an svg source.

**Comment by Jinksi** [comment]
`react-icons` maintenance seems to have halted.
[`react-feather`](https://github.com/carmelopullara/react-feather) is a good alternative for using feather icons

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
try new version!
