### ISSUE TITLE
Eslint Style Config?

### ISSUE THREAD

**Issue by fpoumian** [react-icons/react-icons#108]
I noticed that the Eslint config is set up to use the "eslint-config-airbnb" preset, however, taking a look at the component files I just noticed that the none of them are using semicolons, which is a rule enforced by the Airbnb's style guide. So, as a result, Eslint is complaining about this particular rule; is this intentional? maybe we could use [StandardJS](https://standardjs.com/) instead? or add an exception to this rule in the Eslint config file?

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
try new version!
