### ISSUE TITLE
React build very slow

### ISSUE THREAD

**Issue by pmunin** [react-icons/react-icons#111]
I'm using it with create-react-app + react-scripts-ts (typescript)+ react-app-rewired(to override build configuration). In my code I'm linking all FA icons so it's easier to use it:
`import * as fa from 'react-icons/lib/fa';`. Just this line increase build time for ~2 minutes, and adds additional 500k to generated js bundle + 3Mb for source map.

Can you please provide instructions how to configure build to make it faster and smaller with react or at least not to rebuild it every time?

**Comment by ronaldroe** [comment]
That is likely because you are importing every single icon in the FA stack. I'm a bit surprised that it's only 500k. It should be fine for development, but for production, you should only be importing the icons you are actually using.

**Comment by ghufr** [comment]
I have same problem here

`import { MdIcon } from 'react-icons/lib/md'`
`import { FaIcon } from 'react-icons/lib/fa'`

and the bundle size is around **2MB** & **200KB** **Gzipped** 🙄

![bundle-size](https://user-images.githubusercontent.com/20156570/34893455-e42ffb04-f80f-11e7-84f0-416e09d4d4cf.png)

**Comment by nidaorhan** [comment]
I'm also experiencing the same issue. Is there any solution for this?

**Comment by ghufr** [comment]
I think the solution is `import FaCaretDown from 'react-icons/lib/fa/caret-down'`  👀

**Comment by mariusk** [comment]
This hit me as well, although I was using `preact-icons` which is more or less the same module as this. The solution suggested by @ghufr above does work. But I'm also wondering why using named imports unexpectedly pulls in everything.

**Comment by cjtafoya** [comment]
Any additional discussion on sizing issues would be helpful... likewise only selectively importing icons, and likewise ending up with a huge bundle size

**Comment by kamijin-fanta** [comment]
I am working on improving the build speed in webpack. It will be possible to use it if merged.
#141

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
try new version!
