### ISSUE TITLE
Icons have ugly offset in button (comparing to Bootstrap glyphs)

### ISSUE THREAD

**Issue by pmunin** [react-icons/react-icons#112]
I'm using Bootstrap in my react app. Bootstrap is missing some glyphs so I have to use FA icons from react-icons. And when I add it to the button (xs size) - it renders with some ugly offset, which does not happen if I use Bootstrap glyph icon:

Here is the code:
```
import * as bs from 'react-bootstrap'
import FaTable from 'react-icons/lib/fa/table'; let fa = {FaTable};

const renderButton = ()=>
                        <bs.Button>
                            <bs.Glyphicon glyph="film"/>
                            <fa.FaTable />
                            Table
                        </bs.Button>
```
Here is result:

![image](https://user-images.githubusercontent.com/7120440/29822011-f9e42e2c-8c97-11e7-8452-e7ce8ad8c6d7.png)

1st icon - is standard bootstrap

2nd icon - is FA icon which has offsets lower than a text

What is the best way to fix it?

**Comment by senycorp** [comment]
Hi,

i had same problem with my own implementation and wanted to test this library. Same here. I did some hacks. First one was to wrap the icon by FontAwesomes <i className="fa"></i>. This was good but not really perfect. Then i figured out that the main problem was the viewBox value of the svg element. in asterisk.js. Setting it to '0 -2 40 40' solves it totally.

I am not a svg expert and modifying library code is ugly but.... it solves the problem

**Comment by kamijin-fanta** [comment]
The latest version is 3. If the problem persists, please provide a minimal repository.
