### ISSUE TITLE
How to reference icon import as variable from another file?

### ISSUE THREAD

**Issue by praiseTheKek** [react-icons/react-icons#114]
So far I have been referencing the library to make a variable
`let IconBomb = require('react-icons/lib/fa/bomb');`
Then in my html I call it as
`<IconBomb/>`

Now I have multiple files that need `IconBomb`, so I want to make a separate `icons.js` file that includes all my icon variables.
```
let IconBomb = require('react-icons/lib/fa/bomb');
let IconClose = require('react-icons/lib/fa/close');
let IconAudio = require('react-icons/lib/md/audiotrack');
let IconUnlock = require('react-icons/lib/fa/unlock-alt');
let IconLock = require('react-icons/lib/fa/lock');
```

How can I import these variables to be used by various components?

**Comment by kumarharsh** [comment]
http://exploringjs.com/es6/ch_modules.html#sec_importing-exporting-details

**Comment by kamijin-fanta** [comment]
ES Imports was supported from react-icons@3.0.0.
try it.
```jsx
import * as Fa 'react-icons / fa';
```
