### ISSUE TITLE
Support for Fontawesome 5

### ISSUE THREAD

**Issue by kumarharsh** [react-icons/react-icons#123]
Hi, the Fontawesome 5 has been released and the default download contains raw SVG files too, so I think automating it would be easy. What do you think about adding support for it?

**Comment by waterfoul** [comment]
FYI FA 5 has support for this by default https://www.npmjs.com/package/react-fontawesome

**Comment by waterfoul** [comment]
FYI FA 5 Has support for react natively https://github.com/FortAwesome/react-fontawesome it works a little different though

**Comment by kamijin-fanta** [comment]
Currently we are work for support with fa 5. It will be possible to use it if merged.
#141

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
try new version!
