### ISSUE TITLE
Alternatives?

### ISSUE THREAD

**Issue by diegohaz** [react-icons/react-icons#133]
Since this project is not maintained anymore, do you guys recommend any other alternative?

**Comment by mmmeff** [comment]
Or alternatively, would the current maintainer be willing to pass the torch on? This project is amazing and I'd hate to see it stagnate.

**Comment by JeffersonFilho** [comment]
I agree! Would be good if @gorangajic passed it to someone so we can still maintain it!

**Comment by gorangajic** [comment]
I have passed project to couple of guys already and no one stick to it. Just ping me with username and I will add you to maintaince list

**Comment by kamijin-fanta** [comment]
@gorangajic please add me to the maintainer.

**Comment by JeffersonFilho** [comment]
@gorangajic I'm happy to give it a shot too!

**Comment by kamijin-fanta** [comment]
I have developed a similar project prototype while waiting. Support of ES Modules, Use of git submodule, Improvement of build speed, TypeScript support etc, and many modern design changes are included.

https://github.com/kamijin-fanta/react-icons-set

Owners of react-icons do not actively develop. I'm thinking about merging this project or developing it independently.

I want idea.

**Comment by JeffersonFilho** [comment]
It sounds good, but I think ideally we should fix the current issues with this one first before thinking of merging anything into it.

Any thoughts?

**Comment by kamijin-fanta** [comment]
I think most of the current Issue is an icon library addition / update. This can be handled quickly.

The biggest problem is that the administrator of this repository is not active.
so, CI setting, npm publish will also take time.

**Comment by diegohaz** [comment]
Maybe @gorangajic should consider transferring the repo and the npm package to someone else altogether.

**Comment by jayehmke** [comment]
@gorangajic I'd be more than happy to take over ownership/be a maintainer. I use it in a few projects already.

**Comment by kamijin-fanta** [comment]
I made an organization of Github. And I invited a collaborator here.
https://github.com/react-icons

I think that only adding npm - owner is good for npm.
If publish npm package as a different name, we do not need to transfer this repo.
ref: https://docs.npmjs.com/cli/owner

**Comment by JeffersonFilho** [comment]
Sounds good to me!

**Comment by kamijin-fanta** [comment]
memo: If we start development with a new code base, the transfer of git repo may not be necessary :thinking_face:

**Comment by gorangajic** [comment]
I have moved the repository to a new organization. You can start from scratch and I would recommend doing so because build and everything else is outdated. When you are ready to publish the new version on npm I will give access

**Comment by kamijin-fanta** [comment]
Thanks!

**Comment by JeffersonFilho** [comment]
Awesome!

**Comment by jayehmke** [comment]
Sounds goo, thanks!

**Comment by ahpearce** [comment]
@gorangajic Is there any chance you could make the github.io.pages source available, or instructions to generate? I'm having trouble generating that page of icons that showed their component name.

**Comment by kamijin-fanta** [comment]
@ahpearce did you try `npm run docs` ? see package.json, bin/generate-docs

**Comment by ahpearce** [comment]
@kamijin-fanta Thanks, I actually hadn't. I initially got a 
```Error: ENOENT: no such file or directory, open '/Users/user/dev/react-icons/publish/fa.html'```
but fixed just by creating the `/publish` sub-directory.

**Comment by baba43** [comment]
Is this an alternative?

https://github.com/wmira/react-icons-kit

**Comment by austinbutler** [comment]
If all you want is Font Awesome, I've been using the dev V5 version of [react-fontawesome](https://github.com/FortAwesome/react-fontawesome/tree/development).

**Comment by kamijin-fanta** [comment]
Currently we are work for support with fa 5. It will be possible to use it if merged.
https://github.com/react-icons/react-icons/pull/141

**Comment by kamijin-fanta** [comment]
The repository was moved to orgs.
Welcome contribution.
