### ISSUE TITLE
Instagram Font Awesome icon different between doc and real

### ISSUE THREAD

**Issue by vietthanhbk1994** [react-icons/react-icons#135]
[https://gorangajic.github.io/react-icons/fa.html](url)
It is Instagram Font Awesome icon in home page `react-icons/lib/fa/instagram` ![capture](https://user-images.githubusercontent.com/16161343/39759262-680c3946-52fc-11e8-9b0c-332b3e5c75e0.PNG)

And this is icon when I use
![capture](https://user-images.githubusercontent.com/16161343/39759419-d41a0352-52fc-11e8-9e58-15a1886eebf6.PNG)
They are different

**Comment by JeffersonFilho** [comment]
I just checked and I can confirm that this is actually a bug, I will have a look at it today after work!

**Comment by daniel93cs** [comment]
The same with Youtube icon. please quick check

**Comment by sapegin** [comment]
You need to use `3.0.0-beta.1` to have it. But the Medium is still old ;-/

**Comment by kamijin-fanta** [comment]
maybe fix in react-icons@3.0.0 / pr: #141
Can you check it?
