### ISSUE TITLE
Tiny mistake in doc

### ISSUE THREAD

**Issue by lukassteiner** [react-icons/react-icons#143]
In the docs at [http://react-icons.github.io/react-icons/fa.html](url), the path to FaHourglass1 should be `react-icons/lib/fa/hourglass-1` instead of `react-icons/lib/fa/hourglass1`.

Applies to FaHourglass2 and FaHourglass3 as well.

**Comment by KromDaniel** [comment]
Same for
react-icons/lib/md/rotate90-degrees-ccw``
should be renamed to
`react-icons/lib/md/rotate-90-degrees-ccw`

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
try new version!
