### ISSUE TITLE
Add fa-times icon

### ISSUE THREAD

**Issue by PeterShershov** [react-icons/react-icons#146]
Hey,
There's no fa-times icon in the fa folder. 

![screenshot from 2018-06-20 10-57-11](https://user-images.githubusercontent.com/16524839/41645176-d960cdd0-7478-11e8-942e-4f4e73b5c862.png)

It's a pretty essential asset as it used in a lot of apps as the "Close" icon.
[https://fontawesome.com/icons/times?style=solid](url)

Thanks!

**Comment by PeterShershov** [comment]
I opened a PR: [https://github.com/react-icons/react-icons/pull/147](url)

**Comment by PeterShershov** [comment]
Added a PR.

**Comment by samvk** [comment]
I believe this is the "FaClose" icon.

https://github.com/react-icons/react-icons/blob/master/fa/close.js

**Comment by PeterShershov** [comment]
Cool, so we can just rename it?
I think it's crucial for this to be consistent with the original names.

WDYT @samvk ?

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
try new version!
