### ISSUE TITLE
Readme typo: md icon example path incorrect

### ISSUE THREAD

**Issue by thesmuggle** [react-icons/react-icons#151]
`import {MdCancel, MdChat, MdCheck} from 'react-icons/md';`
In the above line, there is a `/lib` missing. It should read:
`import {MdCancel, MdChat, MdCheck} from 'react-icons/lib/md';`

**Comment by thesmuggle** [comment]
PR: https://github.com/react-icons/react-icons/pull/152

**Comment by antoinerousseau** [comment]
Will be better in #141
