### ISSUE TITLE
IconContext is not defined

### ISSUE THREAD

**Issue by andyhu92** [react-icons/react-icons#162]
Project scaffolded with create-react-app 1.3.3
React version 16.4.1
React-icons version 3.0.2

Reproduce steps:
1. create-react-app a new project and install react icons
2. Simply include an icon (anyone) and put inside App.js render method
3. App crashed and got error message `ReferenceError: IconContext is not defined`

![error message](http://res.cloudinary.com/dvl0bnhhw/image/upload/v1533196469/Screen_Shot_2018-08-02_at_3.45.38_PM_loravt.png)

The issue **persists** even if I wrapped my code with `IconContext.Provider`

**Comment by raduungurean** [comment]
I'm also getting the same error

**Comment by Wmaileq** [comment]
Line 12 of iconBase.mjs needs to be:
`import { IconContext } from './iconContext';`

**Comment by benoit-hocquet** [comment]
@Wmaileq suggestion fixes the error for me.

**Comment by kamijin-fanta** [comment]
sorry.
I will fix it now.

**Comment by andyhu92** [comment]
It's working now. Thanks!
