### ISSUE TITLE
[v3] Error during gatsby build (UglifyJs) "SyntaxError: Name Expected"

### ISSUE THREAD

**Issue by MaxMcKinney** [react-icons/react-icons#167]
When compiling my project with react icons running v3+ it now fails during my build process (gatsby with UglifyJs)

```javascript
error Generating JavaScript bundles failed

  Error: component---src-templates-project-js-3df92bc7a0d9cb72bfb1.js from UglifyJs
  SyntaxError: Name expected [./~/react-icons/md/index.js:2,0]

  Error: component---src-layouts-index-js-f9d444461bff255c55be.js from UglifyJs
  SyntaxError: Name expected [./~/react-icons/fa/index.js:2,0]
```

It runs fine on my test server without the UglifyJs plugin running.

react-icons is v3.0.4

**Comment by MaxMcKinney** [comment]
Looks like this is a gatsby issue with how they are compiling packages with babel. I'm closing this issue here.

**Comment by chrismaltais** [comment]
@MaxMcKinney did you find a workaround for this? I'm also getting the error.

**Comment by mujuni88** [comment]
I'm also getting this error

**Comment by MaxMcKinney** [comment]
This issue is related to those of us still running Gatsby V1. In v1 the webpack bundler included is using a version of UglifyJS that does not the ES6 syntax included in the react icons version 3+.

The only fixes are to upgrade to Gatsby Beta V2 or downgrade react icons to 2.x
