### ISSUE TITLE
Not working on create-react-app

### ISSUE THREAD

**Issue by JeffersonFilho** [react-icons/react-icons#169]
I finally got some time to test the new version! Thanks @kamijin-fanta for the hard work and the timing you have dedicated to this.

But for some reason it seems that version 3.0 doesn't work with create-react-app, is just me or is this issue happening with someone else as well?

[![Image from Gyazo](https://i.gyazo.com/d9818f5c764245e70c8d87e1ceac53a7.png)](https://gyazo.com/d9818f5c764245e70c8d87e1ceac53a7)

**Comment by kamijin-fanta** [comment]
@JeffersonFilho there are few information that can be read from errors. please upload this project.

**Comment by JeffersonFilho** [comment]
My bad @kamijin-fanta, I will add the steps that I did.

```yarn add react-icons```

```
import React, { Component } from 'react'
import logo from './logo.svg'
import './App.css'
import { FaBeer } from 'react-icons/fa'
class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title"> Welcome to React </h1>
        </header>
        <div>
          <FaBeer />
        </div>
      </div>
    )
  }
}

export default App
```
[![Image from Gyazo](https://i.gyazo.com/14e0071ad511be8df3f2e8a55d8dfdf5.png)](https://gyazo.com/14e0071ad511be8df3f2e8a55d8dfdf5)

**Comment by kamijin-fanta** [comment]
I do not know the version of webpack or react-script etc.
Please upload the repository on github, not paste.

**Comment by kamijin-fanta** [comment]
I am not doing technical support for React Project. If you have problems with react-icons, please provide the smallest repository.

**Comment by JeffersonFilho** [comment]
I understand, but at any moment I was asking for the 'technical support' for that project, I was just mentioning that react-icons wasn't working on create-react-app.

But since it works on a fresh install, this issue can be closed.
