### ISSUE TITLE
v3.0.5 is not working with react-uglify

### ISSUE THREAD

**Issue by davidesigner** [react-icons/react-icons#170]
Hi there,

I am using the `react-icons@3.0.5`.

My imports are made like the following: `import { MdAdd } from 'react-icons/md';`.

All is working when I start my webpack dev server but when I try to build my app, I have the following error from my `webpack.optimize.UglifyJsPlugin`:
```
ERROR in backoffice.688bdd91.js from UglifyJs
SyntaxError: Name expected [./~/react-icons/md/index.js:2,0]
```

Have you any ideas to fix it? Thanks.

**Comment by kamijin-fanta** [comment]
@davidesigner can you provide the smallest repository?

**Comment by davidesigner** [comment]
@kamijin-fanta I was using Webpack 1.
I moved my project from v1 to v3 and all is working now.
