### ISSUE TITLE
All icons have a generic name of Component when snapshot

### ISSUE THREAD

**Issue by jktravis** [react-icons/react-icons#173]
Is there something I'm doing wrong here, or do we lose the icon names when upgrading? 

Before upgrading, if I add an icon of `<FaBeer/>` that name would show up in the snapshot. Now, regardless of the icon, I just get `<Component/>`.

**Comment by kamijin-fanta** [comment]
are you using jest?
generation logic of the component was changed, so may have been changed.

**Comment by SBoudrias** [comment]
Sounds like it's now missing a `displayName` static property on each icon components.
