### ISSUE TITLE
'react-icons/fa' does not contain an export named 'FaCloudDownload'

### ISSUE THREAD

**Issue by PaulRBerg** [react-icons/react-icons#174]
## Behavior
Albeit specified on https://react-icons.netlify.com, `FaCloudDownload` is not exported in `react-icons/fa`.

## Versions
- npm `6.3.0`
- react-icons `3.0.5`

**Comment by PaulRBerg** [comment]
According to the fontawesome [website](https://fontawesome.com/icons?d=gallery&q=cloud), `FaCloudDownload` has been renamed to `FaCloudDownloadAlt` in the free version. I think that the problem is actually with your [web app](https://react-icons.netlify.com) docs.

I'll leave this issue open until someone notices it, but it's good to be closed.

**Comment by kamijin-fanta** [comment]
if copy, you will know the correct icon name.
![image](https://user-images.githubusercontent.com/1541187/44451123-c0039700-a62d-11e8-9ed2-879fc4302daa.png)
