### ISSUE TITLE
enzyme/jest tests can't find react-icons components 

### ISSUE THREAD

**Issue by effinrich** [react-icons/react-icons#176]
Hi,
I just finished upgrading and now all my tests that use react-icons are breaking.

The following code fails with result 0, which worked fine with the previous version:
`expect(wrapper.find('FaChevronDown').length).toBe(1)`

Is this a bug or is there a workaround?  Seems like a very odd feature.

**Comment by kamijin-fanta** [comment]
Please submit the minimal sample repository.

**Comment by kamijin-fanta** [comment]
@effinrich may be fix in #195.
try react-icons@3.2.0
