### ISSUE TITLE
Create react app failed to minify

### ISSUE THREAD

**Issue by nickhaughton** [react-icons/react-icons#178]
When minifying my project using create react app, it fails to minify `./node_modules/react-icons/fa/index.js:2 `

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

Is there a reason for this? Can it be cleaned up?

**Comment by kamijin-fanta** [comment]
@nickhaughton can you provide the smallest repository?
It works with demo project using create-react-app.
https://github.com/react-icons/react-icons/tree/master/packages/demo

**Comment by jtan4nih** [comment]
I have the same issue:

Failed to minify the code from this file:

        ./node_modules/react-icons/fa/index.js:2

**Comment by kamijin-fanta** [comment]
There is no update

**Comment by kamijin-fanta** [comment]
why do you give `-1` without submitting a sample repository?
