### ISSUE TITLE
 New Import style documentation 

### ISSUE THREAD

**Issue by kruulik** [react-icons/react-icons#179]
*On the pain page:*
```
import { FaBeer } from 'react-icons/fa';

class Question extends React.Component {
    render() {
        return <h3> Lets go for a <FaBeer />? </h3>
    }
}
```

*On the PR documentation:* 
```
import React from "react";

import { IconContext } from "react-icons";
import { FaFolder } from "react-icons/lib/fa";
import { MdAccessibility } from "react-icons/lib/md";

funciton App () {
  return (
    <IconContext.Provider value={{ color: "#333" }}>
      <div>
        <MdAccessibility />
        <FaFolder />
      </div>
    </IconContext.Provider>
  );
}
```

**Comment by kruulik** [comment]
Is it `"react-icons/lib/fa"` or `"react-icons/fa"` ??

**Comment by itsalysialynn** [comment]
```react-icons/lib/fa```

But, if you want to just import the icon you need, this is better: 

```react-icons/lib/fa/beer```

**Comment by kamijin-fanta** [comment]
Which file should be modified?

**Comment by obouchari** [comment]
If you're using version 2:
`import FaBeer from 'react-icons/lib/fa/beer';`
For version 3 use:
`import { FaBeer } from 'react-icons/fa';`

Reference: https://www.npmjs.com/package/react-icons#migrate-from-version-2---3
