### ISSUE TITLE
How to import compiled version?

### ISSUE THREAD

**Issue by Woolseyyy** [react-icons/react-icons#181]
The guide in readme confuses me. I want to import compiled version because I don't want to use babel to compile my node_modules.
I tried with:
`import {FaChevronCircleLeft as BackIcon} from 'react-icons/lib';`
but BackIcon is undefined.
What's the correct importing method?
Thank you!

**Comment by itsalysialynn** [comment]
```import { FaChevronCircleLeft as BackIcon } from 'react-icons/lib/fa/chevron-circle-left';```

**Comment by itsalysialynn** [comment]
That's the best way to import it, because you are not importing the whole library.  You will also see it done like this: 

```import { FaChevronCircleLeft as BackIcon } from 'react-icons/lib/fa'; ```

This imports the whole Font Awesome library so it is way larger.

**Comment by Woolseyyy** [comment]
@itsalysialynn I have tried the latter way, but lib has no directory below

**Comment by kamijin-fanta** [comment]
please see reference. https://react-icons.netlify.com/#/icons/fa
`lib` dir used in old version.

```js
import { FaChevronCircleLeft as BackIcon } from 'react-icons/fa';
```

**Comment by Woolseyyy** [comment]
@kamijin-fanta 
you mean, if I want to import compiled icon, I must use old version?

**Comment by kamijin-fanta** [comment]
@Woolseyyy I do not understand your message.
I want you to see a demo project.

https://github.com/react-icons/react-icons/tree/master/packages/demo

**Comment by Woolseyyy** [comment]
@kamijin-fanta
I have read it.
The importing way in document is es6, needing babel compile this module.
I notice that document mention another way to import icons from compiled directory. But I don't know how to.
I don't want to use babel to compile node_modules. But es6 can't run on low browsers.

**Comment by Woolseyyy** [comment]
@kamijin-fanta

> If you are not using an ES6 compiler like Babel or Rollup, you can include icons from the compiled folder ./lib. Babel by default will ignore node_modules so if you don't want to change the settings you will need to use files from ./lib.

This is in readme. Can you give me an example about it?

**Comment by kamijin-fanta** [comment]
@Woolseyyy I'm sorry. The above description is an old description. I delete it.

You do not need to build node_modules with babel.
es modules are supported by webpack.

**Comment by kamijin-fanta** [comment]
@odusseys my jest is working :smile:
https://github.com/react-icons/react-icons/blob/master/packages/demo/src/App.test.js

**Comment by odusseys** [comment]
You may not have the exact same setup as we do. 
Either way this really isn't the point, we shouldn't have to compile code which is written in your "flavour" of javascript ; you can't assume exactly how people will be using it, and you can't expect them to rewrite their build configuration just to include your project. 

Right now we've downgraded to v2 just because of this. We're not spending hours tweaking our build configs just to include an icon pack.

**Comment by kamijin-fanta** [comment]
goodbye. I blocked you.

Other people who are troubled want you to upgrade to new Webpack settings or new react-scripts. This project structure is the same as other libraries such as graphql, and you will fall down.

- GraphQL structure: https://unpkg.com/graphql@14.1.1/language/
- ReactIcons structure: https://unpkg.com/react-icons@3.3.0/lib/

jest does not support `.mjs`, so you need to use `.js`.
But, if uses `.js` in webpack, the bundle gets bigger, so you need to use `.mjs`.

ref: https://github.com/facebook/create-react-app/pull/5258
