### ISSUE TITLE
Version 3.0.5 Fails Build With Create-React-App

### ISSUE THREAD

**Issue by ronaldroe** [react-icons/react-icons#182]
Upon updating to the latest version in hopes of getting access to more icons, I noticed that to get the icons to work while developing, I couldn't go through `/lib` as is recommended. So, importing looks like this:
```
import { MdPerson } from 'react-icons/md';`
```
That works during development. However, the build process can't resolve it. Oddly, only FontAwesome works through `/lib`, and the build process can't resolve it either.

Using `react-dom 16.4.2`, `react-scripts 1.1.4` and `react-icons 3.0.5`.

I am able to downgrade to an older version of React-Icons, and it works again.

**Comment by kamijin-fanta** [comment]
@ronaldroe Please submit the minimal sample repository.

**Comment by mslooten** [comment]
@ronaldroe I had the same issue. You might want to try to upgrade `react-scripts` to version `1.1.5`, that resolved the issue for me.

**Comment by kamijin-fanta** [comment]
no updates
