### ISSUE TITLE
Font Awesome Heartbeat icon missing

### ISSUE THREAD

**Issue by sensorii** [react-icons/react-icons#183]
I can't find it when upgrading from react-icons v2 to v3.

https://github.com/react-icons/react-icons/blob/2.2.7/fa/heartbeat.js
https://fontawesome.com/icons/heartbeat?style=solid

It is missing?

**Comment by kamijin-fanta** [comment]
FaHeartbeat?

**Comment by sensorii** [comment]
that works, I see it now.  thanks!
Must've been something temporarily mixed up with my development environment.  I see that [fa/heart-o](https://github.com/react-icons/react-icons/blob/2.2.7/fa/heart-o.js) is what is actually missing(?), and I see outline versions for Font Awesome icons discussed [here](https://github.com/react-icons/react-icons/issues/158).
