### ISSUE TITLE
Icon className includes string "undefined"

### ISSUE THREAD

**Issue by ahutchings** [react-icons/react-icons#189]
**Describe the bug**
When rendering an icon with a className, and there is no className set in IconContext, the resulting className includes the string "undefined".

**Minimal sample repository**
https://codesandbox.io/s/53n74mxz24

**Expected behavior**
The resulting className should only consist of the className string provided via props.

**Screenshots**

<img width="865" alt="screen shot 2018-09-22 at 1 27 13 pm" src="https://user-images.githubusercontent.com/35026/45919926-48fb3180-be6b-11e8-84f7-ed06f9c09af9.png">

**Additional context**
The bug appears to be in iconBase.tsx here: https://github.com/react-icons/react-icons/blob/30ee1d374d20f1125a6815329145d843e163b029/packages/react-icons/src/iconBase.tsx#L35.

Would you accept a PR to fix this? Would you prefer to fix it by using the `classnames` library to concatenate the string, or by updating the existing logic without using a dependency?

**Comment by kamijin-fanta** [comment]
@ahutchings 
I'm sorry for the late reply.
PR is welcome.
It is preferable not to use additional libraries.

**Comment by drkohlipk** [comment]
Just submitted PR for fix.
