### ISSUE TITLE
Set Baseline for icons

### ISSUE THREAD

**Issue by leesdolphin** [react-icons/react-icons#19]
The GitHub Octicons have a baseline slightly below centre and this causes them to display slightly off when rendered through react-icons. I don't have any time at the moment to throw together a JSFiddle; but I'll try and make one tomorrow.

The GitHub Octicons have a baseline set at `-18.75%`(Taken from the descent divided by 1024 in the [Octicons SVG](https://github.com/github/octicons/blob/master/octicons/octicons.svg?short_path=0908706#L17).

**Comment by kamijin-fanta** [comment]
If you have an update please comment again.
