### ISSUE TITLE
Unclear how to use

### ISSUE THREAD

**Issue by axelkennedal** [react-icons/react-icons#192]
**Is your feature request related to a problem? Please describe.**
It is not clear how to use any other icon pack than the Font Awesome one. I've tried looking around the repo for occurances of "feather" without finding anything.

**Describe the solution you'd like**
Please provide examples for each icon pack.

**Describe alternatives you've considered**
Not using this package.

**Additional context**
-

**Comment by stavalfi** [comment]
+1

I have no idea actually show on the screen an icon.

**Comment by mikelax** [comment]
You can [look at the docs](https://react-icons.netlify.com/#/icons/fi) that should each set of icons with the appropriate namespace. 

ie. here is how you would use the google material design github logo. 
`import { GoMarkGithub } from 'react-icons/go';`

Here is a feather import:
`import { FiAlertTriangle } from 'react-icons/fi';`

**Comment by kamijin-fanta** [comment]
please see documents site
https://react-icons.netlify.com/

**Comment by mikelax** [comment]
@axelkennedal  I will open a quick PR to update the README to point to the docs for icon usage.
