### ISSUE TITLE
Using it with `create-react-app v2` import everything in final bundle.

### ISSUE THREAD

**Issue by frederikhors** [react-icons/react-icons#193]
Using it with `create-react-app v2` import everything in final bundle using this import:

`import { FaBell } from 'react-icons/fa'`

How to fix this?

Maybe Babel 7 which is the news in `create-react-app`? Changelog: https://reactjs.org/blog/2018/10/01/create-react-app-v2.html

**Comment by jptissot** [comment]
I have the same issue. This might be because they dropped support for .mjs files.

**Comment by jptissot** [comment]
Well I spoke too quickly. https://github.com/facebook/create-react-app/releases/tag/v2.0.4 They just re-added .mjs support.

**Comment by ivan-aksamentov** [comment]
Regardless of `create-react-app`, in case you are getting bundles of ginormous sizes, even when with importing only a couple of icons from `react-icons`, try to add `.mjs` to the [list of file extensions resolved by webpack](https://webpack.js.org/configuration/resolve/#resolve-extensions). Make sure you don't forget the rest of extensions you need (e.g. for JSX and Typescript):

`webpack.config.js`:

```js
module.exports = {
  ...
  resolve: {
    extensions: [
      ".js",
      ".jsx",
      ".ts",
      ".tsx",
      ".mjs"    // <- add this
    ]
    ...
  }
  ...
}
```

**Comment by kamijin-fanta** [comment]
.mjs should be given priority over .js.

like:

```js
resolve: {
  extensions: ['.mjs', '.web.js', '.js', '.json', '.web.jsx', '.jsx'],
}
```

https://github.com/facebook/create-react-app/blob/v2.0.4/packages/react-scripts/config/webpack.config.prod.js#L218
