### ISSUE TITLE
How do I remove the underline asthetic from react-icons?

### ISSUE THREAD

**Issue by transluciddata** [react-icons/react-icons#194]
I am having some problems trying to remove the underline aesthetic in react-icons. I tried to remove it with 'text-decoration: none', but didn't do anything. Though, I am able to change size or colour. Could anyone point me out what I am missing? There is any way to avoid this underline aesthetic in a global way? Thanks in advance!

`import React from 'react'
import { FaFacebook, FaInstagram} from 'react-icons/fa'
import '../styles/style.scss'

const SocialLinks = () => (
  <ul className='social'>
    <a className='socialIcon' id='foo' href='https://www.facebook.com/user'>
      <FaFacebook />
    </a>
 
    <a className='socialIcon' href='https://www.instagram.com/user/'>
      <FaInstagram  />
    </a>

  </ul>
)

export default SocialLinks`

SASS

`.social {
        display: flex;
        justify-content: space-around;
        align-items: center;
        .socialIcon {
            font-size: 2.5vw; // That works!
            color: black; // That works!
            text-decoration: none; // That doesn't work!
        }
}`

**Comment by kamijin-fanta** [comment]
It does not seem to be related to react-icons.
