### ISSUE TITLE
The feather icons are not latest

### ISSUE THREAD

**Issue by aaron-fe** [react-icons/react-icons#199]
**Describe the bug**
The [feather icons](https://react-icons.netlify.com/#/icons/fi) are different from https://feathericons.com/.

![image](https://user-images.githubusercontent.com/4002586/47125659-4b5c7a00-d2b7-11e8-91e9-c29c1c74d7f2.png)

![image](https://user-images.githubusercontent.com/4002586/47125668-57e0d280-d2b7-11e8-95c3-6e5bde1de308.png)

**Comment by paulclifford** [comment]
Please update to the latest Feather Icons, they are soooo much nicer than these old ones.

**Comment by kamijin-fanta** [comment]
there was a mistake. I'm sorry.
I want you to try `react-icons@3.2.2`
