### ISSUE TITLE
Importing MdLocationHistory causes error

### ISSUE THREAD

**Issue by Abisar** [react-icons/react-icons#202]
**Describe the bug**
`MdLocationHistory` does not exist in `react-icons/md/` but in the [demo](http://react-icons.github.io/react-icons/md.html) the icon exists.

**Comment by kamijin-fanta** [comment]
@Abisar sorry. please see new documents.

old(version2): http://react-icons.github.io/react-icons/
new(version3): https://react-icons.netlify.com/
