### ISSUE TITLE
Github.io page VS Netlify page

### ISSUE THREAD

**Issue by donatoaz** [react-icons/react-icons#203]
Hi folks! Is there any particular reason why there is a github.io page for the iconsets (seemingly outdated)?

http://react-icons.github.io/react-icons/index.html

VS

https://react-icons.netlify.com/#/

**Comment by kumarharsh** [comment]
The github.io page is for the older version (v2). The netlify one is for the new v3 version. I'd prefer if this was not changed for the meanwhile as there are devs like me who are still using v2 (v3 has some breaking changes which would need a refactor). It should be clarified in the github.io page that it's for v2.
