### ISSUE TITLE
FaGooglePlus fontawesome icons don't fit their viewport

### ISSUE THREAD

**Issue by vietthanhbk1994** [react-icons/react-icons#206]
**Describe the bug**
FaGooglePlus not fix their viewport

**Minimal sample repository**
Viewport
![image](https://user-images.githubusercontent.com/16161343/48709232-7845d900-ec37-11e8-8a1b-b6e64fd9f5f2.png)

Reality
![image](https://user-images.githubusercontent.com/16161343/48709273-914e8a00-ec37-11e8-88ae-7718eafa2eb0.png)

**Comment by kamijin-fanta** [comment]
@vietthanhbk1994 sorry. please see new documents.

old(version2): http://react-icons.github.io/react-icons/
new(version3): https://react-icons.netlify.com/
