### ISSUE TITLE
Material Design Icon Style

### ISSUE THREAD

**Issue by steverecio** [react-icons/react-icons#212]
I'm able to import Material Design icons but how do I apply the icon style? Ie. outline, filled, rounded, etc. I'm currently only able to use filled icons but would like to import icons with style outline

https://material.io/tools/icons/?icon=folder&style=outline

**Comment by steverecio** [comment]
Just realized the Readme header was a link to https://react-icons.netlify.com/#/

🤦‍♂️

**Comment by danielpickett** [comment]
I'm looking for an answer to this very question. I don't see how the above comment helps to answer the question. Nothing in the linked documentation answers the question on how to use the icons in other styles like outlined, rounded, sharp, etc. 

@steverecio Were you able to find the answer to your question at the link above?

**Comment by steverecio** [comment]
@danielpickett I didn't see a way to actually change the icon style but if you look at the list of icons available, you'll see that some icons are offered in different styles (ie: MdError & MdErrorOutline)

**Comment by danielpickett** [comment]
Thanks for the quick response. That's a shame. I was mostly interested in the rounded theme/style like this: https://material.io/resources/icons/?icon=alarm&style=round.

It works flawlessly with their icon font as you can see in [this codepen example](https://codepen.io/danielpickett/pen/zYvWyEP), but I want inline SVG from React components, not an icon font. 😢 

Oh well. Maybe I'll open another issue.
