### ISSUE TITLE
async load svg and cache it in localStorage

### ISSUE THREAD

**Issue by ShanaMaid** [react-icons/react-icons#213]
thanks for your rep, that is very cool!

I have a tool named [archer-svgs](https://github.com/ShanaMaid/archer-svgs) that can async load svg and cache it in localStorage.Dont reload `100kb` svg bundle only for `1kb` svg update!

**Comment by kamijin-fanta** [comment]
Thank you for an interesting proposal.

However, I think that it is unusual to include a 100kb bundle.
One application uses several icons.
If you configure Webpack correctly, you can bundle only the icons that are in use.

If you have problems with your project, look at this issue. https://github.com/react-icons/react-icons/issues/154

**Comment by ShanaMaid** [comment]
thx!
