### ISSUE TITLE
A lot of icons are missing from all packages

### ISSUE THREAD

**Issue by mcmwhfy** [react-icons/react-icons#216]
Seems that a big part of icons are unavailable:

`Attempted import error: 'FaLineChart' is not exported from 'react-icons/fa'.`

Looking into node modules (fa/index.d.ts) seems that the FaLineChart is not exported and there are a lot of icons in this situations. 
So basically now are only less than a half available :|

What could be the problem ?

    "react-icons": "^3.3.0",

**Comment by bensontrent** [comment]
You can either downgrade to v2, or update your code to use the new import methods of version 3.   See [https://github.com/react-icons/react-icons#migrate-from-version-2---3](https://github.com/react-icons/react-icons#migrate-from-version-2---3)

**Comment by kamijin-fanta** [comment]
Please refer to the document https://react-icons.netlify.com/#/icons/fa
```jsx
import {FaChartLine} from 'react-icons/fa';
```
