### ISSUE TITLE
Add Fa-Meteor

### ISSUE THREAD

**Issue by mrwadepro** [react-icons/react-icons#220]
Can the meteor icon be added?

[`Icon`](https://origin.fontawesome.com/icons/meteor?style=solid)

**Comment by arkadyt** [comment]
@mrwadepro, I think you'll have to make a PR yourself.

**Comment by kamijin-fanta** [comment]
fix in v3.6.1. https://github.com/react-icons/react-icons/releases/tag/v3.6.1
try it!
