### ISSUE TITLE
3.6 beta causes error: react-icons not found in [my node_modules directory] when trying to build Webpack DLL

### ISSUE THREAD

**Issue by Slapbox** [react-icons/react-icons#227]
I upgraded to 3.6 to try to fix another issue and I noticed this. Not sure what change might cause this.

**Comment by kamijin-fanta** [comment]
please provide a repository.

**Comment by Slapbox** [comment]
I've simply excluded react-icons from my DLL generation due to time constraints, but if anyone else runs into this, they at least have a starting point for their issue here.
