### ISSUE TITLE
Invalid DOM property `xmlns:xlink`. Did you mean `xmlnsXlink`?

### ISSUE THREAD

**Issue by tim-soft** [react-icons/react-icons#229]
The initial React render always yields the error in the title with the GitHub icon. Other icons don't seem to throw this error.

```js
import { DiGithubBadge } from 'react-icons/di';

<DiGithubBadge size="2.5em" />
```

**Minimal sample repository**
https://codesandbox.io/s/1ln0vn6xq

**Desktop (please complete the following information):**
 - Device: [PC]
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [74]

**Comment by kamijin-fanta** [comment]
thanks! fix in v3.6.1. https://github.com/react-icons/react-icons/releases/tag/v3.6.1
