### ISSUE TITLE
FaMugHot icon is not exported

### ISSUE THREAD

**Issue by aman1106** [react-icons/react-icons#236]
**Describe the bug**
I am trying to import FaMugHot icon but it says 'FaMugHot' is not exported from 'react-icons/fa';
Other icons are working fine.

**Expected behavior**
Should have rendered the icon component

**Additional context**
Attempted import error: 'FaMugHot' is not exported from 'react-icons/fa'.

**Comment by jlu24** [comment]
I am having the same issue but it happens when I try to make a new import of the react-icons library (starting from scratch). I believe this has been an issue since the last commit since it has failed 1/2 checks when updating TypeScript... I double-checked to make sure if I guessed correctly by testing the import with [RunKit](https://npm.runkit.com/react-icons); the result was an error...

**Comment by ronaldroe** [comment]
Several of the Font Awesome icons are missing. `FaCircleONotch`, `FaTimesCircleO`, and several others I've tried throw the same error. I've looked at the `index.js` in the `fa` folder, and they are in fact not exported. I'm guessing they either got missed, or maybe deliberately omitted during one of the recent updates...?

**Comment by Shadowman4205** [comment]
FaBabyCarriage has same issue

**Comment by Shadowman4205** [comment]
FaBaby has same issue

**Comment by Shadowman4205** [comment]
@kamijin-fanta Is this gonna be fixed?

**Comment by kamijin-fanta** [comment]
What version are you using? It seems to be importable.
Current package version is `react-icons@v3.8.0`.

![image](https://user-images.githubusercontent.com/1541187/68302194-ddaf0600-00e4-11ea-86e4-074868e338ae.png)
https://react-icons.netlify.com/

and...
`TimesCircleO` does not exist in fa5.
https://fontawesome.com/icons?d=gallery&q=TimesCircle

**Comment by aman1106** [comment]
Now I am using version 3.7.0 and it is working perfectly fine. Earlier when I raised issue it was version 3.4.0 in which it was giving error.
@kamijin-fanta Thanks for resolving and update.

**Comment by melvin175** [comment]
This problem is usually because your Import module can't actually access or find the icon in the modules directory which you've commanded in. Make sure you give the correct location for importing and you're importing the right thing from a right folder from modules
