### ISSUE TITLE
Wifi-Slash icon disappeared on updating to 3.6.1

### ISSUE THREAD

**Issue by kumarharsh** [react-icons/react-icons#244]
**Describe the bug**
I'm using the react-icons library for quite some time, and I upgraded recently to the latest version. I found that one of the icons (`FaWifiSlash`) disappeared from the exported icons. It was there in the `3.6.0` version, but not there in `3.6.1`.

**Minimal sample repository**
Go to this sandbox: https://codesandbox.io/s/bold-star-y3efp
Now, in the sidebar, under the dependencies section, change the version of `react-icons` to `3.6.1` (it's currently `3.6.0`). There will be a react error that says: 

```
Invariant Violation
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
```

**Expected behavior**
The `FaWifiSlash` icon should render

**Comment by kamijin-fanta** [comment]
It has moved to a paid version.
https://fontawesome.com/icons/wifi-slash
