### ISSUE TITLE
Add search bar to online documentation

### ISSUE THREAD

**Issue by pavinduLakshan** [react-icons/react-icons#256]
**Is your feature request related to a problem? Please describe.**
It is very hard, painful and time consuming to search for an icon in the docs. If I want to look for an icon, I need to manually go through each and every icon in the web page as there is no search bar in the page.

**Describe the solution you'd like**
Adding a search bar to the online documentation https://react-icons.netlify.com/#/ would be great.

**Comment by gorbs** [comment]
Haha! I've got a pull request sitting for that very thing: https://github.com/react-icons/react-icons/pull/254
Can't see how to add reviewers for it.
