### ISSUE TITLE
Travis-ci build failing

### ISSUE THREAD

**Issue by gorbs** [react-icons/react-icons#257]
**Describe the problems**
The Travis-ci build is failing. Some where between building pull request #241 and #247 it looks like yarn was updated from v1.3.2 to v1.15.2 and it is now spitting out following errors.

Last working build: [194](https://travis-ci.com/react-icons/react-icons/builds/129366055).
Failing from build: [195](https://travis-ci.com/react-icons/react-icons/builds/129366240).

**Expected behavior**
Build should pass and autodeploy to netlify.

**Errors**
```
$ (cd packages/react-icons/ && yarn build && npm pack)
/home/travis/.travis/functions: line 109: ./node_modules/.bin/yarn: No such file or directory
The command "(cd packages/react-icons/ && yarn build && npm pack)" exited with 127.
```

**Desktop (please complete the following information):**
Travis-ci.

**Comment by kamijin-fanta** [comment]
thanks!
fix in https://github.com/react-icons/react-icons/pull/262
