### ISSUE TITLE
docs: typo FaLinkedinIn

### ISSUE THREAD

**Issue by AndersDJohnson** [react-icons/react-icons#259]
**Describe the bug**
Docs say `FaLinkedinIn`.

**Minimal sample repository**
https://react-icons.netlify.com/#/icons/fa

**Expected behavior**
The icon appears to actually be named just `FaLinkedin`.

**Screenshots**
![Screen Shot 2019-10-18 at 5 31 38 AM](https://user-images.githubusercontent.com/615381/67087530-b78ee980-f168-11e9-8ba9-2d9521b4d591.png)

**Comment by abuuzayr** [comment]
@AndersDJohnson this is not an error. There are two icons: **FaLinkedinIn** and **FaLinkedin**.

![image](https://user-images.githubusercontent.com/19371989/71537668-3f0f8a80-295a-11ea-87b4-72143b14f7ad.png)

I tested them both as well with the current version 3.8.0 and they work fine. 

![Screenshot 2019-12-28 at 10 06 10 AM](https://user-images.githubusercontent.com/19371989/71537662-2b642400-295a-11ea-9cc2-69799db6dddf.png)

See here: https://codesandbox.io/s/falinkedinin-test-9g1dc
