### ISSUE TITLE
Multi Color Icons

### ISSUE THREAD

**Issue by cardimajs** [react-icons/react-icons#263]
Hi,
When i try to import multi colored icons like https://github.com/icons8/flat-color-icons

I get a single color icons:
![image](https://user-images.githubusercontent.com/5782144/67554185-3e9e0d80-f6e5-11e9-8cf6-dc1bd91c4c17.png)

is possible to get colored icons?

Thanks!.

EDIT!!!
After changing the source code i can get multi colored icons working
![image](https://user-images.githubusercontent.com/5782144/67558891-3e564000-f6ee-11e9-89bc-346a011d6658.png)

i just add to /packages/react-icons/src/icons/index.js a key called multiColor
![image](https://user-images.githubusercontent.com/5782144/67559035-81181800-f6ee-11e9-841a-0858321a6c36.png)

and edit the /packages/react-icons/scripts/build.js 

that is a good idea?

**Comment by Slapbox** [comment]
I like this a lot. @kamijin-fanta are there any downsides to enabling this on the `master` branch??

**Comment by kamijin-fanta** [comment]
Good idea! Is it possible to submit a PR?

**Comment by Eeslam10** [comment]
great work
