### ISSUE TITLE
[Demo Website] Crash when typing "Fau"

### ISSUE THREAD

**Issue by rodperottoni** [react-icons/react-icons#274]
**Describe the bug**
Typing "Fa" followed by the letter "U" on the search box will crash the demo website 🤔

**Expected behavior**
Being able to type "FaU" ?

**Comment by Lemaro86** [comment]
If I typing  "def" - too cathc crash

**Comment by abuuzayr** [comment]
yes I can confirm this is happening at least for `def` and `fau`.

I launched the docs in both development mode with `yarn serve` and also ran `yarn build` and served the distribution files and both were working ok. 

Could there be something broken / incorrect settings when deploying to Netlify? It even looks broken:

![8AAD3EF5-2C46-4557-A7CB-2C34295A70AB](https://user-images.githubusercontent.com/19371989/71541736-95032300-2998-11ea-9c1d-c60ae7897484.jpeg)
(_left: production, right: local_)

**Comment by kamijin-fanta** [comment]
This seems to be improving now. I want you to try again.

**Comment by abuuzayr** [comment]
If anyone else is still encountering this, clear your cache or do a hard refresh (CTRL + SHIFT + R). Thanks @kamijin-fanta !
