### ISSUE TITLE
New icon library: CSS.gg

### ISSUE THREAD

**Issue by heuristicAL** [react-icons/react-icons#277]
How complex would it be to add https://css.gg to the available icons?

It is MIT licensed :)

**Comment by abuuzayr** [comment]
Probably not complex but this is an SVG library and CSS.gg is a CSS icon library. You can use css.gg directly or use the API to conditionally add required icons only.

**Comment by kamijin-fanta** [comment]
Yes. This repository currently only contains SVG icons.

**Comment by farism** [comment]
It looks like they just shipped v2 with support for various other formats, including svg 

https://github.com/astrit/css.gg/tree/master/icons/svg

**Comment by kamijin-fanta** [comment]
That's good news!
