### ISSUE TITLE
Icon Updates

### ISSUE THREAD

**Issue by dubble-G** [react-icons/react-icons#281]
How often do you update react-icons to pull in new icons that may have been added?  For example, here is a free font awesome icon that you all are not currently pulling in that I would like to use via react-icons:

https://fontawesome.com/icons/caravan?style=solid

**Comment by vojtaholik** [comment]
+1

Remix icons aren't updated as well.

**Comment by kamijin-fanta** [comment]
It available in v3.10.0. try it!
https://github.com/react-icons/react-icons/releases/tag/v3.10.0
