### ISSUE TITLE
Color bug when there is svg at the same component

### ISSUE THREAD

**Issue by birutaibm** [react-icons/react-icons#288]
**Describe the bug**
If you have a component with an svg and some icon, that icon uses the svg fill property instead of their own color.

**Minimal sample repository**
https://github.com/birutaibm/react-icons-colors-bug

**Expected behavior**
The lock icon be blue (the same color of the text) instead of red

**Screenshots**
![Captura de tela de 2020-02-20 13-36-59](https://user-images.githubusercontent.com/19666564/74957380-35e4ec00-53e6-11ea-94cb-82bd4a04e803.png)

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Linux Mint
 - Browser chrome
 - Version 80.0.3987.116 (Versão oficial) 64 bits

**Additional context**
At the repository you can find the solution I am using, but I think that a more user transparent solution (included into the react-icons) would be better.
Thank you

**Comment by kamijin-fanta** [comment]
It seems difficult to improve because CSS selector priorities are related.
