### ISSUE TITLE
On Mobile, the menu doesn't collapse

### ISSUE THREAD

**Issue by imarchit19** [react-icons/react-icons#291]
**Description**
While accessing the mobile site of react-icons.netlify.com, the menu hampers in readability of site.
There is no option to minimize/close it, only way is to go for Desktop Site.

**Expected behavior**
I feel the menu should be collapsible so that one can access the site without going for Desktop Site. 

**Screenshots**
![bug_mobile_react](https://user-images.githubusercontent.com/31448375/75894094-bc271680-5e59-11ea-84d4-3b5f7f61d0ef.png)

**Desktop **
 - Device: Mi A3
 - OS: Android 10
 - Browser: Microsoft Edge
 - Version: 45.01.4.4900

**Comment by wesbos** [comment]
Looks like the repo version does have a mobile menu. Maybe the netlify deploy isn't working?

![image](https://user-images.githubusercontent.com/176013/75895299-72134600-5e03-11ea-8a21-59802f125853.png)

**Comment by imarchit19** [comment]
I think this issue was resolved and we can close the issue, right?
