### ISSUE TITLE
Upgrade to IonIcons v5

### ISSUE THREAD

**Issue by akphi** [react-icons/react-icons#294]
Hi,

Thanks for making this super useful library (and the website as well :) ). I was just wondering if we could upgrade this to IonIcons v5 since it just came out and has many new good-looking icons over there. Let me know if I could help in some way.

**Comment by ptoly** [comment]
I took a shot at upgrading to 5.0.1. Not fully tested, but, so far, seems to work fine: git@github.com:ptoly/react-icons.git

**Comment by garmeeh** [comment]
Would also love to see v5 of IonIcons. 

@ptoly happy to give a hand if needed getting a pull request open for the upgrade?

**Comment by ptoly** [comment]
@garmeeh Thanks! Yea, I'm not sure how to do a pull request from a forked branch....

**Comment by garmeeh** [comment]
Hey @ptoly, so luckily GitHub make it straight forward enough for us. 

So on your fork you should see the pull request option:

![image](https://user-images.githubusercontent.com/13333582/83024428-4bd9fc80-a026-11ea-85ae-adda44eab659.png)

From here this should open the pull request editor for you and automatically point your base fork master branch at the original repo master. 

![image](https://user-images.githubusercontent.com/13333582/83024593-880d5d00-a026-11ea-92e8-cff3fdbaf8fb.png)

Let me know how it goes.

**Comment by ptoly** [comment]
Boom. Done. Thanks Gary!

**Comment by garmeeh** [comment]
I also took a shot at this but the icons did not render correctly. No errors or anything tho 🤔 

<img width="1473" alt="image" src="https://user-images.githubusercontent.com/13333582/85622826-5c01ed80-b65f-11ea-91c4-28ca5f469d55.png">
