### ISSUE TITLE
Documentation breaks on search

### ISSUE THREAD

**Issue by micaeldias** [react-icons/react-icons#297]
**Describe the bug**
Searching "fau" in the documentation throws an exception "t is not a function"

**Minimal sample repository**
https://react-icons.netlify.com/#/search

**Expected behavior**
Icons with fau in the name should appear

**Comment by kamijin-fanta** [comment]
It worked on my PC 🤔 

![image](https://user-images.githubusercontent.com/1541187/79980945-d3d85e00-84de-11ea-9f91-522ee3ddef7a.png)

**Comment by kamijin-fanta** [comment]
This seems to be improving now. I want you to try again.

**Comment by micaeldias** [comment]
Can confirm it's fixed for me now.
