### ISSUE TITLE
Add Box Icons

### ISSUE THREAD

**Issue by brunosra** [react-icons/react-icons#298]
Hi all. Thanks for this great lib!
I'd like to suggest adding the Box-icons: https://github.com/atisawd/boxicons

It's a great icon lib with more than 1000 icons.

Thanks in advance!

**Comment by TrejoCode** [comment]
Please <3

**Comment by AdsonCicilioti** [comment]
Hey man! Boxicons implementation are incomplete. Boxicons have more icons.
The brand logos set is not present on react-icons/bi.

**Comment by LinHuiqing** [comment]
Is this going to be addressed soon? Icons such as the `bank` icon are still missing from `react-icons/bi`
