### ISSUE TITLE
Name of this icon?

### ISSUE THREAD

**Issue by zRelux** [react-icons/react-icons#301]
I know this is a weird question but what is the name of this icon? [Icon](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F1393680%2Fequalizer_filter_filtering_refine_sort_sorting_icon&psig=AOvVaw2C7_5RmNKO9liF6VOKPdfz&ust=1586797037062000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNCV4eCt4-gCFQAAAAAdAAAAABAD) I can't remember...

**Comment by TrejoCode** [comment]
You can search it: https://react-icons.netlify.com/#/search
Similar: Settings, Control.
Close it if you find it or any similar.

**Comment by zRelux** [comment]
Thank you I was able to find it!
