### ISSUE TITLE
 Actual size (1391205) of tarball .../@fluentui/react-icons/-/react-icons-0.1.4.tgz) did not match the one specified in 'Content-Length' header (1651956)

### ISSUE THREAD

**Issue by moizgh** [react-icons/react-icons#302]
**Describe the problems**
failing consistently on package installation.

**Expected behavior**
installation should not fail

**Errors**
```
Error: Actual size (1391205) of tarball (...@fluentui/react-icons/-/react-icons-0.1.4.tgz) did not match the one specified in 'Content-Length' header (1651956)
```

**Desktop (please complete the following information):**
 - Device: Hosted agent
 - OS: Windows_NT
 - Browser N/A
 - Version N/A

**Comment by kenotron** [comment]
This is the wrong repo. The actual repo is here: https://github.com/microsoft/fluentui/
