### ISSUE TITLE
How do I change the size of the icon in CSS?

### ISSUE THREAD

**Issue by NehaChaudhary311** [react-icons/react-icons#320]
**Describe the problems**
I want to increase the size of the icon and I tried doing it using CSS in a CSS file using this
```
.arrow{
    color: aliceblue;
    size: 40px;
}
```
but it doesn't change the size of the code. Please help.

**Comment by mrmartineau** [comment]
@NehaChaudhary311 there is no `size` property in CSS, but there is a `size` prop for these icon components. Use this if you want to change the size of an icon.

```jsx
<FiRss size="30px" />
```

I understand your confusion because the docs do not tell you how to manipulate the icons at all.

**Comment by visus100** [comment]
@NehaChaudhary311 i know it's a little late for answer but you can manipulate icon size in CSS by property font-size if icon component is child of div

Example:

jsx
```
<div id="container">
 <FiRss />
</div>
```

css
```
#container{
 font-size: 40px;
}
```

**Comment by ajoslin103** [comment]
none of these answers are working...

**Comment by gustavonikov** [comment]
@NehaChaudhary311 i'm more late than visus100, but, for others who might come to this topic, u can edit the size in CSS like this:  
     Example with the Icon being the firstchild:
           parent-element :first-child {
                 width: 20px;
           }

note: if the icon is not the firstchild, just use other property like nth-child(), that gets the position of the child.
