### ISSUE TITLE
AiOutlineMergeCells icon not available

### ISSUE THREAD

**Issue by prathd** [react-icons/react-icons#323]
**Issue**

The following line of code runs into the issue where there is no exported member. After further investigation the icon `AiOutlineMergeCells` is not exported in any package (specifically `ai`).

```
import { AiOutlineMergeCells } from "react-icons/all";
```

**Screenshots**

The icon is available according the the https://react-icons.github.io/react-icons/ search tool.

![image](https://user-images.githubusercontent.com/7470145/83977805-46579e80-a8d1-11ea-8ba5-6fab85c0ddea.png)

**Comment by kamijin-fanta** [comment]
Included in the latest react-icons. please try it.
