### ISSUE TITLE
Using two tone icons

### ISSUE THREAD

**Issue by teagueash** [react-icons/react-icons#324]
Has anyone gotten the ant design Two Tone icons working?

**Comment by kuroshhashemi** [comment]
@teagueash did you figure it out?

**Comment by teagueash** [comment]
It’s not the cleanest solution but yeah I was able to with Styled
Components. Can post a gist, just let me know.

**Comment by kuroshhashemi** [comment]
I would love to see it if you don't mind.  My temporary workaround was downloading the svg and assigning a different color to each path

**Comment by teagueash** [comment]
Assigning a color to each path is the main idea, I just do it through selectors: https://codesandbox.io/s/angry-neumann-jee3u?file=/src/App.js

**Comment by kuroshhashemi** [comment]
Ah oh I get it now, thanks much!
