### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by vishalkdotcom** [react-icons/react-icons#326]
I see no updates since end of April, 2020. Community is adding PRs since then. But they aren't merged yet.

So, I was just curious, if it's still active.

**Comment by cmcaboy** [comment]
April 2020 was just two months ago. Personally, I don't consider a project inactive until at least 6 months of inactivity... sometimes more.

**Comment by vishalkdotcom** [comment]
Actually, this is an amazing package. I'm using it in multiple projects. I need some icons packs to be upgraded. So, I used a custom fork meanwhile. Plus pushed a PR as well. I can wait on that. :)

I just wanted to know, if it's still being maintained. I would love to contribute more.

**Comment by aliogaili** [comment]
The project is moving to slow, the PRs are not hard to merge, and it is causing a lot of pain especially with bundle size and folks are moving away.

If the current maintainers can't merge that PR, we better fork it and move o.

**Comment by aliogaili** [comment]
I've forked the repo here until we get some traction https://github.com/aliogaili/meronex-icons

**Comment by OnurGvnc** [comment]
cc:  @kamijin-fanta

**Comment by vishalkdotcom** [comment]
Glad to see @kamijin-fanta back. :)
Hope everything is all right there.
