### ISSUE TITLE
Please update ionicons to version 5.x

### ISSUE THREAD

**Issue by cge** [react-icons/react-icons#333]
Currently, the `iconicons` version exposed by `react-icons` is `4.5.6`, as mentioned here: https://github.com/react-icons/react-icons#icons

However, the official [ionicons](https://github.com/ionic-team/ionicons) project is already at version [5.x](https://github.com/ionic-team/ionicons/blob/master/CHANGELOG.md), which looks much nicer IMHO.

Please consider an update :)

**Comment by kamijin-fanta** [comment]
fixed in #372
