### ISSUE TITLE
`AiOutlineSend ` is not rendering. 

### ISSUE THREAD

**Issue by yilmazbingo** [react-icons/react-icons#339]
< AiOutlineSend/>  creates React warning:

Warning: React does not recognize the `pId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in path (created by AiOutlineSend)
    in svg (created by Context.Consumer)
    in IconBase (created by AiOutlineSend)

```
import React from "react";
import { GiMiner, GiReceiveMoney } from "react-icons/gi";
import { AiOutlineSend } from "react-icons/ai";
import { GrTransaction } from "react-icons/gr";
import "./side-menu.scss";

const SideMenu = () => {
  return (
    <aside className="sideBar">
      <div>
        <GiMiner />
        <h5> Overview</h5>
      </div>
      <div>
        <AiOutlineSend />
        <h5>Send</h5>
      </div>
      <div>
        <GiReceiveMoney />
        <h5>Receive</h5>
      </div>
      <div>
        <GrTransaction />
        <h5>Transactions</h5>
      </div>
    </aside>
  );
};

export default SideMenu;

```
I have been using react-icons for a while and this is the first time I saw this issue.

**Comment by kamijin-fanta** [comment]
dup https://github.com/react-icons/react-icons/issues/344

it's fixed.
