### ISSUE TITLE
How to appropriately create a loader in webpack?

### ISSUE THREAD

**Issue by codetony25** [react-icons/react-icons#34]
Right now this is the loader i'm using in my webpack:

```
  {
    test: /react-icons\/(.)*(.js)$/,
    loader: 'babel',
    include: config.iconPath
  }
```

with config.iconPath pointing to my "node_modules/react-icons" path.

This all works, however currently every time I start my localhost dev, it takes around 8-10 seconds for it to finally be viewable in the browser. Is this normal? Or am I doing this wrong? Thank you!

**Comment by jsierles** [comment]
I also see this load time. Probably because there are lots of small files that all need to be transformed when you require a full icon set?

**Comment by gorangajic** [comment]
You should include every icon separately. This module is created with that in mind so user of your app only gets what is needed

**Comment by olegyanchinskiy** [comment]
I'm using the webpack configuration above but getting a module error
   
    Module parse failed: /Users/oyachinskiy/Documents/ichnaea-root/web-      reporting/public/map/node_modules/react-icons/fa/beer.js Unexpected token (8:12)
    You may need an appropriate loader to handle this file type.


Here is the main portion of my webpack file 

    var config = {
	    iconPath: 'node_modules/react-icons'
    };

    module.exports = {
	entry: './main.js',
	output: {path: __dirname, filename: 'bundle.js'},
	module: {
		loaders: [
			{
				test: /.jsx?$/,
				loader: 'babel-loader',
				exclude: /node_modules/,
				query: {
					presets: ['es2015', 'react']
				}
			},
			{
				test: /react-icons\/(.)*(.js)$/,
				loader: 'babel',
				include: config.iconPath
			},
			{
				test: /\.scss/,
				loader: 'style!css!sass'
			}
		]
	   }
    };

In the actual component I'm importing exactly as stated in the documentation.

    import FaBeer from 'react-icons/fa/beer';

Any idea what could be causing this?

**Comment by osmonus** [comment]
@olegyanchinskiy 
Maybe not the more elegant solution, but it works if you include each path explicitly:

`      
{
        test: /(\.js|\.jsx)$/,
        loader: 'babel',
        include: [path.resolve(__dirname, './node_modules/react-icons/fa'), path.resolve(__dirname, './node_modules/react-icons/go')],
        query: { presets: ['es2015', 'stage-0', 'react'] }
      }  
`

**Comment by supr-d** [comment]
@olegyanchinskiy 
Maybe it wil help:
npm i --save-dev babel-plugin-transform-export-extensions

**Comment by olegyanchinskiy** [comment]
Thanks guys! @supr-d @osmonus

**Comment by kiliwalk** [comment]
I'd like to say that we should publish a package with es5-compatible(babel it first), so that no extra babel-ify for this package

**Comment by loicginoux** [comment]
@olegyanchinskiy I have the same issue with webpack, did you find a solution ?
@supr-d solution does not work for me and I cannot include each path explicitly.

**Comment by olegyanchinskiy** [comment]
@loicginoux Yes I was able to find a solution for this. I mostly followed what @osmonus provided above. 

Here is the relevant part of the loader: 

    {
				test: /.jsx?$/,
				loader: 'babel-loader',
				exclude: /node_modules/,
				query: {
					presets: ['es2015', 'react']
				}
			},
			{
				test: /(\.js|\.jsx)$/,
				loader: 'babel',
				include: [path.resolve(__dirname, './node_modules/react-icons/fa'), path.resolve(__dirname, './node_modules/react-icons/go')],
				query: {
					presets: ['es2015', 'react']
				}
			}

Separating all the paths seemed to fix the problem but there's probably a more elegant solution. Let me know if you have any more questions.

**Comment by oldo** [comment]
I was able to resolve this issue by including the following loader in my webpack config:

```
{
    test: /react-icons\/(.)*(.js)$/,
    loader: 'babel',
    query: {
      presets: ['es2015', 'react']
    }
}
```

**Comment by CerratoA** [comment]
To resume best solution is by @olegyanchinskiy 
But take in consideration this:
I was just copy pasting his code, but he is using fa and go.
Update the code to resolve your needs, mine were material design = md
so I used :

```
{
        test: /(\.js|\.jsx)$/,
        loader: 'babel',
        include: [path.resolve(__dirname, './node_modules/react-icons/md'), path.resolve(__dirname, './node_modules/react-icons/fa'))],
        query: {
            presets: ['es2015', 'react']
        }
      },
```

**Comment by cristyansv** [comment]
In the new versions of webpack it is necessary to put the suffix `babel-loader` @oldo 
```
{
    test: /react-icons\/(.)*(.js)$/,
    loader: 'babel',
    query: {
      presets: ['es2015', 'react']
    }
}
```

**Comment by oldo** [comment]
Thanks @cristyansv 
Good to know.

**Comment by bkniffler** [comment]
I'd love to see a es5 compatible version of this, just like react-router!

**Comment by DaveyEdwards** [comment]
When dynamically loading icons like this is it inevitable to see long  compile times? 

![2017-04-09_21-28-19](https://cloud.githubusercontent.com/assets/15203899/24846054/3e76f7ea-1d6c-11e7-9f74-03d4116856ba.gif)

I am using the babel-loader
```
    {
      test: /react-icons\/(.)*(.js)$/,
      loader: 'babel-loader',
      query: {
        presets: ['es2015', 'react']
      }
    }
```

**Comment by kamijin-fanta** [comment]
Package structure was changed from react-icons@3.0.0. try it.
