### ISSUE TITLE
Possible collaboration with SVG Icons / Styled Icons / Emotion Icons

### ISSUE THREAD

**Issue by jacobwgillespie** [react-icons/react-icons#342]
Hey @kamijin-fanta / `react-icons` maintainers! 👋 I'm the maintainer of [Styled Icons](https://github.com/styled-icons/styled-icons), [Emotion Icons](https://github.com/emotion-icons/emotion-icons), and [SVG Icons](https://github.com/svg-icons/svg-icons)...

Would you be interested in collaborating to adopt unified sources and tools here in React Icons? Over the past two years I've built the following tooling:

- The @svg-icons NPM org re-publishes upstream icon packs as optimized SVGs, cleaning up any issues (like hard-coded colors, extra classnames, etc)
- The [@styled-icons](https://github.com/styled-icons/styled-icons) and [@emotion-icons](https://github.com/emotion-icons/emotion-icons) projects take the SVGs published to @svg-icons and repack them into React components, wrapped using either Emotion or Styled Components
- All projects have CI tests with TypeScript as well as visual regression testing using Chromatic, to ensure that code updates don't break the icons
- Dependabot initiates dependency update PRs, meaning that when upstream icon packs release new versions, the icon projects pick them up automatically
- All projects use [Changesets](https://github.com/atlassian/changesets) for automatic releases to NPM (handled by @icon-bot)

The Styled and Emotion Icons projects also have a few React niceties developed over the past few years, including:

- The ability to import all icons (`styled-icons`)
- The ability to import only individual packs (`@styled-icons/feather`)
- The ability to import individual icons (`@styled-icons/feather/AlertCircle`)
- All of the above support tree shaking (as in, this would resolve #154)
- TypeScript support for everything

---

If you would be interested in collaborating, I believe the benefits would include:

- All projects could benefit from using @svg-icons as their upstream source, so they could all get updated icons as soon as the upstream packs pushed new versions
- The build tooling would reduce the @react-icons maintenance burden
- Styled and Emotion icons would benefit from additional icon packs (@react-icons has a few they don't currently have)
- I would be willing to contribute time maintaining @react-icons, e.g. requests for new icon packs.

This idea is, of course, totally up to you, I just wanted to start the discussion in case you'd find this proposal interesting. If you'd like to discuss further or have any questions, feel free to ping me here or via email at jacobwgillespie@gmail.com.

Thanks! ❤️

**Comment by kamijin-fanta** [comment]
Thank you for your wonderful suggestions! I will check your work when I have time.

**Comment by jacobwgillespie** [comment]
Perfect, thanks for the reply!
