### ISSUE TITLE
React does not recognize the `pId` prop on a DOM element

### ISSUE THREAD

**Issue by dmusato** [react-icons/react-icons#344]
**Describe the bug**

React throws exception when you are using some of Icons. For example "**AiFillFormatPainter**".

React, gives this exception in Chrome: 
index.js:1 Warning: React does not recognize the `pId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `pid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Expected behavior**
No Exception

**Screenshots**
![image](https://user-images.githubusercontent.com/3994386/88936427-94fb3680-d28b-11ea-96ce-e91d3819094d.png)

**Comment by philohelp** [comment]
There seems to be a pull request to address the problem here : https://github.com/react-icons/react-icons/pull/310

Any news ?

**Comment by dmusato** [comment]
Looks great! But i think it's not in release. Do you know when it will be in release? on 3.10 it's the same

**Comment by MejanH** [comment]
Still getting errors from `Ai` icons.

**Comment by kamijin-fanta** [comment]
thanks report. fix in this pr. works fine with the latest react-icons version. https://github.com/react-icons/react-icons/pull/378
