### ISSUE TITLE
Simple icons

### ISSUE THREAD

**Issue by krychaxp** [react-icons/react-icons#351]
Why there is no "react-icons/si" ?
The website :https://react-icons.github.io/react-icons/icons?name=si have it , but package doesn't have it. :(

**Comment by jamiejohnsonkc** [comment]
+1

**Comment by Bant89** [comment]
Hi!
I was having the same problem updating to version **3.11.0** fixed for me =)

**Comment by kamijin-fanta** [comment]
Works fine with the latest version.
