### ISSUE TITLE
I cannot import some remix icons

### ISSUE THREAD

**Issue by ArjunAtlast** [react-icons/react-icons#353]
I am not able to import some of the remix icons. It is showing that the icon is not exported from 'react-icons/ri'. I have tried to import **RiSurveyLine, RiDraftLine and RiTestTubeLine**.

I am getting the error on compilation:
```
Attempted import error: 'RiSurveyLine' is not exported from 'react-icons/ri'.
```

My react-icons version is react-icons@3.11.0.

**Comment by kamijin-fanta** [comment]
@ArjunAtlast Will it be reproduced with the latest react-icons? Please submit the smallest project.
