### ISSUE TITLE
Add RPG-Awesome font icons

### ISSUE THREAD

**Issue by devcshort** [react-icons/react-icons#359]
Request to add [RPG-Awesome](https://github.com/nagoshiashumari/Rpg-Awesome) font icon library.

Licensed under BSD-2-Clause License

**Comment by delacannon** [comment]
Hi,

All icons from the [RPG-Awesome](http://nagoshiashumari.github.io/Rpg-Awesome/) library are included in the [Game Icons](https://react-icons.github.io/react-icons/icons?name=gi) group. RPG-Awesome is a curated list of rpg related icons from the same source.
