### ISSUE TITLE
Not all icons are downloaded from Game-Icons

### ISSUE THREAD

**Issue by Zanoshky** [react-icons/react-icons#360]
The following icons are not downloaded from game-icons:
https://game-icons.net/1x1/delapouite/matchbox.html
https://game-icons.net/1x1/delapouite/sesame.html
https://game-icons.net/1x1/delapouite/wire-coil.html
https://game-icons.net/1x1/delapouite/clothes.html
https://game-icons.net/1x1/delapouite/sewing-string.html

https://game-icons.net/1x1/delapouite/cape-armor.html
https://game-icons.net/1x1/delapouite/heart-armor.html
https://game-icons.net/1x1/delapouite/sonic-shoes.html
https://game-icons.net/1x1/delapouite/dragon-shield.html
https://game-icons.net/1x1/delapouite/crescent-staff.html
https://game-icons.net/1x1/delapouite/winged-scepter.html

**Comment by kamijin-fanta** [comment]
Please use the latest react-icons. It may have been added in v4.0.0.
