### ISSUE TITLE
[RFC] Improve Query Search Times

### ISSUE THREAD

**Issue by ChrisCates** [react-icons/react-icons#369]
**Is your feature request related to a problem? Please describe.**
When typing into the search bar for icons. The app can become incredibly slow. This is because of how many elements it needs to render.

**Describe the solution you'd like**
There are countless ways to optimize the search bar. In all honesty, I haven't reviewed the source. But just wanted to open an issue to start a discussion about it.

**Comment by kamijin-fanta** [comment]
The cause is not in the rendering. Icon file download time is slow.

**Comment by ChrisCates** [comment]
@kamijin-fanta, the fix should be simple then. Lazy load images sequentially. Loading 10 images concurrently should make sure the browser doesn't freeze on majority of computers.

**Comment by ChrisCates** [comment]
Ill send a pull request later tomorrow.

**Comment by kamijin-fanta** [comment]
Thanks! I wait for PR.

**Comment by gabrii** [comment]
It seems the issue was the unnecessary rendering (or at least part of the issue). Check out the version on my PR: https://gabrii.github.io/react-icons/search?q=react
https://github.com/react-icons/react-icons/pull/384

**Comment by ChrisCates** [comment]
@gabrii, this works like a charm. I just needed it to stop gobbling my RAM.
Thank you, hopefully @kamijin-fanta will be able to review and merge into master.
