### ISSUE TITLE
NextJS 500 Error when importing 2 Librariers

### ISSUE THREAD

**Issue by danielbarenkamp** [react-icons/react-icons#371]
**Describe the bug**
I am trying to import 2 libraries with 
```
import { BsBag, BsPerson } from 'react-icons/bs'
import { FaFacebook, FaInstagram, FaYoutube } from 'react-icons/fa'
```

But I always get a 500 error. No error log nothing .. if I uncomment one import line it works.The compiling also works.

**Minimal sample repository**

```
import { BsBag, BsPerson } from 'react-icons/bs'
import { FaFacebook, FaInstagram, FaYoutube } from 'react-icons/fa'
```

**Expected behavior**
Both icons should work

**Screenshots**
![Bildschirmfoto 2020-09-30 um 10 41 54](https://user-images.githubusercontent.com/3169388/94662881-4ad51680-0309-11eb-94ff-6e2087699736.png)

![Bildschirmfoto 2020-09-30 um 10 45 03](https://user-images.githubusercontent.com/3169388/94663143-9daece00-0309-11eb-8e98-bb50ac29587d.png)
![Bildschirmfoto 2020-09-30 um 10 44 58](https://user-images.githubusercontent.com/3169388/94663146-9e476480-0309-11eb-946e-16a07106774c.png)

**Desktop (please complete the following information):**
 - Device: MAC
 - OS: MacOS 
 - Browser Chrome
 - Version latest

**Comment by kamijin-fanta** [comment]
Please provide all configuration files such as package.json and detailed error messages.
