### ISSUE TITLE
'IconContext' only refers to a type, but is being used as a namespace here. TS

### ISSUE THREAD

**Issue by klendi** [react-icons/react-icons#375]
**Describe the bug**
When I try to use the IconContex to add values it shows error `'IconContext' only refers to a type, but is being used as a namespace here`

**Minimal sample repository**
`import { IconContext } from "react-icons";`
`      return <IconContext.Provider value={values}>
      </IconContext.Provider>`

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Chrome
 - React Icons version: 3.11.0
 - Chrome Version: 86.0.4240.183 (Official Build) (x86_64)

**Comment by kamijin-fanta** [comment]
It's always working fine in this sample project. Please submit the smallest project. 
https://github.com/react-icons/react-icons/blob/master/packages/ts-test/src/App.tsx
