### ISSUE TITLE
Possible to add FontAwesome Pro to this if we provide a pro key?

### ISSUE THREAD

**Issue by corysimmons** [react-icons/react-icons#382]
Currently FontAwesome Pro is kind of a pain in the butt to use, whereas react-icons is really, really, easy to use. It'd be nice if we could just provide an env var for the pro key and be able to use FontAwesome Pro.

**Comment by kamijin-fanta** [comment]
Thank you for opening the issue.

There are currently no plans to support FA Pro. react-icons converts SVG to JavaScript and publish to npm. This process requires an open source license.
