### ISSUE TITLE
npm latest version is still v4.1 while the Github latest release is v.4.2

### ISSUE THREAD

**Issue by lynxerious** [react-icons/react-icons#410]
**Describe the bug**
So I just found some icons in the github pages cannot be imported into my project. It turned out there is a new version two days ago and when I do npm install v4.2, it gives me an error.

**Expected behavior**
Be able to install the latest version of git on npm.

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser: Chrome
 - Version: 4.1

**Additional context**

**Comment by nolanleung** [comment]
Just release v4.2.0 to npm
