### ISSUE TITLE
Handful of Remix icons missing from the build

### ISSUE THREAD

**Issue by Foxhoundn** [react-icons/react-icons#418]
**Describe the bug**
There are bunch of Remix icons missing from the build version 4.2.0 (So far I've only found RiSortAsc, RiSortDesc).

**Minimal sample repository**
import * as Remix from 'react-icons/ri';

**Expected behavior**
The icons should be there, since they are available on the demo site.

**Screenshots**
![Screenshot 2021-02-25 at 09 57 49](https://user-images.githubusercontent.com/8861481/109128604-eef3aa00-774f-11eb-8960-121dfd059e6c.png)

**Desktop (please complete the following information):**
 - Device: MacBook Pro 2015 13"
 - OS: Latest Big Sur
 - Browser: irrelevant

**Comment by isaacparker2** [comment]
Believe it's this: https://github.com/react-icons/react-icons/pull/402
fix was merged but not released yet

**Comment by deep-c** [comment]
Has this fix been released yet? Looks like the PR was merged. Would be great to have it :)

**Comment by hacknug** [comment]
I've published a fork of this package with all of the missing Remix icons. Details on https://github.com/react-icons/react-icons/issues/446#issuecomment-865823421
