### ISSUE TITLE
Question: Is this project still maintained?

### ISSUE THREAD

**Issue by zaygraveyard** [react-icons/react-icons#42]
Thank you for this is a great library.
But it seams to me that this project is not being maintained anymore

> Latest commit is on 26 May 2016 (a month ago)

If it's the case then a search for a new maintainer might be the best option.

**Comment by gorangajic** [comment]
I am a bit busy and currently do not use project that much myself, if someone want to help I am more than happy to give access

**Comment by bentatum** [comment]
@gorangajic I'd be happy to help.

**Comment by zaygraveyard** [comment]
@gorangajic I too would be happy to help, but I can't actively maintain this project.
So if anyone needs help, let me know.

PS: Sorry for the late reply.

**Comment by jemhuntr** [comment]
@gorangajic @bentatum any updates on whether this will still be maintained? A little hesitant about using it right now.

**Comment by i8wu** [comment]
Looks like there are some pretty old pull requests, is there still a need for more maintainers? o_o...

**Comment by gorangajic** [comment]
If someone want to take over I will be more than happy to give access

**Comment by brillout** [comment]
👍 @gorangajic would be awesome if you add collaborators, I love this lib

**Comment by bentatum** [comment]
@gorangajic see pull requests https://github.com/gorangajic/react-icons/pull/32 & https://github.com/gorangajic/react-icons/pull/35 & https://github.com/gorangajic/react-icons/pull/63

**Comment by i8wu** [comment]
thanks @bentatum and @gorangajic for the hard work!

**Comment by bentatum** [comment]
I'd like give the docs an update. Looks like it's missing at least one icon set and I'd like to make it searchable. @gorangajic cool with you if I take that on?

**Comment by gorangajic** [comment]
you can do it

**Comment by bryan** [comment]
Still active?

**Comment by nwwells** [comment]
@gorangajic I'd be happy to help! Please add me as a Collaborator!

**Comment by antoinerousseau** [comment]
I see that the project title says "not maintained anymore"... I'm happy to help, you can add me as a collaborator if you wish.

**Comment by kamijin-fanta** [comment]
it is active now!
