### ISSUE TITLE
readme to describe props and required/optional?

### ISSUE THREAD

**Issue by colinmccann** [react-icons/react-icons#44]
I had to dig (a little) to find:

IconBase.propTypes = {
color: PropTypes.string,
size: PropTypes.oneOfType([
PropTypes.string,
PropTypes.number
]),
style: PropTypes.object
}

You might want to consider listing the proptypes for the icons eg in the readme. Further, maybe specify that size is required and eg color is not?

**Comment by ryanhca** [comment]
Yes, an example explaining how to use props to adjust the size of icons would be great. +1 here

**Comment by kamijin-fanta** [comment]
Use TypeScript instead of PropType.
