### ISSUE TITLE
Wanted to know whether react-icons can be clicked ?

### ISSUE THREAD

**Issue by crossLineApex** [react-icons/react-icons#445]
**Describe the bug**
I'm trying to add onClick on the react-icon I'm using and its not working
**Minimal sample repository**
Gist/Github URL

**Expected behavior**
This is the line of code
              <AiOutlineSound onSelect={() => console.log("clicked")} />

**Screenshots**

**Desktop (please complete the following information):**
 - Device: [e.g. PC, iPhone6]

**Additional context**

**Comment by crossLineApex** [comment]
Coudn't use it so I placed it inside a button with some css, but this can still be something to look for

**Comment by kamijin-fanta** [comment]
Please use the container element.
