### ISSUE TITLE
Get all list of icons and show it in select box.

### ISSUE THREAD

**Issue by khoaanh2212** [react-icons/react-icons#448]
Dear Team.
I want to get all list of icons and show it in select box.to allow user can search and choose an icon,
do we have any solution for it?

Thanks

**Comment by ambroiseRabier** [comment]
I toyed a bit with whatever clue I found in the source code, and this might help you:

```ts
import * as RiLib from "react-icons/lib";

// @ts-ignore
export const ALL_ICONS = RiLib["IconsManifest"];
console.log(ALL_ICONS);
```
```json
{
    "id": "fa",
    "name": "Font Awesome",
    "projectUrl": "https://fontawesome.com/",
    "license": "CC BY 4.0 License",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0/"
}
```

```ts
import * as ReactIcons from 'react-icons/all';

const j = Object.keys(ReactIcons);
console.log(JSON.stringify(j)); // ['AiFillAccountBook', 'AiFillAlert', ...]
```

Save the the result as a constant, redo if you update the package.

**Comment by Nicolas-PredictaLab** [comment]
> I toyed a bit with whatever clue I found in the source code, and this might help you:
> 
> ```ts
> import * as RiLib from "react-icons/lib";
> 
> // @ts-ignore
> export const ALL_ICONS = RiLib["IconsManifest"];
> console.log(ALL_ICONS);
> ```
> 
> ```json
> {
>     "id": "fa",
>     "name": "Font Awesome",
>     "projectUrl": "https://fontawesome.com/",
>     "license": "CC BY 4.0 License",
>     "licenseUrl": "https://creativecommons.org/licenses/by/4.0/"
> }
> ```
> 
> ```ts
> import * as ReactIcons from 'react-icons/all';
> 
> const j = Object.keys(ReactIcons);
> console.log(JSON.stringify(j)); // ['AiFillAccountBook', 'AiFillAlert', ...]
> ```
> 
> Save the the result as a constant, redo if you update the package.

Interesting approach, but how can you call of those string as component ? For example :
['icon1','icon2'] => <Icon1 /> <Icon2 />

**Comment by Nicolas-PredictaLab** [comment]
Ok I've managed to do it ;)

```
import {useMemo} from 'react'
import * as ReactIcons from 'react-icons/all'

const IconFinder = (): JSX.Element => {
  const renderIcons = useMemo(() => {
    return Object.keys(ReactIcons).map((icon, index) => {
      const Icon = ReactIcons[icon as keyof typeof ReactIcons]
      return <Icon key={index} size={20} />
    })
  }, [])

  return <div className={styles.icons}>{renderIcons}</div>
}
export default IconFinder
```

**Comment by Xevion** [comment]
Is anyone going to close this issue? It appears a solution has been given.
@Nicolas-PredictaLab @khoaanh2212
