### ISSUE TITLE
Update Github Octicons

### ISSUE THREAD

**Issue by beni69** [react-icons/react-icons#450]
Can you guys update the octicons to the latest version?
The version used here is `v8.5.0` while the octicons project is currently at `v14.2.2`.

**Comment by akphi** [comment]
@nolanleung The latest version is now `v16.3.0`, could we consider updating this? Thanks!!

**Comment by nbkhope** [comment]
The GitHub icons (aka [Primer Octicons](https://github.com/primer/octicons)) have been updated frequently and this package could not keep up. The latest version as of today was v17.9.0.

**Comment by Netail** [comment]
Already on v18.3.0, but I really want the draft and closed icons :(
