### ISSUE TITLE
Add Material ui Storefront Icon

### ISSUE THREAD

**Issue by jonasmello** [react-icons/react-icons#459]
Hi, could you add the Storefront icon from the ui material?
It is at https://fonts.google.com/icons and also at https://material-ui.com/pt/components/material-icons/ but it does not appear in the react-icons/md library.

![image](https://user-images.githubusercontent.com/1612563/125993016-13eccf13-bfda-4e3e-8879-67c0c1781bd4.png)
![image](https://user-images.githubusercontent.com/1612563/125993290-0c0e7162-cafd-4966-b515-19a1dc68289b.png)

**Comment by kamijin-fanta** [comment]
Please upgrade to the new react-icons package version.
