### ISSUE TITLE
(node:21908) [DEP0128] DeprecationWarning: Invalid 'main' field in 'E:\Projects\vite-react-ts-starter\node_modules\react-icons\package.json' of 'lib'. Please either fix that or report it to the module author

### ISSUE THREAD

**Issue by callmeberzerker** [react-icons/react-icons#461]
**Describe the bug**

No real need for additional info, I am pretty sure all people running latest node (15) and npm get this warning. Your `main` (most probably) needs to point to `.cjs` entry, and the `module` entry in package.json needs to point to `esm` version of it... at least according to this gist: https://gist.github.com/aelbore/65a4d2e86c3326f36607db111a7b6887

**Comment by JettScythe** [comment]
getting the same issue. Any idea when / if this will be fixed?

**Comment by U-4-E-A** [comment]
I am currently unable to install with either yarn or npm, getting a timeout. Is that related to this issue?

**Comment by DanielsDesigns-au** [comment]
Following on from @callmeberzerker, to fix the warning change the following in the `package.json` file in the directory of `react-icons`

**BEFORE**
```json
"license": "MIT",
  "main": "lib",
  "types": "./lib/esm/index.d.ts",
```

**AFTER**
```json
"license": "MIT",
  "main": "./lib/cjs/index.js",
  "module": "./lib/esm/index.js",
  "exports": {
    ".": {
      "require":  "./lib/cjs/index.js",
      "default": "./lib/esm/index.js"
    }
  },
  "types": "./lib/esm/index.d.ts",
  ```

**Comment by ImRodry** [comment]
Any plans to fix this? I think this is quite an important issue

**Comment by kamijin-fanta** [comment]
Discussed in #509
