### ISSUE TITLE
Error on npm run dev in a Next.js app

### ISSUE THREAD

**Issue by iOrchK** [react-icons/react-icons#466]
**Screenshots**
(node:4621) [DEP0128] DeprecationWarning: Invalid 'main' field in '/Users/iorchdkary/repositorios/nuevo-sol/sigem-webapp/node_modules/react-icons/package.json' of 'lib'. Please either fix that or report it to the module author

**Desktop (please complete the following information):**
 - Device: MacBook Air
 - OS: MacOS BigSur
 - Browser Chrome

**Comment by JettScythe** [comment]
duplicate of #461

**Comment by kamijin-fanta** [comment]
Discussed in #509
