### ISSUE TITLE
Decrease minimum search query length to 2 ?

### ISSUE THREAD

**Issue by cotwitch** [react-icons/react-icons#468]
I've tried to find/search an "at" sign (`@`) at (https://react-icons.github.io/react-icons/search) but I'm unable to do so, because minimum search query is 3 characters. But "at" sign is just 2 characters long. I would bet on that there's more 2-length character icon codes than just "at". So it would be really helpful.

So, is it possible to change minimum search query length to 2 ?

**Comment by Aqzhyi** [comment]
😂

![screenshot-GAbJdNaN](https://user-images.githubusercontent.com/1500206/205644344-5f41e34a-a3dc-490f-aaf7-e21da9947c2d.jpg)

**Comment by cotwitch** [comment]
@Aqzhyi You're right, it's not impossible, but it's not much user-friendly. 

When you have to "figure-out how to find it" at first, instead of just "find what you're looking for" instantly.

So, this issue is not about crying "Boo, I'm unable to find something 😭" ... It's more like "hey, guys, you could make your search feature little more user-friendly" 😉👍
