### ISSUE TITLE
The icons not showing

### ISSUE THREAD

**Issue by Borisboky** [react-icons/react-icons#48]
Hi, 

If I import like `import * as IO from 'react-icons/io` I'm getting error 

_/Users/boris/WebstormProjects/autralis-sales-new/node_modules/react-icons/io/index.js:1
export IoAlertCircled from './alert-circled';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'_

If I import like `import * as IO from 'react-icons/lib/io` I'm not getting an error, but the icons are not showing. The div where `{IO.IoAndroidFavorite}`  is, is empty.

Any advice "zemljace" :) ?

**Comment by gorangajic** [comment]
I think that you need this babel plugin http://babeljs.io/docs/plugins/transform-export-extensions/
on my project it works with current setup

.babelrc
```json
{
    "presets": ["react", "stage-0", "es2015"]
}
```

**Comment by Borisboky** [comment]
I'm getting _Couldn't find preset "stage-0" relative to directory_ error. 

My babelrc looks like : 

```
{
  "presets": ["react", "stage-0", "es2015"],
  "plugins": ["transform-object-rest-spread"]
}
```

**Comment by gorangajic** [comment]
```
npm install babel-preset-react babel-preset-stage-0 babel-preset-es2015 --save-dev
```

**Comment by Borisboky** [comment]
Ok. babel-preset-stage-0 wasn't installed. I installed it, and now I'm not getting the error, but the icons still not showing.

**Comment by MichaelIT** [comment]
maybe u miss size props. like:
`<IconHome size={30} />`

**Comment by kamijin-fanta** [comment]
If you have an update please comment again.
