### ISSUE TITLE
react-icons/ri has no exported member 'RiLinks'.ts

### ISSUE THREAD

**Issue by narutubaderddin** [react-icons/react-icons#481]
I tried to import the Icon 'RiLink' from react-icons
but I got the error "Module react-icons has no exported member RiLink"
https://react-icons.github.io/react-icons/search?q=rilink

**Comment by codeaid** [comment]
#446 is related to this. Looks like tons of icons are missing and this library isn't being updated anymore lately.

**Comment by kamijin-fanta** [comment]
Please upgrade to the new `react-icons` package version.
