### ISSUE TITLE
[IMPORTANT] 4.3.0 release is broken

### ISSUE THREAD

**Issue by PabloSzx** [react-icons/react-icons#490]
these screenshots show 4.2.0 vs 4.3.0

![Screenshot from 2021-10-02 15-22-28](https://user-images.githubusercontent.com/8672915/135727791-f3deec1e-16ac-43f8-9fe9-f4679fdb34e7.png)
![Screenshot from 2021-10-02 15-23-57](https://user-images.githubusercontent.com/8672915/135727819-4f2acb56-fa65-4346-95da-a23e43d4dd0e.png)

**Comment by PabloSzx** [comment]
@nolanleung @kamijin-fanta @westbrookdaniel

**Comment by mickaelxd** [comment]
I was using React-icons 4.2.0. After deleting node modules and reinstalling on my project, it gave the same error that is happening in this issue

**Comment by antoniocanas** [comment]
I can confirm: Module not found: Can't resolve '../lib'
Downgrading to 4.2 solved it

**Comment by caskater4** [comment]
I'm getting the same "Module not found: Can't resolve '../lib'" error. l've downgraded to 4.2 and completely wiped out my node_modules folder. I'm still seeing the error for some reason.

**Comment by caskater4** [comment]
> I'm getting the same "Module not found: Can't resolve '../lib'" error. l've downgraded to 4.2 and completely wiped out my node_modules folder. I'm still seeing the error for some reason.

Looks like this was my mistake. I was setting the dependency to `^4.2.0` instead of `4.2.0` so it was pulling 4.3.0 anyway. Oops!

**Comment by saitodisse** [comment]
> I'm getting the same "Module not found: Can't resolve '../lib'" error. l've downgraded to 4.2 and completely wiped out my node_modules folder. I'm still seeing the error for some reason.

I've tried version 4.1.0 and version 4.0.0. But all remains pointing to 4.3.0.

but i found a fix here:

instead this:
```json
"react-icons": "^4.2.0",
```

use this:
```json
"react-icons": "4.2.0",
```

**Comment by jsteenkamp** [comment]
Confirming same - 4.3 broken, revert to 4.2

**Comment by kalwalt** [comment]
i had the same issue, spent hours to find the reason, but reading here the comments by @caskater4 @saitodisse  save me! i can confirm instead of:

`"react-icons": "^4.2.0",`

use this:

`"react-icons": "4.2.0",`

**Comment by tpkahlon** [comment]
I am facing same issue. You can view log [here](https://github.com/tpkahlon/jackal/runs/3779210601?check_suite_focus=true#step:6:20). I will try the recommendation and keep the version `4.2.0` for now.

**Comment by bayazid18** [comment]
Same issue I already facing. Developer should fixed this asap

**Comment by ddaiane** [comment]
i downgraded to 4.2.0 and i'm still seeing the "is not exported from react-icons" error. 
im already using `"react-icons": "4.2.0"` and i also doublechecked the package-lock.json and even with 4.2.0 version its not working :(

**Comment by grikomsn** [comment]
Anyone reports 4.2.0 also shows an error can do these to help maintainers:

- describe what stack is being used (CRA, Next.js, etc.)
- give a public reproduction repository so anyone can investigate
- just to make sure, try deleting `node_modules` and reinstall packages

**Comment by grikomsn** [comment]
As for @ddaiane, try removing `node_modules` and reinstall packages.

For extra measures, clear the npm cache by running `npm cache clean --force`, remove `node_modules`, and reinstall packages again.

**Comment by sabertazimi** [comment]
Same import issue, details on [failed CI log](https://github.com/sabertazimi/hust-web/actions/runs/1299336674).

**Comment by nolanleung** [comment]
Just pushed a rebuild

**Comment by sabertazimi** [comment]
4.3.1 version works.

**Comment by kalwalt** [comment]
4.3.1 works for me!

**Comment by PabloSzx** [comment]
confirmed, 4.3.1 fixes it, thank you @nolanleung
