### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by minhtaile2712** [react-icons/react-icons#491]
**Describe the bug**
On new version 4.3.0, icon imports fails to work.
Attempted import error: 'FaBeer' is not exported from 'react-icons/fa'.

**Expected behavior**
It should not be a problem when I use this code
`import { FaBeer } from 'react-icons/fa';`
And use `FaBeer` in my project.

**Screenshots**
![image](https://user-images.githubusercontent.com/53080238/135739874-009e1882-3344-45af-8e76-d8fe15cacd15.png)

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Ubuntu (Linux)

**Comment by grikomsn** [comment]
See #490. For now you can downgrade and lock to version 4.2.0.

**Comment by Hamza-Liaqat1** [comment]
Getting same error
error - ./node_modules/react-icons/fa/index.esm.js:2:0
Module not found: Can't resolve '../lib'

**Comment by nolanleung** [comment]
Please upgrade to v4.3.1 for the fix
