### ISSUE TITLE
Import error in both version  4.2.0 and 4.3

### ISSUE THREAD

**Issue by Hamza-Liaqat1** [react-icons/react-icons#492]
error - ./node_modules/react-icons/fi/index.esm.js:2:0
Module not found: Can't resolve '../lib'

**Comment by grikomsn** [comment]
Most reports on #490 shows only `4.3.0` has those import errors.

Make sure the version you use on `package.json` is `4.2.0` and not `^4.2.0`, and double check your lockfile to make sure it's actually using `4.2.0`.

**Comment by nolanleung** [comment]
Please upgrade to v4.3.1 for the fix
