### ISSUE TITLE
Missing icons in icon packages

### ISSUE THREAD

**Issue by harrycarp** [react-icons/react-icons#493]
react-icons package 4.3.0 missing FontAwesome Icons
react-icons package 4.0.0 missing Chevron Ionic Icons

Other icons more than likely missing in 4.X.X packages.

**Comment by korbav** [comment]
> 
> 
> react-icons package 4.3.0 missing FontAwesome Icons react-icons package 4.0.0 missing Chevron Ionic Icons
> 
> Other icons more than likely missing in 4.X.X packages.

Confirmed. Using latest release.

**Comment by donhook** [comment]
I am getting the same issue... i did an npm update and unfortunately went from 4.2 to 4.3 only to encounter a number of errors

**Comment by nolanleung** [comment]
Please upgrade to v4.3.1 for the fix
