### ISSUE TITLE
import error on version @4.3.0

### ISSUE THREAD

**Issue by arslanahmed777** [react-icons/react-icons#495]
whatever icon I  import it gives that error

import { FaBeer } from "react-icons/fa";

ERROR:
./src/components/Navbar/Navbar.jsx
Attempted import error: 'FaBeer' is not exported from 'react-icons/fa'.

**Comment by andrei10k** [comment]
happens to me too

**Comment by arslanahmed777** [comment]
> happens to me too

Downgrade to 4.2.0
npm i react-icons@4.2.0
it will solve the issue

**Comment by andrei10k** [comment]
yeah, i know. i just wanted to signal that it's happening for everyone with the latest version

**Comment by ZamanMehdi** [comment]
> > happens to me too
> 
> Downgrade to 4.2.0 npm i react-icons@4.2.0 it will solve the issue

There are still some icons which are giving the same error

**Comment by donhook** [comment]
I already tried doing that and am unable to do so.    Get library errors

ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/react-icons
npm ERR! dest /Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/.react-icons-eZl8CS5l
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/react-icons' -> '/Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/.react-icons-eZl8CS5l'

npm ERR! A complete log of this run can be found in:

**Comment by nolanleung** [comment]
Please upgrade to v4.3.1 for the fix

**Comment by donhook** [comment]
Upgrading to 4.3.1 didnt work either.... tried uninstalling and reinstalling ...nothing worked.  Not sue what i am doing wrong

 code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/react-icons
npm ERR! dest /Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/.react-icons-eZl8CS5l
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/react-icons' -> '/Users/donaldhook/Library/Mobile Documents/com~apple~CloudDocs/NextJS/fullonconsulting/node_modules/.react-icons-eZl8CS5l'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/donaldhook/.npm/_logs/2021-10-03T18_52_15_321Z-debug.log

**Comment by donhook** [comment]
deleted the react-icons directories then reinstalled - that seems to have worked... thanks for your help on getting 4.3.1 set
