### ISSUE TITLE
Lots of missing material icons that are available on the site but not in the package

### ISSUE THREAD

**Issue by TowhidKashem** [react-icons/react-icons#497]
This may be an issue with other icon sets as well but I'm using only material so am just noticing it there.

On the website:

https://react-icons.github.io/react-icons/icons?name=md

You can see icons such as:

* MdSaveAlt
* MdQrCode
* etc..

but when trying to import them:

`import { MdSaveAlt, MdQrCode } from 'react-icons/md';`

Getting `'"react-icons/md"' has no exported member named ...`  errors.

I'm using the latest version `4.3.1`

**Comment by jcleefw** [comment]
ya we had the same issue with `MdMinus`, `MdOutlineHome` not found

**Comment by DarrylBrooks97** [comment]
Yeah this is still an issue. Tried importing ```IoTriangleSharp``` from the io folder but it's not there
