### ISSUE TITLE
Unable to import/use any of the Material Design icons

### ISSUE THREAD

**Issue by nardove** [react-icons/react-icons#498]
**Describe the bug**
From the Material Design icons directory, I'm unable to import/use any of the outlined icon versions

**Minimal sample repository**
import { MdDoneOutline } from "react-icons/md";

<MdDoneOutline />

**Screenshots**

**Additional context**
Get the following error
```
[1] Compiling...
[1] Failed to compile.
[1]
[1] ./src/Pages/UtilityComponents/Sidebar/index.js
[1] Attempted import error: 'MdDoneOutline' is not exported from 'react-icons/md'.
```

**Comment by bhatvikrant** [comment]
same issue for me as well

**Comment by ccomstudio** [comment]
Attempted import error: 'MdEditCalendar' is not exported from 'react-icons/md'.
