### ISSUE TITLE
AutoComplete/Intellisense not suggesting or importing Components

### ISSUE THREAD

**Issue by n1xn** [react-icons/react-icons#499]
**Describe the bug**
AutoComplete/Intellisense not suggesting or importing Components from node-modules.

**Minimal sample repository**
https://stackblitz.com/edit/github-fvhgyc?file=pages%2Findex.tsx
Fork this and run locally, in browser on StackBlitz I get fully functional suggestions what to import.

**Expected behavior**
Auto Import the corresponding component.

**Screenshots**
![image](https://user-images.githubusercontent.com/30150915/136705891-d9c1437a-6c54-48ba-b0e8-8c9fd648f21a.png)

**Desktop (please complete the following information):**
 - Device: MacBook Pro 2019
 - OS: OSX 10.14.6 (18G87)
 - Browser:
 - Version: 4.1.0

**Comment by jinbe0** [comment]
Relaunching TypeScript server in VSCode did not solve the problem. 
Still showing No suggestions. 
Is this a limitation of Intellisense?

**Comment by indralukmana** [comment]
I also had similar issue, I created a project using `vite` and using TypeScript with `preact-ts` template. The icons from `react-icons`  work when I manually import them one by one, but the auto-complete doesn't work.

I found a fix by adding the `moduleResolution` to `tsconfig.json`. The import auto-complete works with this configuration in my project.

Additional configuration I added to my `tsconfig.json`

```
	"moduleResolution": ["node_modules", "node"]
```

My complete `tsconfig.json` :

<details>
<summary>Show Config</summary>

  ### tsconfig.json
  ```json
    {
	  "compilerOptions": {
		  "target": "ESNext",
		  "lib": ["DOM", "DOM.Iterable", "ESNext"],
		  "allowJs": true,
		  "skipLibCheck": true,
		  "strict": true,
		  "forceConsistentCasingInFileNames": true,
		  "noEmit": true,
		  "esModuleInterop": true,
		  "allowSyntheticDefaultImports": true,
		  "module": "ESNext",
		  "moduleResolution": "Node",
		  "resolveJsonModule": true,
		  "isolatedModules": true,
		  "jsx": "react-jsx",
		  "jsxImportSource": "preact",
		  "importHelpers": true,
		  "preserveSymlinks": true,
		  "baseUrl": ".",
		  "paths": {
			  "@/*": ["src/*"]
		  },
		  "useDefineForClassFields": true
	  },
	  "include": ["src/**/*"],
	  "exclude": ["node_modules", "dist", "public"],
	  "references": [{ "path": "./tsconfig.node.json" }],
	  "moduleResolution": ["node_modules", "node"]
  }

  ```
</details>

**Comment by indralukmana** [comment]
My apologies, seems like I was too fast to come to conclusion.

When I imported an icon from `Boostrap Icon` The import auto-complete works on icons for the same group. But when I tried to import an icon from other icon group, the auto-complete doesn't start. 

- Icon import completion works for `Boostrap Icon` when one of the icons imported already.
![image](https://user-images.githubusercontent.com/4124883/213361137-a81ce48d-bb8a-4bac-8f4d-47274a68e560.png)

- Here I tried importing an icon from `Ionicon` but have never imported it yet. The auto-complete doesn't trigger.
![image](https://user-images.githubusercontent.com/4124883/213361320-dae06d8a-25cd-46f0-83b5-ac223070e382.png)

The Stackblitz for the above:

https://stackblitz.com/edit/vitejs-vite-mdyptx?file=index.html,src%2Fcomponents%2FChatShowButton.tsx&terminal=dev

**Comment by ItsYeWolfie** [comment]
Same issue as @indralukmana, when I import from an already imported group, IntelliCode will work just fine, however if I try to import from some other library, nope.

**Comment by brumasribera** [comment]
How be so great to have this global import suggestions working!

**Comment by usernein** [comment]
For @react-icons/all-files, this saved me: add this into the "include" array on tsconfig.json:
```json
"node_modules/@react-icons/all-files/**/*.d.ts"
```

**Comment by beqarion** [comment]
```
"js/ts.suggest.autoImports": true,
"js/ts.preferences.includePackageJsonAutoImports": "on"
```

This worked for me in VSCodes user > settings.json
