### ISSUE TITLE
GrCertificate not exported

### ISSUE THREAD

**Issue by nabanita-sarkar** [react-icons/react-icons#505]
**Describe the bug**
GrCertificate from `react-icons/gr` is not available to use in typescript file

**Expected behavior**
GrCertificate should have been exported from `react-icons/gr`

**Screenshots**
![image](https://user-images.githubusercontent.com/36895154/138568610-51839e28-28e6-4919-9874-12e042835b07.png)

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Windows
 - Browser: Edge
 - Version: 95.0.1020.30

**Comment by kamijin-fanta** [comment]
Please upgrade to a newer package version.
