### ISSUE TITLE
React Icons import

### ISSUE THREAD

**Issue by web-shoharab-pk** [react-icons/react-icons#536]
**Describe the problems**
ERROR in ./node_modules/react-icons/all.js

**Minimal sample repository**
Gist/Github URL

**Expected behavior**

**Errors**
```
If an error occurs, paste the output.
```

**Desktop (please complete the following information):**
 - Device: [e.g. PC, iPhone6]

**Additional context**

**Comment by max-sym** [comment]
@web-shoharab-pk need more info, this doesn't seem enough to understand your issue

**Comment by fiercedMonkey** [comment]
maybe that's the issue:
`ERROR in ./node_modules/react-icons/all.js 4:0-22
The requested module './io5' contains conflicting star exports for the names 'IoLogoAndroid', 'IoLogoAngular', 'IoLogoApple', 'IoLogoBitbucket', 'IoLogoBitcoin', 'IoLogoBuffer', 'IoLogoChrome', 'IoLogoClosedCaptioning', 'IoLogoCodepen', 'IoLogoCss3', 'IoLogoDesignernews', 'IoLogoDribbble', 'IoLogoDropbox', 'IoLogoEuro', 'IoLogoFacebook', 'IoLogoFlickr', 'IoLogoFoursquare', 'IoLogoGithub', 'IoLogoGoogle', 'IoLogoHackernews', 'IoLogoHtml5', 'IoLogoInstagram', 'IoLogoIonic', 'IoLogoIonitron', 'IoLogoJavascript', 'IoLogoLinkedin', 'IoLogoMarkdown', 'IoLogoNoSmoking', 'IoLogoNodejs', 'IoLogoNpm', 'IoLogoOctocat', 'IoLogoPinterest', 'IoLogoPlaystation', 'IoLogoPython', 'IoLogoReddit', 'IoLogoRss', 'IoLogoSass', 'IoLogoSkype', 'IoLogoSlack', 'IoLogoSnapchat', 'IoLogoSteam', 'IoLogoTumblr', 'IoLogoTux', 'IoLogoTwitch', 'IoLogoTwitter', 'IoLogoUsd', 'IoLogoVimeo', 'IoLogoVk', 'IoLogoWhatsapp', 'IoLogoWindows', 'IoLogoWordpress', 'IoLogoXbox', 'IoLogoXing', 'IoLogoYahoo', 'IoLogoYen', 'IoLogoYoutube' with the previous requested module './io'
`

**Comment by mdddj** [comment]
Same problem, is there a solution?

**Comment by Aziaev** [comment]
check out this solution https://github.com/react-icons/react-icons/issues/528

**Comment by burakakca** [comment]
In my case; when I use yarn I got error. ``` npm install ``` works for me
