### ISSUE TITLE
Access to the classes names of icons

### ISSUE THREAD

**Issue by manuelpoelzl** [react-icons/react-icons#548]
**Is your feature request related to a problem? Please describe.**

It's good that every single icon is returned as a component, but in my opinion it would be very good if you could also access the class name of the icon somehow, many frameworks only allow class names as e.g. icon property of a menu or so.

**Describe the solution you'd like**

A method or property that returns the class name of the respective icon. A method could look like this, for example, that it gets an icon as a parameter and then returns the class name of this icon

**Describe alternatives you've considered**

An alternative to all this, of course, would be to include the respective icon libraries manually, but especially if you want to use multiple icon libraries, this can then become very messy.

**Comment by kamijin-fanta** [comment]
This package do not provide class names.
