### ISSUE TITLE
21 collections on the website but only 17 in the code, why?

### ISSUE THREAD

**Issue by romu70** [react-icons/react-icons#551]
**Describe the bug**
There is a large difference between the react-icons web site which lists 21 icon collections and the Github repository which contains only 17 of them. This makes the website pretty unreliable when it comes to choose an icon.

An example : the website lists Ionicons 4 and 5 collections, but there is neither of them in the code.

I would like to know why this discrepancy. 

Another question, is there a way to specify on the website to show only the icons really available ? Thanks.

**Comment by kamijin-fanta** [comment]
Please upgrade to a newer package version.
