### ISSUE TITLE
'GrCertificate' is not exported from 'react-icons/gr'.

### ISSUE THREAD

**Issue by ebrahimbd** [react-icons/react-icons#552]
i face 'GrCertificate' is not exported from 'react-icons/gr'.
![DeepinScreenshot_select-area_20220414063606](https://user-images.githubusercontent.com/67005999/163291484-3a20e4c4-24e2-44b6-af26-a729e8650877.png)

**Comment by kamijin-fanta** [comment]
Which version are you using? Try the latest version.
