### ISSUE TITLE
Imported icons from react-icons/all can't find export icons.

### ISSUE THREAD

**Issue by bhaskarb360** [react-icons/react-icons#553]
**Describe the bug**
The imported icons from react-icons can't find export icons.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/89518767/163800351-6a8b083f-d9ae-415f-b844-d7347f188d70.png)

![image](https://user-images.githubusercontent.com/89518767/163800188-537f89fe-d8fc-4571-b8e3-b196ea484163.png)

![image](https://user-images.githubusercontent.com/89518767/163800416-ee4536eb-2545-4cd1-888b-93d7e493d33f.png)

**Desktop (please complete the following information):**
 - Device: PC
 - OS: Windows10/11
 - Browser chrome

**Comment by HimanshuMS** [comment]
I'm getting the same issue, the issue started only after I tried to import the **all.js** file, before than when I was individually importing the icons they were being imported, but after importing **all.js** file I started getting the same issue, even after deleting the line and using individual imports the issue still persisted and I couldn't find any solutions online, glad I found this issue opened so I knew at least it's not my fault. Please if there's any way to fix this issue it will be much help, for now I'm using another icon sets for my project.

**Comment by laurenceks** [comment]
@HimanshuMS if you change `react-icons/all` to `react-icons/*` where * is the specific collection the icon is from it should work - make sure there's no reference to `react-icons/all` and your import statements match the collection e.g. 

**won't work**
`import { IoIosCart } from "react-icons/all";`
`import { IoIosCart } from "react-icons/md";`

**should work**
`import { IoIosCart } from "react-icons/io";`

I found my IDE was autocompleting the wrong directories. Not a proper fix but might help you
