### ISSUE TITLE
Feather table icon

### ISSUE THREAD

**Issue by isBatak** [react-icons/react-icons#556]
Feather icon set recently added table icon which is not available in react-icons lib https://github.com/feathericons/feather/commit/f81cd40fdcdd5e94f3f97eb670a5058e3aac528d

**Comment by Aaqu** [comment]
It would be nice if there were the table icon. Can we somehow help to push this forward?

**Comment by kalyan90** [comment]
@isBatak @Aaqu Feather icons table icon is already available on react-icons v5.3.0. I tried to setup a sample project, please have a look https://codesandbox.io/p/sandbox/reactjs-playground-forked-lksvwh?workspaceId=da680cdb-77a3-4ab2-8045-3eb83f570a91.

Also I've tried to change the feather icons integration, https://github.com/react-icons/react-icons/pull/984

**Comment by kamijin-fanta** [comment]
The current react-icons@v5.3.0 includes the contents of feather-icons@4.29.1. Please upgrade package version.
