### ISSUE TITLE
Add Tabler Icons

### ISSUE THREAD

**Issue by MartinMuzatko** [react-icons/react-icons#558]
**react package:** https://www.npmjs.com/package/tabler-icons-react
**original package:** https://github.com/tabler/tabler-icons
Both licensed unter MIT.

I haven't yet worked with the source of this repository, but if there is anything I can do to help, please let me know :)

**Comment by jz222** [comment]
I was about to create the same request. Would be great to see them being part of the library.

**Comment by arifszn** [comment]
+1
