### ISSUE TITLE
Cannot add the library

### ISSUE THREAD

**Issue by MaralS** [react-icons/react-icons#565]
**Describe the bug**
Hello, I tried to add the react-icons library with yarn but I have some issues.
Here is the error message:
```
$ yarn add react-icons
yarn add v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
error @portabletext/types@1.0.3: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "12.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

```

**Desktop (please complete the following information):**
 - Device  : PC
 - OS: W10
 - Browser Chrome

Thanks in advance for helping me.
Maral

**Comment by RubyHuntsman** [comment]
Hey, in error section you can see that you use node in version `12.16.0`.  It's pretty old one. Just bump node to last LTS version if it's possible in your project. To do that use your nvm manager or just install LTS version from official node.js site https://nodejs.org/en/

**Comment by MaralS** [comment]
Ok thank you :)
