### ISSUE TITLE
upgrade @react-icons/all-files version

### ISSUE THREAD

**Issue by mkhalil95** [react-icons/react-icons#568]
**Describe the bug**

can you upgrade the version of `@react-icons/all-files` to match the current version of  `react-icons` to get all the new released icons, as the current version of `@react-icons/all-files` is `4.1.0` and it has some missing icons.

**Comment by codsane** [comment]
> > @pauloavelar piggy backing on Paulo's request to include missing icons from react-icons in @react-icons/all-files.
>
> Someone mentioned in another issue that this single icon per file approach caused the package to reach the NPM file limit, and that is why recent additions haven't been published.
>
> Not really sure if this is true though.
>
> _Originally posted by @pauloavelar in https://github.com/react-icons/react-icons/issues/154#issuecomment-1080016721_

Not sure if this is true but referencing it here for context

**Comment by kamijin-fanta** [comment]
refs #593

**Comment by samantha-wong** [comment]
+1 would love to get an update on this package as well. I'm missing some icons for my icon picker 🙏
