### ISSUE TITLE
Font awesome 6.0

### ISSUE THREAD

**Issue by lpatiny** [react-icons/react-icons#573]
Is there a specific reason that font-awesome is not updated to version 6 ?

Version 6 came out around 4 months ago: https://github.com/FortAwesome/Font-Awesome

**Comment by abhi1693** [comment]
I have forked this awesome library due to inactivity and you can find the most up-to-date icons at https://onemind-services-llc.github.io/react-icons-ng/

**Comment by kamijin-fanta** [comment]
added
