### ISSUE TITLE
Doesn't tree shake when bundled with Webpack and Create React App

### ISSUE THREAD

**Issue by thomscoder** [react-icons/react-icons#574]
**Describe the bug**
React-icons 4.2.0 when bundled with Webpack is importing the entire libraries even when specified to import just one icon. Resulting in 95% of unused code.

`import { CgArrowsShrinkH as Shrink } from 'react-icons/cg'`

**Expected behavior**
I'm expecting to see only the Shrink icon imported.

**Screenshots**
<img width="1908" alt="Screenshot 2022-07-04 100908" src="https://user-images.githubusercontent.com/78874117/177111870-0e6876cf-cfb8-427d-8894-e695ef047d36.png">

Version: 4.2.0 
OS: Windows 10
Browser: Chrome 102.0.5005.11

**Comment by codsane** [comment]
You may need to use `@react-icons/all-files` instead as described here: https://github.com/react-icons/react-icons/issues/154#issuecomment-895976123

**Comment by thomscoder** [comment]
> You may need to import from `@react-icons/all-files` instead as described here: [#154 (comment)](https://github.com/react-icons/react-icons/issues/154#issuecomment-895976123)

Oh alright, will do. Thank you very much @codsane

**Comment by fregante** [comment]
I'm experiencing this issue through https://github.com/rjsf-team/react-jsonschema-form

To the point that most of the weight comes from react-icons, a sub-dependendency of react-jsonschema-form. I looked at their code and they're using the same code suggested in your readme. How come it's failing? Other libraries are being treeshaken, like Lodash.

<img width="1402" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/186429965-8f8b20e9-e906-48a9-ad88-0b0e8acb509f.png">

**Comment by fregante** [comment]
As seen by the recent comments and mentions in https://github.com/react-icons/react-icons/issues/154, this issue still persists and I think it should be fixed in the main package instead of forcing people to discover this on their own and have to fix it every time.

**Comment by thomscoder** [comment]
> As seen by the recent comments and mentions in #154, this issue persists and I think it should be fixed in the main package instead of forcing people to discover this on their own and have to [fix it every time](https://github.com/rjsf-team/react-jsonschema-form/pull/3046).

I agree.
Switched to another package for now.

Thanks to you both, guys!

**Comment by codsane** [comment]
> What is `@react-icons/all-files`? Looks like it's not been updated in years.

I believe this is due to a limitation with the number of files in the package, see #593 and #568.

**Comment by villesau** [comment]
Could make sense to publish all the icon packs as treeshakeable individual packages then 🤔 such as `@react-icons/md` etc.

**Comment by vincerubinetti** [comment]
<img width="458" alt="Screenshot 2024-07-06 at 11 54 43 AM" src="https://github.com/react-icons/react-icons/assets/8326331/99f41662-c60b-4bc2-a417-3fab94cd9dce">

I see that this was closed around the time that v5 was released. Is this still an issue? I'm not seeing anything in the release notes about this.
