### ISSUE TITLE
Module not found: Error: Can't resolve '@react-icons/all-files/Bi

### ISSUE THREAD

**Issue by maligaurav947** [react-icons/react-icons#578]
//React Code

import {
  BiSearch,
  BiX,
  BiHome,
  BiMessageRoundedCheck,
  BiImageAdd,
  BiLayer,
  BiHeart,
} from "@react-icons/all-files/Bi";
_____________________________________________________________________________________________________________________________________

Compiled with problems:

ERROR in ./src/components/Header.js 5:0-119

Module not found: Error: Can't resolve '@react-icons/all-files/Bi' in 'I:\VS-Code\Working On\Instagram-clone-react\instagram-clone-react\src\components'

ERROR in ./src/components/Post.js 5:0-113

Module not found: Error: Can't resolve '@react-icons/all-files/bi' in 'I:\VS-Code\Working On\Instagram-clone-react\instagram-clone-react\src\components'

_____________________________________________________________________________________________________________________________________

i have installed react-icon/all-files
i have try reinstall 
i have imported the react-icon/all-files

but some how it not working

here is my package.json /dependencies

 "@react-icons/all-files": "^4.1.0",
![Capture](https://user-images.githubusercontent.com/86152880/178411175-b55bf6ed-1f9d-4942-83dd-abcfb0068dcc.PNG)

**Comment by NisooJadhav** [comment]
_Try this:_

1) ### ` npm install react-icons --save `

2) ### ``` import {BiSearch,BiX,BiHome,BiMessageRoundedCheck,BiImageAdd,BiLayer,BiHeart,} from "react-icons/bi";```

_using them:_

3) ### `<> <BiSearch /> </>`

_I think this should work, I used to have similar issues when I started with it, but now they're solved.
Hope it helps._
