### ISSUE TITLE
Give a way to use whole pack in an single import 

### ISSUE THREAD

**Issue by rayhan999** [react-icons/react-icons#596]
Need a feature to import the whole pack.

I'm taking the icon names from a json file 
![image](https://user-images.githubusercontent.com/58140227/188201451-1089730c-3252-44d0-b2a7-1d2202b542e9.png)

and then i'm trying to show them. Icons can be from multiple packs(e.g: fa, io,md). So I need a single import line to import the whole pack.
![image](https://user-images.githubusercontent.com/58140227/188201838-aa611309-eabf-4461-b197-4b3d17780b0b.png)

**Comment by nahidiftekhar** [comment]
Does this code from another issue helps you? This way you can use any required icon on the fly.

https://github.com/react-icons/react-icons/issues/594#issuecomment-1236237124

**Comment by rayhan999** [comment]
@nahidiftekhar It worked. Thanks for the help.
