### ISSUE TITLE
"react-icons/hi2" is present on the website but is missing from latest version on npm

### ISSUE THREAD

**Issue by rhazegh** [react-icons/react-icons#597]
**Describe the bug**
- On the website https://react-icons.github.io there is a section for `Heroicons 2`
- The latest version of the package on `nmp` is currently `4.4.0` and was published 3 months ago.
- Using the latest version, `import { IconName } from "react-icons/hi2";`  does not work because `react-icons/hi2` does not exist in the package.

**Expected behavior**
I should be able to import from `react-icons/hi2` namespace.

Are you planning to publish the latest changes under a new version to npm? Is there anything we can do to help make this happen?

**Comment by anakinak** [comment]
I am also facing the same issue, Is there a workaround to get the HeroIcons 2 package

**Comment by rkjain119** [comment]
Since #590 has not yet been packaged and released untill then I'm using heroicons directly from https://heroicons.com/. In v2, the import was modified from` import {BeakerIcon} from '@heroicons/react/solid' `to `import {BeakerIcon} from '@heroicons/react/24/solid'`.

**Comment by IqbolUsta** [comment]
same to me
![image](https://user-images.githubusercontent.com/45452823/188545660-40e51277-6d49-4e3b-9367-94801377b925.png)

**Comment by corysimmons** [comment]
@nolanleung Can we get an npm publish, please?

**Comment by kamijin-fanta** [comment]
Try the latest `react-icons@v4.6.0`.
