### ISSUE TITLE
More info on how to import icons in the website

### ISSUE THREAD

**Issue by LuisEnMarroquin** [react-icons/react-icons#599]
**Is your feature request related to a problem? Please describe.**

When I use the sidebar to search for an icon I can click it and will copy the icon name to my clipboard

![image](https://user-images.githubusercontent.com/35376824/189208961-0327439f-bc8f-4552-aedc-5d50eab46455.png)

But then when I am going to import it in my code I am not sure to which icon library it belongs to

```tsx
import { GiHamburgerMenu } from 'react-icons'
// Module '"react-icons"' has no exported member 'GiHamburgerMenu'.
```

![image](https://user-images.githubusercontent.com/35376824/189209514-9005ac16-64ab-4fd7-8650-f3b3a7ff6e88.png)

![image](https://user-images.githubusercontent.com/35376824/189209785-fcf7573b-4d8b-4fbb-98d8-e3e9d66bf283.png)

**Describe the solution you'd like**

Just figured out while getting screenshots for this `feature request` that icons are prefixed by the library name

```tsx
import { GiHamburgerMenu } from 'react-icons/gi'
```

Probably a tootlip when clicking or hovering some icon will avoid other people to open similar issues 

**Describe alternatives you've considered**

Adding to the [homepage](https://react-icons.github.io/react-icons) that info

**Additional context**

No extra context

**Comment by portableCoder** [comment]
I actually implemented this, check pr #541 .
