### ISSUE TITLE
two icons on docs with exact same name but different .. icons! HiOutlinePlay

### ISSUE THREAD

**Issue by praisethemoon** [react-icons/react-icons#607]
**Describe the bug**
I think `HiOutlinePlay` icon is duplicated or miss documented

**Minimal sample repository**
Invalid for this issue

**Expected behavior**
Each Icon would have its own name and not same name

**Screenshots**
<img width="541" alt="image" src="https://user-images.githubusercontent.com/22145460/190876023-7fbd4db5-9ffb-42b8-8e1c-c2ffff99af55.png">

**Desktop (please complete the following information):**
Invalid for this problem

**Additional context**
FYI it returns the circular one by default (not eggzactly what i wanted) 😔

**Comment by lindapaiste** [comment]
This is related to #598 

The circular version is from heroicons v1 and can be imported as
```
import { HiOutlinePlay } from 'react-icons/hi'
```

The triangle is from heroicons v2, which is not actually in the react-icons package yet (as of v4.4.0).  Once #598 gets fixed and both are in the package then you would need to use the import path to control which version of the icon you want.  You would be able to get the triangle with
```
import { HiOutlinePlay } from 'react-icons/hi2'
```

**Comment by praisethemoon** [comment]
Cool, thank you for the clarification, I will close this issue since there is already a related one that is still open! 
Have a good one!
