### ISSUE TITLE
Old NPM version

### ISSUE THREAD

**Issue by PaulTodd** [react-icons/react-icons#608]
Is it possible to have npm updated to the latest version?

**Comment by VIEWVIEWVIEW** [comment]
@kamijin-fanta Can you take a look if you could publish the latest version of react-icons on npm? :)

**Comment by wottpal** [comment]
@nolanleung push :) otherwise it's not possible to use heroicons2 atm :/

**Comment by darenmalfait** [comment]
🥺 🙏

**Comment by kamijin-fanta** [comment]
`react-icons@4.6.0` published. please try it! https://github.com/react-icons/react-icons/releases/tag/v4.6.0

**Comment by PaulTodd** [comment]
Got the latest and it's got everything.  There is a new warning I get now with Hi2 icons:  Invalid ARIA attribute `ariaHidden`. Did you mean `aria-hidden`.

**Comment by bacali95** [comment]
@PaulTodd can be fixed by #630
