### ISSUE TITLE
FaClockRotateLeft is missing

### ISSUE THREAD

**Issue by yomansk8** [react-icons/react-icons#609]
Hello, 

I want to use the `fa-clock-rotate-left` icon from FontAwesome in my project using `react-icons`, but it seems this one is not exported in it.

The icon: https://fontawesome.com/icons/clock-rotate-left?s=solid&f=classic

I'm not sure how to add it, in this case I'll open an MR.

Thanks!

**Comment by kamijin-fanta** [comment]
please use `FaHistory`. thanks.

**Comment by yomansk8** [comment]
Thanks for the answer, I haven't saw it! 🙏
