### ISSUE TITLE
Built icons in lib should require react-icon-base/lib

### ISSUE THREAD

**Issue by ravinggenius** [react-icons/react-icons#61]
I am building an app on [react-typescript-boilerplate](https://github.com/StrikeForceZero/react-typescript-boilerplate), which is a fork of [react-boilerplate](https://github.com/mxstbr/react-boilerplate). (I haven't changed the webpack configuration at all except to try to get this working.)

I'm having trouble getting `import FaBeer from 'react-icons/fa/beer';` to work, so I tried using the pre-compiled icons: `var FaBeer = require('react-icons/lib/fa/beer');`. However the pre-built icons have `var IconBase = require('react-icon-base');` on line 18, which does not pull in the pre-built version of react-icon-base. Shouldn't that line be changed to `var IconBase = require('react-icon-base/lib');`? Otherwise what's the point of providing pre-built icons?

---

I truly don't mean to come across as demanding or stupid. I've spent all morning trying to get this library and others working, but nothing has worked yet, and I'm exhausting my understanding of web development. I just want some icons for my app. Thank you for your patience.

**Comment by yi** [comment]
I met the exact same problem. spent hours update babel and modifying webpack config. no help. 
I wonder why use `require` keywords rather then the standard `import`.

**Comment by ravinggenius** [comment]
That's what I was trying, and I still get the error.

My issue is that the *pre-built* code inside `./lib` is requiring `'react-icon-base'`, but it should be requiring `'react-icon-base/lib'` instead. See https://gist.github.com/ravinggenius/6fd6776ed174c83a4d26912d2507fe42#file-500px-js-L20.

A possible work-around is configuring WebPack to build `./node_modules`, but that negates pre-building the icons in the first place and is slow.

**Comment by bentatum** [comment]
Interesting, I see what you're saying. Thanks for pointing this out. I'm going to look into changing this.

**Comment by kamijin-fanta** [comment]
Currently no longer use react-icons-base.
thx.
