### ISSUE TITLE
Tabler Icons directory missing

### ISSUE THREAD

**Issue by asifkabani** [react-icons/react-icons#610]
**Describe the bug**
When importing an icon from the Tabler Icons library, it is not found. Seems that library folder does not exist.
`Module not found: Can't resolve 'react-icons/tb' in ...`

**Expected behavior**
Should import the icon needed from the `/tb` directory

**Additional context**
[Tabler Icons](https://react-icons.github.io/react-icons/icons?name=tb)
The page exists but the icons directory does not.

**Comment by wakywayne** [comment]
I am also having this problem when importing from react icons

**Comment by wakywayne** [comment]
I think I might stop using react-icons altogether and instead go to the respected icon library and just install it from their library

**Comment by mococa** [comment]
This is true, please, can someone fix this?

**Comment by sturgeonphillip** [comment]
i'm also having this issue.

**Comment by stijnvanderlaan** [comment]
Same problem

**Comment by mococa** [comment]
It's fixed by updating the version. me, for example, I'm now using version `"react-icons": "^4.7.1"`

**Comment by stijnvanderlaan** [comment]
I'm using `@react-icons/all-files` to include the package directly, and that one, does not include tabler. I was linked here from there, didn't realise this is the github for `normal` react-icons.
