### ISSUE TITLE
HiOutlinePhoto is present on website but not present in package

### ISSUE THREAD

**Issue by bhavesh-chaudhari** [react-icons/react-icons#618]
**Describe the bug**

The icon shown below is not present inside the package but it is shown there on the website.
![image](https://user-images.githubusercontent.com/74975876/194750496-52f755bb-e640-4fc4-b8c4-bc5804b3b5d5.png)
|---|

[icon search link](https://react-icons.github.io/react-icons/search?q=hioutlinephoto)
|---|

After trying to import it as -

`import {HiOutlinePhoto} from "react-icons/hi"`

I get the error saying -

`'"react-icons/hi"' has no exported member named 'HiOutlinePhoto'. Did you mean 'HiOutlinePhone'?`

**Expected behavior**

HiOutlinePhoto gets imported.

**Desktop:**
 - Device: Acer Aspire 7
 - OS: Windows 10
 - Version: ^4.4.0

**Comment by kamijin-fanta** [comment]
@bhavesh-chaudhari Could you try upgrading to 4.6.0?

**Comment by bhavesh-chaudhari** [comment]
> @bhavesh-chaudhari Could you try upgrading to 4.6.0?

Hi! I tried upgrading to 4.6.0 but I am still getting the same error. A visually similar icon named HiOutlinePhotograph is available both on website as well as in the package so I am using it for now. Though, HiOutlinePhoto is not present in the package but is on the website.

**Comment by bacali95** [comment]
Hello @bhavesh-chaudhari, that icons was add with `Heroicons 2` so you will find it under `react-icons/hi2`.

**Comment by bacali95** [comment]
I made this PR https://github.com/react-icons/react-icons/pull/629 to solve this confusion in the search page, @kamijin-fanta can you please take a look?
