### ISSUE TITLE
When using CiCircleRemove of react-icons/ci, I get the error message React does not recognize the 'dataName' prop on a DOM element.

### ISSUE THREAD

**Issue by DoK6n** [react-icons/react-icons#637]
**Describe the bug**

When using `CiCircleRemove` of `react-icons/ci`,
I get the error message `React does not recognize the 'dataName' prop on a DOM element.`

When using CiCircleRemove in react-icons, GenIcon function creates an element
I have the code `attr: { id: 'Circle_Remove', dataName: 'Circle Remove' },`,
In the actual DOM, it is created like this:
```html
<g id="Circle_Remove" dataName="Circle Remove">...</g>
```

This results in the following error output:  

<img width="872" alt="image" src="https://user-images.githubusercontent.com/39258608/198029122-a24372c7-4502-4e0e-93e9-e24ef5857483.png">

It looks like it should be created with data-name, right? 
ex) `<g id="Circle_Remove" data-name="Circle Remove">...</g>`

SVGProps<SVGElement> Type does not have dataName.  

<img width="718" alt="image" src="https://user-images.githubusercontent.com/39258608/198029241-aad9be84-f344-499c-bec0-1c3e94a49383.png">

**Desktop (please complete the following information):**

- React-ts (Vite)
- OS: macOS
- Browser chrome

**Additional context**

**Comment by xuandai-py** [comment]
Same with Ci

**Comment by nlynzaad** [comment]
same with FaInstalod. it seems just setting it to lowercase it might solve the issue? [data-* attributes should be lowercase](https://github.com/jhamlet/svg-react-loader/pull/54)

**Comment by nisalrenuja** [comment]
same here 😥 hope will fix soon

**Comment by j33n** [comment]
Facing the same issue using remix.run

`Warning: React does not recognize the `dataName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

**Comment by laravieira** [comment]
Same with CiMobile2.
