### ISSUE TITLE
importing icons starting with Hi breaks the project

### ISSUE THREAD

**Issue by K2adir** [react-icons/react-icons#638]
**Describe the bug**

these imports work without a single problem. 

import { RiAwardLine } from 'react-icons/ri'
import { TbMoodHappy } from 'react-icons/tb'
import { GrProjects } from 'react-icons/gr'
import { BsBoxArrowUp } from 'react-icons/bs'

however,
any icon starting with Hi, breaks my project and shows a white screen. 
removing the import fixes the problem.

icons I have tried

HiOutlineCloudArrowUp
HiOutlineCloudArrowUp

the way I import

import { HiArrowDownTray } from 'react-icons/hi'

**Minimal sample repository**
Gist/Github URL

**Expected behavior**
import the icon like others

**Screenshots**
just white screen, nothing is visible

**Desktop (please complete the following information):**

MacBook pro 2018 Monterey 12.5

**Comment by MiroKopecky** [comment]
I have same issue, @K2adir did you find any solution ?

**Comment by K2adir** [comment]
> 

apparently, hi icons were located in a different folder. I forgot the location and I will update this issue if I could remember it
