### ISSUE TITLE
Upgrade FontAwsome Icon Pack to version 6.2.1

### ISSUE THREAD

**Issue by ayushkumarbhadani** [react-icons/react-icons#649]
I am working on a project where I need an icon from version 6.2.1 which is not available in the current version used by React-Icons.
Upgrade the font-awesome pack to version 6.2.1

**Comment by rene-demonsters** [comment]
Running into the same issue here. I switched to using `import { FaMessage } from "@react-icons/all-files/fa/FaMessage";` as I saw suggested in #216, but FaMessage still isn't available.

**Comment by abhi1693** [comment]
I have forked this awesome library due to inactivity and you can find the most up-to-date icons at https://onemind-services-llc.github.io/react-icons-ng/

**Comment by kamijin-fanta** [comment]
upgraded. current version 6.4.2.
