### ISSUE TITLE
Upgrade Heroicons 2 to the latest version

### ISSUE THREAD

**Issue by haikhalfakhreez** [react-icons/react-icons#656]
Hi, thanks for the awesome library. But could you guys upgrade Heroicons 2 version to the latest one? As of 7 December 2022, it is on v2.0.13. They added a bunch of new icons since v2.0.8 used in this library.

**Comment by tomimarkus991** [comment]
Hey, is your project not breaking when using heroicons? Or are you using just version 2? Im using version 1 and when i try to upgrade react-icons everything breaks

**Comment by haikhalfakhreez** [comment]
@tomimarkus991 Nope. Everything works fine on my side. My only issue is Heroicons 2 is not yet updated to the latest version under React Icons. There are some icons missing that I need to use. As a workaround, I can easily installed Heroicons library itself but it would be nice if React Icons keep them updated as well. 

As for your problem, I tried importing `HiHome` from `react-icons/hi` and it works fine. I'm using v4.7.1 btw.

**Comment by tomimarkus991** [comment]
> @tomimarkus991 Nope. Everything works fine on my side. My only issue is Heroicons 2 is not yet updated to the latest version under React Icons. There are some icons missing that I need to use. As a workaround, I can easily install Heroicons library itself but it would be nice if React Icons keep them updated as well. 
> 
> As for your problem, I tried importing `HiHome` from `react-icons/hi` and it works fine. I'm using v4.7.1 btw.

yes. i tried aswell and now everything works. wat the f.

**Comment by kamijin-fanta** [comment]
I released with package version [v4.8.0](https://www.npmjs.com/package/react-icons/v/4.8.0) which updated to heroicons 2.0.16 thanks.
