### ISSUE TITLE
Can't open github page

### ISSUE THREAD

**Issue by Color-Kat** [react-icons/react-icons#658]

**Comment by givensuman** [comment]
Are you using [https://react-icons.github.io/react-icons](https://react-icons.github.io/react-icons)?

It is definitely an issue that the base route leads to a 404.

**Comment by thanhtutzaw** [comment]
> Are you using https://react-icons.github.io/react-icons?
> 
> It is definitely an issue that the base route leads to a 404.

It is infinite loading

**Comment by kamijin-fanta** [comment]
already fixed.
