### ISSUE TITLE
Add SaveClose icon

### ISSUE THREAD

**Issue by bitsbuildomniverse** [react-icons/react-icons#660]
**Is your feature request related to a problem? Please describe.**
I'm implementing the feature (immediately closing after saving the content) in React app and using react-icons in my project.
But can't find a proper icon.

**Describe the solution you'd like**
I'd like to use SaveClose icon.

**Describe alternatives you've considered**
https://www.visualpharm.com/free-icons/save%20close-595b40b75ba036ed117d8ec5
It's from Icons8.

**Additional context**
We need not only Save icon, but also SaveClose icon to close the window after saving the content.

**Comment by kamijin-fanta** [comment]
sorry. Icon sets that do not adopt OSS licenses cannot be added.
