### ISSUE TITLE
After HeroIcons 2 was added, when using heroicons 1 app is not starting

### ISSUE THREAD

**Issue by tomimarkus991** [react-icons/react-icons#661]
**Describe the bug**
Brave error:
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-icons_all.js?v=826af561' does not provide an export named 'HiHome'
Firefox error:
Uncaught SyntaxError: ambiguous indirect export: HiHome

**Minimal sample repository**
I was using 4.3.1 and after upgrading to 4.7.1 Im getting error

**Expected behavior**
No error

**Screenshots**

**Desktop (please complete the following information):**

- Device: PC
- OS: WIN 10
- Browser: all
- Version 4.7.1 (or when HeroIcons2 were added)

**Additional context**
I thought this would get fixed sooner, but as it is not fixed yet im creating this issue

**Comment by kamijin-fanta** [comment]
Depending on the version of the icon set, the icon name etc. will be changed.
