### ISSUE TITLE
Missing Icons: `MdKeyboardCommandKey` and `MdOutlineKeyboardCommandKey`

### ISSUE THREAD

**Issue by pierre-lgb** [react-icons/react-icons#665]
Icon `KeyboardCommandKey` from Material Design Icons ([see here](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Akeyboard_command_key%3A)) is missing.

**Comment by present-g** [comment]
The `ContentCopy` icon is also missing

**Comment by kamijin-fanta** [comment]
exists in v4.8.0. prelease upgrade package. thanks.
