### ISSUE TITLE
Getting Component Icon by passing a string as name 

### ISSUE THREAD

**Issue by luccas-specht** [react-icons/react-icons#673]
**Describe the solution you'd like**
Just a component that expect an icon name as string prop and return directly the icon.

**Describe alternatives you've considered**

`import { Icon } from "react-icons"`;
`<Icon name='BsFacebook'/>`;

then the component **Icon** will return: 
![image](https://user-images.githubusercontent.com/40741571/211682603-072ba752-0f6c-4931-9b00-59c3f8e58476.png)

**Comment by erenkulaksiz** [comment]
I dont think this is possible the way package was built. 
<Icon name="BsFacebook"/> will break tree shaking since package not going to know which icon will be passed, and result in large file size.
