### ISSUE TITLE
Incompatible with react native navigation

### ISSUE THREAD

**Issue by LouisMuriuki** [react-icons/react-icons#679]
**Describe the bug**
I want to use this icon `HiOutlineMenuAlt1` as my drawer icon in react native navigation. However i try to use as shown below it brings an error(see below)
Note: This error happens with all icons when used in the navigation

**Minimal sample repository**
import { HiOutlineMenuAlt1} from "react-icons/hi";
 <Drawer.Navigator
      screenOptions={({ navigation }) => ({
        headerLeft: () => <HiOutlineMenuAlt1 size={24} color="white" />,
})
>
....
</Drawer.Navigator>

**ERROR SHOWN**
Invariant Violation: View config getter callback for component `path` must be a function (received `undefined`). Make sure to start component names with a capital letter.

**Expected behavior**
it should display an icon and no error should be shown

**Screenshots**

**Desktop (please complete the following information):**

- DELL E6430,HUAWEI NOVA 7
- WINDOWS,ANDROID
- CHROME

**Additional context**

**Comment by jamsch** [comment]
@LouisMuriuki This library is incompatible with React Native because it uses `<svg>` tags. Use `react-native-vector-icons` or `@expo/vector-icons` if you use Expo.

**Comment by LouisMuriuki** [comment]
Okay thanks
