### ISSUE TITLE
C++ bug in search

### ISSUE THREAD

**Issue by rajraii** [react-icons/react-icons#687]
**Describe the bug**
Whenever we search for C++, it shows an Application error: a client-side error occurred

**Expected behavior**
It should have shown the results for C++ icons

**Screenshots**
![image](https://user-images.githubusercontent.com/71391631/219950780-49b7fcd3-2d4a-472a-a0d4-629ff0ccbb52.png)

**Desktop (please complete the following information):**

- Device: PC
- OS: Windows
- Browser chrome
- Version 110.0.5481.96

**Comment by kamijin-fanta** [comment]
- dup #633
