### ISSUE TITLE
Missing "graph-up" icon of Bootstrap Icons

### ISSUE THREAD

**Issue by didaquis** [react-icons/react-icons#692]
I see in the Bootstrap Icons documentation this icon: https://icons.getbootstrap.com/icons/graph-up/

However, I see that it is not available in this repository. 

Would it be possible to update the Bootstrap Icons?

Thanks!

**Comment by kamijin-fanta** [comment]
I released with package version [v4.8.0](https://www.npmjs.com/package/react-icons/v/4.8.0) which updated to bootstrap icons 1.10.3. thanks.
