### ISSUE TITLE
[Bug]: `c++` search doesn't work

### ISSUE THREAD

**Issue by scffs** [react-icons/react-icons#695]
### Describe the bug

if you enter `symbol` ++, the page is reloaded

### Expected behavior

Search for a suitable icon

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search?q=c%2B%2B

### Steps To Reproduce

1. In the input enter any `symbol` ++
`c++` for example

### Package version

v4.8.0

### Relevant log output

```Shell
SyntaxError: nothing to repeat
    NextJS 57
framework-a42f82fbe29cccf0.js:1:71883
```

```
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

```
SyntaxError: nothing to repeat
    NextJS 57
main-dc668c95f3dc2753.js:1:16155
```

![изображение](https://user-images.githubusercontent.com/67464545/222892622-674a518b-ea73-4472-8f9a-99e30fc977ba.png)

**Comment by kamijin-fanta** [comment]
duplicate #633
