### ISSUE TITLE
[Feature]:  Add SolarIcons Set

### ISSUE THREAD

**Issue by n0vit** [react-icons/react-icons#700]
### Describe

Add New Icon Set

### Solution

Hi! Add Please Solar Icons it's a open source project  https://solariconset.com

**Comment by Hamjaster** [comment]
Solar Icons is only available on figma templates 👎

**Comment by themudrec** [comment]
Are there any updates? Solar Icons has a github repository: https://github.com/480-Design/Solar-Icon-Set

**Comment by AlixRoyere** [comment]
Why is it marked as completed? It is not completed
