### ISSUE TITLE
[Feature]: modularizeImport in Nextjs

### ISSUE THREAD

**Issue by mpotane** [react-icons/react-icons#705]
### Describe

The library import a lot of icons which aren't supposed to. Takes time in build time.

### Solution

Add default conversion -> import AiThisIcon from react/ai

**Comment by Stevemoretz** [comment]
> My Bad only some icons have issue with Nextjs compiler for example react-icons/ai. Will be closing this for now

That's not a good reason to close it, even one bug is one bug.

**Comment by guhur** [comment]
I can confirm it is happening for TbPigBank. Replacing it with FaPiggyBank saves me 10 sec!
