### ISSUE TITLE
Cross Icon-Set Search

### ISSUE THREAD

**Issue by brillout** [react-icons/react-icons#71]
https://github.com/gorangajic/react-icons/issues/42 mentions 

> I'd like give the docs an update. Looks like it's missing at least one icon set and I'd like to make it searchable.

Not sure what the plan is but it would be really nice to be able to Ctrl+F over all icon sets.

Right now, I end up opening every icon set in a new browser tab and Ctrl+F in each of them.

**Comment by bentatum** [comment]
I just published the initial pass at this last night.

http://react-icons.benjamintatum.com

Let me know what you think of the search feature and if you have any additional ideas.

**Comment by brillout** [comment]
Wow nice!

And if you add a "All Icons" selection then it would be perfect for me.

Thanks so much!

**Comment by bentatum** [comment]
Good idea! I'll add that to the list.

**Comment by brillout** [comment]
just used your new interface to find `react-icons/lib/io/ios-world-outline`, thanks! Wouldn't have find it otherwise.

**Comment by brillout** [comment]
(using it again :))

**Comment by brillout** [comment]
and again.. any reason why it's not on http://gorangajic.github.io/react-icons/?

**Comment by kjanoudi** [comment]
Just used http://react-icons.benjamintatum.com/all this is so cool!!

**Comment by kamijin-fanta** [comment]
With the new site, this has been improved.
