### ISSUE TITLE
ant design Icon

### ISSUE THREAD

**Issue by IbrahimIjai** [react-icons/react-icons#716]
### Describe the bug

import { iconName} from "react-icons/ai"; it is buggy, it seems it was renamed to "react-icons/Ai", but not updated in the documentation. Please fix the docs, or fix the file name.

### Expected behavior

Had to use "Ai" instead of "ai"

### Minimal sample repository URL

just in my production

### Steps To Reproduce

1. Import any ant design Icon, and try to render it on your webpage.

### Package version

"4.8.0",

**Comment by kamijin-fanta** [comment]
There is no fact that the module name has been changed to `react-icons/ai` `react-icons/Ai` in react-icons@4.8.0.

https://unpkg.com/browse/react-icons@4.8.0/
