### ISSUE TITLE
[Bug]: Cannot change the color of the Grommet-Icons icon.

### ISSUE THREAD

**Issue by Joshuajee** [react-icons/react-icons#722]
### Describe the bug

Color props doesn't change the colors in GR icons
![image](https://user-images.githubusercontent.com/36106199/233630742-37bf07be-371b-4da7-94ec-63ba8bc55bc5.png)
 

### Expected behavior

The color of the GR icons should be white as the other icons

![image](https://user-images.githubusercontent.com/36106199/233631013-bfcc360e-3125-4f4c-8762-ef875ee742ed.png)

### Minimal sample repository URL

https://replit.com/@Joshuajee/React-Icon-bug

### Steps To Reproduce

1 In a nodejs environment in ubuntu 22.04
2 Create a Nextjs application with typescript and tailwindcss
3 Navigate to `src/index.tsx`, delete the codes there and replace with the snippet below

```tsx
import { GrTemplate, GrAction } from "react-icons/gr"

export default function Home() {

  return (<main>
    <GrTemplate size={"28"} color="#FFFFFF" /> 
    <GrAction size={"28"} color="white" /> 
  </main>)

}

```

### Package version

v.4.8.0

**Comment by goraprial** [comment]
I have the same issue

**Comment by kamijin-fanta** [comment]
see #334
