### ISSUE TITLE
[Feature]: Polygon Icon

### ISSUE THREAD

**Issue by AmanADissingar** [react-icons/react-icons#725]
### Describe

Hi ! First of all, thanks for what you have created it helps me a lot ! I am a rookie in  developement and i appreciate your work !

I got something to figure it out ! I am looking for Polygon matic icon but impossible to find it out . Can you please make one for the react-icon librairi ?

Thanks in advance; 
You have my support !

### Solution

Make a beautiful one like 'FaEthereum'

**Comment by RahulBisht001** [comment]
This issue Required to build a cryptocurrency icon. I can build it. Please assign it to me.

**Comment by kamijin-fanta** [comment]
The icon set must be provided as SVG files on GitHub, etc.
