### ISSUE TITLE
[Feature]: Update BoxIcons, please

### ISSUE THREAD

**Issue by piscopancer** [react-icons/react-icons#726]
### Describe

![image](https://user-images.githubusercontent.com/109352196/235887915-70981742-ec72-44b1-9ba3-f671ca8ab627.png)

the current box icons number in your package is about **700**, however they have been updated and now the total is about **1.600**.
Update please, their icons are superb quality! 🙏

### Solution

update (one way or another)

**Comment by JoelNichols** [comment]
Agreed - also as an aside Boxicons is now licensed under the MIT license. The React-icons documentation still shows it as being licensed under CC-BY-4.0 which is a less permissive license and is no longer correct.

**Comment by kamijin-fanta** [comment]
upgraded. current version 2.1.4.
