### ISSUE TITLE
[Bug]:  Two output files share the same path but have different contents: 

### ISSUE THREAD

**Issue by Albertyhu** [react-icons/react-icons#729]
### Describe the bug

I am building a React JS application using Vite and the react-icons library, and the console would return the following error: 

 Two output files share the same path but have different contents: node_modules\.vite\deps_temp_0bfc751c\react-icons_Ai.js

The app would crash on build. 

I believe that the issue occurs when using icons from the Ai library. 

### Expected behavior

The app should be able to display the imported react-icons correctly without crashing. 

### Minimal sample repository URL

https://github.com/Albertyhu/BlogClient/blob/main/component/header/menuLinks.jsx

### Steps To Reproduce

1. npm install 'react-icons' 
2. import an icon from the Ai library onto the page and use it. 

### Package version

"^4.8.0",

### Relevant log output

```Shell
X [ERROR] Two output files share the same path but have different contents: node_modules\.vite\deps_temp_0bfc751c\react-icons_Ai.js

D:\NodeJS projects\BlogClientSite\node_modules\esbuild\lib\main.js:1636
  let error = new Error(`${text}${summary}`);

Error: Build failed with 1 error:
error: Two output files share the same path but have different contents: node_modules\.vite\deps_temp_0bfc751c\react-icons_Ai.js
    at failureErrorWithLog (D:\NodeJS projects\BlogClientSite\node_modules\esbuild\lib\main.js:1636:15)
    at D:\NodeJS projects\BlogClientSite\node_modules\esbuild\lib\main.js:1048:25
    at D:\NodeJS projects\BlogClientSite\node_modules\esbuild\lib\main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: null,
      notes: [],
      pluginName: '',
      text: 'Two output files share the same path but have different contents: node_modules\\.vite\\deps_temp_0bfc751c\\react-icons_Ai.js'
    }
  ],
  warnings: []
}
```

**Comment by Albertyhu** [comment]
I decided to remove the react-icons library and the issue disappeared.

**Comment by obere4u** [comment]
Did the icons show when you remove the react-icons library?

**Comment by zainwaseem** [comment]
> Did the icons show when you remove the react-icons library?

yes icon shows
