### ISSUE TITLE
[Feature]: Update Remix Icon version 3.2.0

### ISSUE THREAD

**Issue by hgutierrez** [react-icons/react-icons#730]
### Describe

Remix Icon updated their repository in the past few months, they added over 200 new icons. It would be awesome to update this.

### Solution

Update Remix Icon import at least up to v3.2.0, commit hash 6ec52417fd8736d6dd08cee84b1a03cb810bc903 

Currently, react-icons is pointing to v2.5.0, commit hash df9e5255ff6a3caf42fb79e27facc80af3d20545
https://github.com/react-icons/react-icons/blob/fcc5b205243b5dc8896b5f5caa464a1f77176bcb/packages/react-icons/src/icons/index.ts#L365

### Additional context

https://github.com/Remix-Design/RemixIcon/releases/tag/v3.2.0

**Comment by scottsun94** [comment]
+1

**Comment by abhi1693** [comment]
I have forked this awesome library due to inactivity and you can find the most up-to-date icons at https://onemind-services-llc.github.io/react-icons-ng/

**Comment by kamijin-fanta** [comment]
upgraded. current version is 3.5.0.
