### ISSUE TITLE
FillUpvote and FillDownvote icons

### ISSUE THREAD

**Issue by gurbaaz27** [react-icons/react-icons#732]
### Describe

I am using react-icons in a professional NextJS project, and one thing that is bugging me a lot is the lack of Solid fill upvote and downvote icons. The only ones I can use from the react-icons collection are BiUpvote and BiDownvote, which are just outline icons.

### Solution

I would appreciate if anyone could guide me on how to convert these outline icons to fill ones, or if someone is able to add these 2 icons (or guide me how to do it) I would be the most grateful.

**Comment by kamijin-fanta** [comment]
Included in BoxIcons.
