### ISSUE TITLE
[Feature]: Pass React Icon as props to Client Component in NextJS

### ISSUE THREAD

**Issue by huyphamfc** [react-icons/react-icons#733]
### Describe

I build a dynamic button:
```ts
'use client';

import type { IconType } from 'react-icons';

interface ButtonProps {
  children: React.ReactNode;
  Icon: IconType;
}

export default function Button(props: ButtonProps) {
  const { children,  Icon } = props;

  return (
    <button>
      <Icon />
      {children}
    </button>
  );
}
```

I got a problem when passing React Icon:
`
Error: Functions cannot be passed directly to Client Components unless you explicitly expose it by marking it with "use server".
  <... Icon={function} children=...>
`

### Solution

I have no idea to resolve this :((

**Comment by AdamQuadmon** [comment]
I'm not an expert, still learning but try to pass the `<Icon />` in the children, so the client component does not need to know about the content of its children

**Comment by wcosmas** [comment]
I'm having a similar issue

**Comment by ethmore** [comment]
As the error specifies you can not pass functions from 'server components' to 'client components'. This is Next related and not about react-icons. To solve the problem whether you need to remove 'use client' from your 'Button' component or add 'use client' to the file where you import the 'Button' component.

**Comment by kamijin-fanta** [comment]
This seems to be a question about how to use Next.js.

**Comment by ChirayuBatra99** [comment]
instead of 
       <Icon/>
use
      {Icon && <Icon />}

And thank me
