### ISSUE TITLE
[Feature]: Mastodon Icon

### ISSUE THREAD

**Issue by bhouston** [react-icons/react-icons#737]
### Describe

You have most social networks (FB, Twitter, Medium, etc), but no Mastodon icons:

Here is their official branding kit: https://joinmastodon.org/branding

Other similar libraries have Mastodon icons in them:

* FontAwesome: https://fontawesome.com/v5/icons/mastodon?f=brands&s=solid
* Bootstrap: https://icons.getbootstrap.com/icons/mastodon/

### Solution

Add a Mastodon icon.

**Comment by abhi1693** [comment]
You can find these in the new package: https://onemind-services-llc.github.io/react-icons-ng/search?q=mastodon

**Comment by bhouston** [comment]
I was wrong. the icon is there because it is part of Bootstrap:

```js
import {
  BsFacebook,
  BsGithub,
  BsLinkedin,
  BsMastodon,
  BsRss,
  BsTwitter
} from 'react-icons/bs';
```
