### ISSUE TITLE
[Bug]: IoClose doesn't exist

### ISSUE THREAD

**Issue by Nicitaa** [react-icons/react-icons#741]
### Describe the bug

IoClose doesn't exist
![image](https://github.com/react-icons/react-icons/assets/39565703/d1fe3825-b10d-4874-a88d-6224996d7b9f)

### Expected behavior

...

### Minimal sample repository URL

https://github.com

### Steps To Reproduce

1.Try to add IoClose
![image](https://github.com/react-icons/react-icons/assets/39565703/720333dc-1969-4e2d-b8fa-125027ebcab8)
2.Get this error

### Package version

4.9.0

**Comment by kamijin-fanta** [comment]
You need to import `import { IoClose } from "react-icons/io5";`. `io5` instead of `io`.

**Comment by Nicitaa** [comment]
> You need to import `import { IoClose } from "react-icons/io5";`. `io5` instead of `io`.

I want sujjest improve this (add something that let me understand what import I should do)
