### ISSUE TITLE
[Feature]: Add support for The Podcast Font collection

### ISSUE THREAD

**Issue by theDanielJLewis** [react-icons/react-icons#743]
### Describe

https://podcastfont.com/ hosts a variety of podcasting-specific icons that no other icon collection has. For example, Podchaser, Love the Podcast, and more.

I would love to see these icons supported by React Icons, making it easier for podcasting developers to include these icons in their React apps.

### Solution

Include all icons from https://podcastfont.com/

**Comment by kamijin-fanta** [comment]
SVG files must be provided by GitHub or other sources.

**Comment by theDanielJLewis** [comment]
What do you mean? The SVGs are there on the site.
