### ISSUE TITLE
'BiLogoJavascript' not found in 'react-icons/bi'

### ISSUE THREAD

**Issue by ue-an** [react-icons/react-icons#748]
I am having this error of:
`export 'BiLogoJavascript' (imported as 'BiLogoJavascript') was not found in 'react-icons/bi'`

My code:
`import {BiLogoJavascript} from 'react-icons/bi';`
and
`<BiLogoJavascript size={25} />`

Wherein, I searched https://react-icons.github.io/react-icons/search?q=jav, the logo is there but I cannot use it in my project. Also, I cannot seem to find the 'bi' or 'ai' in the website I mentioned to refer hopefully to what other (or all) icons they offer.

**Comment by MoltenFuzzy** [comment]
Getting a similar error with box icons
```import { BiSolidCommentAdd } from "react-icons/bi";```
Updated package to see if that was the fix, but still cannot find that icon either.

**Comment by DanielRendon1020** [comment]
It seems like all logos are missing

**Comment by ue-an** [comment]
Thank you for all the responses. It seems like they haven't updated the website. I am thinking of closing this now or wait until someone from them to notice this and respond.

**Comment by gitChaoslord** [comment]
The Solid and Logo BoxIcons were merged recently and are shown on the website currently but were not included in release `v4.9.0` as you can see here https://github.com/react-icons/react-icons/compare/v4.9.0...master 

Let's wait for next release

**Comment by kamijin-fanta** [comment]
I have published a package with an upgraded version of the icon set. Please use the new version. https://www.npmjs.com/package/react-icons/v/4.10.1

**Comment by ue-an** [comment]
> I have published a package with an upgraded version of the icon set. Please use the new version. https://www.npmjs.com/package/react-icons/v/4.10.1

Thank you!
