### ISSUE TITLE
[Bug]: Missing font-awesome icon (FaCartShopping)

### ISSUE THREAD

**Issue by Asqit** [react-icons/react-icons#751]
### Describe the bug

I can't find an icon in the auto-generated `node_modules/react-icons/fa/index.d.ts`. On the official website, there is mentioned `FaCartShopping` icon, but I can't find it / import it.

### Expected behavior

I expected to import `FaCartShopping` icon via `import { FaCartShopping } from 'react-icons/fa'`

### Minimal sample repository URL

null

### Steps To Reproduce

1. Create a new react-typescript application with vite: `yarn create vite sample-project`
2. install vite dependecies: `yarn`
3. install react-icons package: `yarn add -D react-icons`
4. try importing the `FaCartShopping` as name export from `react-icons/fa`

### Package version

4.9.0

### Additional context

![Snímek obrazovky z 2023-06-15 12-41-14](https://github.com/react-icons/react-icons/assets/70013396/bc4af25f-bac8-4006-90f6-265c1a7b4ddf)

**Comment by kamijin-fanta** [comment]
I have published a package with an upgraded version of the icon set. Please use the new version. https://www.npmjs.com/package/react-icons/v/4.10.1
