### ISSUE TITLE
[Feature]: Update remix icons

### ISSUE THREAD

**Issue by zeitvertrieb** [react-icons/react-icons#752]
### Describe

Remix icons package seems to have new icons (eg. expand-right, expand-left ...)
would be great to have them available with react-icons too.
thanks for your great work!

### Solution

update remix icons package

**Comment by jszsj** [comment]
I need the new icons too, like tiktok icons added in Remix icons v3.0.0, update please! Thanks a lot!

**Comment by kamijin-fanta** [comment]
I have published a package with an upgraded version of the icon set. Please use the new version. https://www.npmjs.com/package/react-icons/v/4.10.1
