### ISSUE TITLE
[Bug]: Passing Icon as prop gives Error: <svg> attribute height: Expected length, "auto".

### ISSUE THREAD

**Issue by AdamQuadmon** [react-icons/react-icons#753]
### Describe the bug

I'm in NextJs using the App Router, in my NavBar Server Component I have:
```jsx
import { MdLogin } from 'react-icons/md';

const Path = ({Icon, children}) => {
  return (
    <>
      {/* this gives the svg errors */}
      <Icon size="auto" color="white" />
      {/* this gives no errors */}
      {children}
    </>
   )
}

const Navbar = () => {
  return (
    <Paths>
        <Path Icon={ MdLogin }>
          <MdLogin size="auto" color="white" />
        </Path>
    </Paths>
  )
```

using the `MdLogin` icon as children gives no error but if I pass the Icon as a `prop` it will work but I can see in the console this error: `Error: <svg> attribute height: Expected length, "auto".`

The icons are displayed correctly in both cases but the console error smells like something wrong with my implementation or the import.

### Expected behavior

no warnings in the console passing the Icon as a prop to another Controller

### Minimal sample repository URL

not available

### Steps To Reproduce

configure it for Next

pass an Icon as prop in a component

### Package version

4.9.0

**Comment by kamijin-fanta** [comment]
No minimum repository is provided. Also, it does not appear to be a bug.
