### ISSUE TITLE
[Bug]: The Solid Variants in BoxIcons are not working

### ISSUE THREAD

**Issue by henacodes** [react-icons/react-icons#757]
### Describe the bug

the solid variants of the Box Icon library are not exported.
for example 

import { BiUpvote, BigSolidUpvote } from "react-icons/bi";
<BiUpvote /> works. but
<BigSolidUpvote /> won't work.

### Expected behavior

I expected to see solid icons to be shown

### Minimal sample repository URL

https://github.com/henacodes/site-galley/blob/master/src/components/FeaturedSite.jsx

### Steps To Reproduce

try  to import and use any icon that starts with "BiSolid..."

### Package version

V4.9.0

### Relevant log output

```Shell
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/react-icons_bi.js?v=7173a763' does not provide an export named 'BiSolidUpvote'
```

**Comment by satarovbekzhan** [comment]
Also wondering why there are no solid variants

**Comment by gitChaoslord** [comment]
The Solid and Logo BoxIcons have been merged recently and are shown on the website but are not included in release `v4.9.0`

see https://github.com/react-icons/react-icons/compare/v4.9.0...master

**Comment by henacodes** [comment]
So when will they be included ?

**Comment by henacodes** [comment]
> The Solid and Logo BoxIcons have been merged recently and are shown on the website but are not included in release `v4.9.0`
> 
> see [v4.9.0...master](https://github.com/react-icons/react-icons/compare/v4.9.0...master)

So when will they be included sir?

**Comment by satarovbekzhan** [comment]
> The Solid and Logo BoxIcons have been merged recently and are shown on the website but are not included in release `v4.9.0`
> 
> see [v4.9.0...master](https://github.com/react-icons/react-icons/compare/v4.9.0...master)

When will it be included and in which version?

**Comment by gitChaoslord** [comment]
> When will it be included and in which version?

I do not know as i am not a project maintainer, we will have to patient

**Comment by kamijin-fanta** [comment]
I have published a package with an upgraded version of the icon set. Please use the new version. https://www.npmjs.com/package/react-icons/v/4.10.1

**Comment by henacodes** [comment]
> I have published a package with an upgraded version of the icon set. Please use the new version. https://www.npmjs.com/package/react-icons/v/4.10.1

Gracias
