### ISSUE TITLE
[Bug]: Documentation and Package not in sync !

### ISSUE THREAD

**Issue by Rahuletto** [react-icons/react-icons#760]
### Describe the bug

As seen in below image,
![image](https://github.com/react-icons/react-icons/assets/71836991/16eb83ca-36eb-40a8-b3a4-f76cf18ae1d8)

https://react-icons.github.io/react-icons/search?q=GoShield

We have GoShield, Check, Lock etc.. But if we see it in the npm package (react-icons/go/index.js) we have
```js
// ...
module.exports.GoSettings 
module.exports.GoShield = function GoShield (props) {
  return GenIcon({"tag":"svg","attr":{"viewBox":"0 0 14 16"},"child":[{"tag":"path","attr":{"fillRule":"evenodd","d":"M7 0L0 2v6.02C0 12.69 5.31 16 7 16c1.69 0 7-3.31 7-7.98V2L7 0zM5 11l1.14-2.8a.568.568 0 0 0-.25-.59C5.33 7.25 5 6.66 5 6c0-1.09.89-2 1.98-2C8.06 4 9 4.91 9 6c0 .66-.33 1.25-.89 1.61-.19.13-.3.36-.25.59L9 11H5z"}}]})(props);
};
module.exports.GoSignIn 
// ...
```

There is no Check, Lock and so on.

And it seems like the documentation suggest that GoShield gives an outline styled icon. but this is the result:
![image](https://github.com/react-icons/react-icons/assets/71836991/3214a0ae-2b13-406e-b4ab-5d0210b64b2c)

### Expected behavior

It should contain the icons and the expected icons shown in the documentation. But rather it shows an outdated one.

### Minimal sample repository URL

NONE

### Steps To Reproduce

1. Use the icon in your React page
2. For example, Lets use `GoShieldCheck`. We receive a Runtime Error

### Package version

v4.9.0

### Relevant log output

```Shell
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Home`.
```

This issue is experienced by many people (look into issues tab) like #440

**Comment by Rahuletto** [comment]
Also all icons are very outdated. For example, 


Github Octicons icons | MIT | 8.5.0 | 184
-- | -- | -- | --

But they are in [v19.13.0](https://github.com/primer/octicons)

**Comment by kamijin-fanta** [comment]
I have published a package with an upgraded version of the icon set. Please use the new version. https://www.npmjs.com/package/react-icons/v/4.10.1

**Comment by Rahuletto** [comment]
Thank you
