### ISSUE TITLE
[Bug]: Missing some icons that are listed on site

### ISSUE THREAD

**Issue by IDrumsey** [react-icons/react-icons#762]
### Describe the bug

There are some icons that are listed on the project's website, but the aren't found when trying to import them. I just know of two, but there may be more. The ones I know about are FaCodePullRequest (https://react-icons.github.io/react-icons/search?q=facodepull) and FaGears. Maybe this is a known issue already, idk.

### Expected behavior

Be able to import an icon listed on the site.

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search?q=facodepull

### Steps To Reproduce

1. install the package
2. try to import FaCodePullRequest -> `import { FaCodePullRequest} from "react-icons/fa"`

### Package version

4.10.1

**Comment by GinoMoena** [comment]
i have the same problem, i need those icons for configuration views

**Comment by mikib0** [comment]
Did you try updating react-icons `npm update react-icons`?

**Comment by IDrumsey** [comment]
@mikib0 Yeah, I'm on the latest version, 4.10.1. Still not found.

**Comment by sajithkahawatta** [comment]
I also faced the same issue. After examining the node_modules folder I figured that we need to import from `react-icons/fa6`.

`import { FaCodePullRequest } from 'react-icons/fa6'`

**Comment by GLorenz90** [comment]
Having issues with react-icons/io as well namely IoCalendarSharp and IoFileTrayFull. I haven't been keeping a list but this has been a constant problem with just about 25% of the icons I'm trying to use. Getting really aggravating...

**Comment by lutz404** [comment]
The same problem here! Many missing icons, making the experience bad. I prefer to have fewer options, but all functional.

**Comment by kamijin-fanta** [comment]
please try `import { FaCodePullRequest } from 'react-icons/fa6'`.

**Comment by lylest** [comment]
> Did you try updating react-icons `npm update react-icons`?

only fix few icons but not all

**Comment by lylest** [comment]
HiChatBubbleBottomCenterText not working

**Comment by IgorGryp** [comment]
RiCloseLargeLine doesn't work
