### ISSUE TITLE
Website SSL error

### ISSUE THREAD

**Issue by aviemet** [react-icons/react-icons#763]
I haven't seen it discussed anywhere yet, and didn't know how else to let someone know or get updates. The website for viewing and searching icons in this package is returning SSL errors. 

https://react-icons.github.io/

I wanted to make sure someone on the dev team was aware, and hopefully get an update as to when it would be available again.

Thank you

**Comment by samsam9395** [comment]
Same here. Wasn't able to access the page and search for icons due to this issue when using company internet :(

**Comment by cfrerebeau** [comment]
same here

**Comment by ymuichiro** [comment]
You can browse on localhost by following these steps.
https://github.com/react-icons/react-icons#preview

1. download source-code

`Source code (zip)`
https://github.com/react-icons/react-icons/releases

2. build & start
```
cd ${your-folder-path}
git init
git add . && git commit -m "sample"
yarn
cd packages/react-icons
yarn fetch
yarn build
cd ../preview
yarn start
```

**Comment by kamijin-fanta** [comment]
TLS certificates are managed by GitHub.
