### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by monster-anshu** [react-icons/react-icons#765]
### Describe the bug

While using GrLocation I passing the color prop but it not applied.

### Expected behavior

if color is pass icon should change the color.

### Minimal sample repository URL

NA

### Steps To Reproduce

1. Import GrLocation
```
import { GrLocation } from "react-icons/gr"
```
2. Render Icon in a Page or Component
```
<GrLocation color="white" className="text-white" />
```

### Package version

4.8.0

**Comment by kamijin-fanta** [comment]
#722
