### ISSUE TITLE
[Bug]: There are two FaEyes

### ISSUE THREAD

**Issue by swapn652** [react-icons/react-icons#766]
### Describe the bug

On searching FaEye on the site, two of them show up.

### Expected behavior

Only one should show up.

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search?q=FaEye

### Steps To Reproduce

Click on the link I provided above

### Package version

v4.10.1

### Additional context

<img width="872" alt="Screenshot 2023-06-29 at 7 46 20 PM" src="https://github.com/react-icons/react-icons/assets/70851202/c8bc8d95-f9a5-4f57-8e3c-1a4dab4885f6">

**Comment by maanil17** [comment]
can you assign it to me? I would like to work on this issue

**Comment by maanil17** [comment]
Hey! Can you assign me this?

**Comment by kamijin-fanta** [comment]
dupulicate #794
