### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Nicitaa** [react-icons/react-icons#767]
### Describe the bug

PiNumberSquareSevenLight doesn't work

### Expected behavior

PiNumberSquareSevenLight

### Minimal sample repository URL

https://github.com

### Steps To Reproduce

1.import this 
import { PiNumberSquareSevenLight } from 'react-icons/pi'
2.use this icon
 <PiNumberSquareSevenLight />
3.get this error
![image](https://github.com/react-icons/react-icons/assets/39565703/c30277d6-d359-423d-bfc3-f7c2ae70edeb)

### Package version

05.07.2023

**Comment by sinahnyazdi** [comment]
Had the same problem, what's wrong with pi icons?

**Comment by sinahnyazdi** [comment]
Installing below package solved the problem.
npm i @phosphor-icons/core

**Comment by Nicitaa** [comment]
> Installing below package solved the problem. npm i @phosphor-icons/core

Not for me
![image](https://github.com/react-icons/react-icons/assets/39565703/de90b742-6129-4508-af25-b38b2efb132e)
![image](https://github.com/react-icons/react-icons/assets/39565703/0c99e25c-de53-4d15-aa33-f52b4fe00fb8)

**Comment by sinahnyazdi** [comment]
Update your react-icons to latest version: ^4.10.1

**Comment by Nicitaa** [comment]
> Update your react-icons to latest version: ^4.10.1
Thank you
After updating it works without this - npm i @phosphor-icons/core
