### ISSUE TITLE
[Bug]: Icon `FaXmark` is missing

### ISSUE THREAD

**Issue by simon-abbott** [react-icons/react-icons#768]
### Describe the bug

The website shows the icon `FaXmark` in the search results, but when I try to import it into my code it doesn't work.

### Expected behavior

The `FaXmark` icon should be usable.

### Minimal sample repository URL

N/A

### Steps To Reproduce

1. Search the website for `FaXmark`
2. You will see an icon
3. Add `import { FaXing } from 'react-icons/fa';` to your code

### Package version

4.10.1

**Comment by simon-abbott** [comment]
Turns out `HiXMark` and `HiMiniXMark` are missing as well. Something is afoot here. 🤔

**Comment by kamijin-fanta** [comment]
use `'react-icons/fa6'`
