### ISSUE TITLE
[Bug]: Website Font Awesome icon typo

### ISSUE THREAD

**Issue by Kykal** [react-icons/react-icons#769]
### Describe the bug

On the website, there are two icons whose names are misspelled:
- [FaCircleUser](https://react-icons.github.io/react-icons/search?q=facircleuser)
- [FaRegCircleUser](https://react-icons.github.io/react-icons/search?q=faregcircleuser)

User and Circle words in both are just swapped.

![imagen](https://github.com/react-icons/react-icons/assets/54295964/6c0e5519-db60-4023-b180-27ca5e8ea99b)
![imagen](https://github.com/react-icons/react-icons/assets/54295964/7731fbd6-95f0-426b-ac2f-502da69b19c3)

### Expected behavior

When importing those icons, its real imported names are:

- FaUserCircle
- FaRegUserCircle

### Minimal sample repository URL

https://codesandbox.io/p/sandbox/great-fog-xg3xvg

### Steps To Reproduce

1. Install package and import `FaCircleUser` and `FaRegCircleUser` from `/fa`.
2. Not found
3. Change its names to `FaUserCircle` and `FaRegUserCircle`, respectively.
4. Will do.

### Package version

v4.10.1

### Additional context

Looks like if you search for both icons (the misspelled and the right one, both will appear and looks like the same.

✅ Right one
![imagen](https://github.com/react-icons/react-icons/assets/54295964/b9d8e59b-343d-4019-abad-d61bf4410363)

❌ Misspelled
![imagen](https://github.com/react-icons/react-icons/assets/54295964/8dc1f814-f018-47a9-8f6e-f2bd8ff1a042)

**Comment by kamijin-fanta** [comment]
There may be a mix of version 5 and 6 icon sets.
