### ISSUE TITLE
[Bug]: Mislabelled Icon in react-icons/go

### ISSUE THREAD

**Issue by Cocean001** [react-icons/react-icons#771]
### Describe the bug

I have found a labeling problem in the react-icons/go package. The **GoTrash** icon seems to be incorrectly labeled, as it actually represents a trashcan, not trash. Therefore, I propose that it should be renamed to **GoTrashcan**.

### Expected behavior

The icon that is currently being labeled as GoTrash should be correctly named as GoTrashcan. This way, the icon's depiction would be accurately described, providing a more intuitive understanding for developers.

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search?q=gotrash

### Steps To Reproduce

1. Import the  icon from 'react-icons/go'GoTrash
2. Render the icon in a React component.
3. Observe that the icon represents a 'trashcan' rather than 'trash'.

### Package version

v4.10.1

**Comment by kamijin-fanta** [comment]
Automatically generated from the original icon set. So I will not rename it for this project.
