### ISSUE TITLE
[Bug]: Majority/all FontAwesome icons no longer work or supported

### ISSUE THREAD

**Issue by JNovacovici** [react-icons/react-icons#775]
### Describe the bug

I encountered a bug when trying to import some icons from the website:
RollupError: "FaPhotoFilm" is not exported by "node_modules/react-icons/fa/index.esm.js", imported by "src/components/DataText.jsx".

Same bug occurs for FaEnvelopesBulk.

### Expected behavior

Expected to use the icon after importing via:
import {FaEnvelopesBulk, FaPhotoFilm, } from 'react-icons/fa';

<div>
<FaEnvelopesBulk />
</div>

### Minimal sample repository URL

https://react-icons.github.io/react-icons/icons?name=fa6

### Steps To Reproduce

1. npm install react-icons
2. import {FaEnvelopesBulk} from 'react-icons/fa;
3. Put in a component/div: <FaEnvelopesBulk />

### Package version

4.10.1

### Relevant log output

```Shell
error during build:
RollupError: "FaEnvelopesBulk" is not exported by "node_modules/react-icons/fa/index.esm.js", imported by "src/components/DataText.jsx".
```

**Comment by kamijin-fanta** [comment]
please rewrite to `import {FaEnvelopesBulk} from 'react-icons/fa6';`
