### ISSUE TITLE
[Bug]: Duplicate "HiDocumentText" found

### ISSUE THREAD

**Issue by alfawal** [react-icons/react-icons#776]
### Describe the bug

I wanted to use the one on the right but after importing it I got a different one, turns out that there are two icons with the same name.
![image](https://github.com/react-icons/react-icons/assets/61620817/0feabfea-370b-4815-8143-a03e34c9c6c2)

### Expected behavior

One unique icon that can be imported.

### Minimal sample repository URL

https://gist.github.com/alfawal/036befee7fe7b5ffd71b3687620ec2db

### Steps To Reproduce

1. Import the icon.
2. Use it.

### Package version

^4.4.0

**Comment by mvaibhav77** [comment]
Hello @alfawal,

Could you kindly direct your attention to issue #794? In my comment there, I've outlined the situation and provided a detailed explanation of how you can address the problem you're encountering. Please review the information there for assistance with resolving your issue.

Thank you.

**Comment by kamijin-fanta** [comment]
see #794
