### ISSUE TITLE
[Feature]:  why don't react-icon have colored icons. 

### ISSUE THREAD

**Issue by Mgajurel** [react-icons/react-icons#777]
### Describe

I am new to react, hence have a simple question. Why don't react-icons have colored icon (as per the icon, a blue linked-in, a gradient instagram and so on). 

I want to have a hover effects on social site's icon. Instead on rigorously working on changing color of the black icons, i could just play on the opacity of the icon with color for them.

Am I missing something, or this could be a serious feature request??? 

### Solution

Have a bunch of icons with accurate colors for major icons, starting with social media icons.

**Comment by kamijin-fanta** [comment]
Some icons are colored. I respect the specifications of the original icon set. https://react-icons.github.io/react-icons/icons?name=fc

**Comment by Mgajurel** [comment]
Now, I prefer and SVG. Thanks but no thanks.

**Comment by eteen12** [comment]
You use SVG over icons?

**Comment by anburocky3** [comment]
> Some icons are colored. I respect the specifications of the original icon set. https://react-icons.github.io/react-icons/icons?name=fc

For newcommers, who have problem in accessing this url. The url is changed: 

New Link: https://react-icons.github.io/react-icons/icons/fc/
