### ISSUE TITLE
[Bug]:  Error loading react-icon

### ISSUE THREAD

**Issue by paullaster** [react-icons/react-icons#778]
### Describe the bug

GET
http://localhost:5173/node_modules/.vite/deps/react-icons_md.js?t=1689516050466&v=cbd8c453

Loading module from “http://localhost:5173/node_modules/.vite/deps/react-icons_md.js?t=1689516050466&v=cbd8c453” was blocked because of a disallowed MIME type (“”).

I get the following error when trying to load react-icons 

### Expected behavior

I expect to see the icons displayed

### Minimal sample repository URL

https://github.com/paullaster/knesta.git

### Steps To Reproduce

I am using "react": "^18.2.0", node v18.15.0

I have installed react-icons library
"react-icons": "^4.10.1",

import { MdDensityMedium } from "react-icons/md";
const randFunc = () => {
return (
 <div>
   <MdDensityMedium />
 </div>
)
}

export default randFunc;

run: npm i then npm run dev.

I expected the icons but I get the above error

### Package version

4.10.1

**Comment by kamijin-fanta** [comment]
The minimum repository is not provided.
