### ISSUE TITLE
[Feature]: New twitter brand design 

### ISSUE THREAD

**Issue by friendglak** [react-icons/react-icons#788]
### Describe

As we already know twitter has updated its logo, it is necessary to change the icons that are already in the library.

### Solution

Update the twitter icons mostly to the n

**Comment by Xevion** [comment]
https://www.compart.com/en/unicode/U+1D54F

**Comment by gdams** [comment]
https://fontawesome.com/icons/x-twitter?f=brands&s=solid

**Comment by wadoud1234** [comment]
use this svg (credit fontawesome.com website)
`<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 512 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/></svg>`

**Comment by C00K1E-dev** [comment]
Hi all 
I have just wanted to use the new icon on my in development website but I couldn't find the new icon in the package .
Any ideas when it will be available?

**Comment by fkk989** [comment]
anyone who wants the new logo can download it form here 
https://about.twitter.com/en/who-we-are/brand-toolkit
