### ISSUE TITLE
[Bug]: There exist 2 icons with the same name

### ISSUE THREAD

**Issue by vanlong20it** [react-icons/react-icons#794]
### Describe the bug

I search hibookmark in react-icons and found heroicon has 2 icons HiBookmark, I want to use the second icon but the result is return the first icon

### Expected behavior

I want to use the second icon HiBookmark, thanks all

### Minimal sample repository URL

https://github.com/react-icons/react-icons

### Steps To Reproduce

- In NextJS 13
- Node version: 18

### Package version

4.10.1

**Comment by mvaibhav77** [comment]
Hello @vanlong20it ,

I noticed that the HiBookmark icon which you are looking for isn't available in the `react-icons/hi` module. However, it can be found in the `react-icons/hi2` module, which corresponds to Hero Icons 2 version.

You can resolve this by updating your import code from:
```jsx
import { HiBookmark } from "react-icons/hi";
```
to:
```jsx
import { HiBookmark } from "react-icons/h2";
```

This should address the issue you're facing. Let me know if you need further assistance.

**Comment by kamijin-fanta** [comment]
@mvaibhav77 That's right.

The search screen needs to be made easier to read, but this is not a bug.
