### ISSUE TITLE
[Bug]: Duplicated names

### ISSUE THREAD

**Issue by sereginserhii** [react-icons/react-icons#795]
### Describe the bug

In the all-files package, there is a bug with duplicate svg names. Some of them for some reason failed with the camel case register and my build fails on Linux as it does not like that 😊
This is a couple of examples with the files that I found:
- MdAddchart.esm.js
- MdOutlineAddchart.esm.js
- MdOutlineAddchart.d.ts
- MdOutlineAddchart.js

### Expected behavior

Exist only one file with the correct camel case register

### Minimal sample repository URL

https://github.com/react-icons/react-icons

### Steps To Reproduce

1. Setup Next JS 13 project
1. Just install this package to your project😅
2. On Linux (I use WSL 2) run yarn dev

### Package version

4.10.1

### Relevant log output

```Shell
- error Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
.next/server/_sc_client_node_modules_react-icons_all-files_md_MdOutlineAddchart_esm_js.js
.next/server/_sc_client_node_modules_react-icons_all-files_md_MdOutlineAddChart_esm_js.js
```

### Additional context

There are no actual versions for the all-files package, so it just installed like so:
---package.json---
"@react-icons/all-files": "https://github.com/react-icons/react-icons/releases/download/v4.10.1/react-icons-all-files-4.10.1.tgz",
---package.json---
Maybe there is a more efficient way to install it. But I don`t find any except [this](https://github.com/react-icons/react-icons/issues/593#issuecomment-1446098993)

**Comment by kamijin-fanta** [comment]
Repository is not provided.
