### ISSUE TITLE
Convert icons to PureComponent as baseline

### ISSUE THREAD

**Issue by tracker1** [react-icons/react-icons#80]
Given the rendering/performance differences, it's probably worthwhile to convert rendering to use PureComponent as the base instead of the stateless component.

**Comment by bentatum** [comment]
Thanks for pointing this out. I was unaware of PureComponent. I think we should replace the base package and change the create script to use this as well.

**Comment by mbrookes** [comment]
@bentatum If you wish to maintains these as SFCs, but gain the benefit of pure rendering, you can wrap them with recompose/pure as we do for Material-UI svg-icons: https://github.com/callemall/material-ui/blob/master/src/svg-icons/action/accessibility.js

**Comment by bentatum** [comment]
thanks @mbrookes probably better we avoid the additional dependency.

+1 for recompose though. love that lib.

**Comment by mbrookes** [comment]
I"m tempted to submit a PR to `recompose` to use `PureComponent` under the covers just for badness. :smiling_imp:

**Comment by bentatum** [comment]
shouldComponentUpdate? Never!

**Comment by tracker1** [comment]
@bentatum I'm wondering if `PureComponent` vs. `shouldComponent = () => false` would be better...

**Comment by bentatum** [comment]
PureComponent would be better.

**Comment by tracker1** [comment]
@bentatum yeah, was just looking into it, and updated my prior comment.

**Comment by oreqizer** [comment]
functional components will have a performance advantage over _any_ class in the future, I would keep them that way

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
use functional component. try new version!
