### ISSUE TITLE
[Bug]: Attempted import error: 'MdLocationPin' is not exported from 'react-icons/md'.

### ISSUE THREAD

**Issue by NageswararaoNilla** [react-icons/react-icons#800]
### Describe the bug

import {MdLocationPin} from 'react-icons/md'

 <MdLocationPin />

Import Error:

Attempted import error: 'MdLocationPin' is not exported from 'react-icons/md'.

### Expected behavior

Should import for usage

### Minimal sample repository URL

https://github

### Steps To Reproduce

 <MdLocationPin />

### Package version

v1.0.0

**Comment by kamijin-fanta** [comment]
No minimum repository is provided.
