### ISSUE TITLE
[Feature]: Redirect / to /react-icons

### ISSUE THREAD

**Issue by cnrad** [react-icons/react-icons#801]
### Describe

Please for the love of god add a redirect from https://react-icons.github.io to https://react-icons.github.io/react-icons or something, I'm tired of getting a 404 for simply wanting to visit the site but forgetting the page

### Solution

Just add a simple redirect, this would be such a low effort high reward feature and should take no more than 5 minutes (but I don't know the details of how the website is hosted)

**Comment by kamijin-fanta** [comment]
dup for #764.
