### ISSUE TITLE
Some icons do not show in search

### ISSUE THREAD

**Issue by chrisblow** [react-icons/react-icons#81]
This is a wonderful project. 

I had a tiny problem: I think some of the icons are included but are not displayed in the index.

For example "MoreHoriz" does not show here: http://gorangajic.github.io/react-icons/md.html but it is there: react-icons/lib/md/more-horiz

**Comment by kamijin-fanta** [comment]
fix in react-icons@3.0.0 / pr: #141
new document site: https://react-icons.netlify.com/#/icons/md . try new version!
