### ISSUE TITLE
[Bug]: BsFillFuelPumpFill icon is missing when installed using "npm @react-icons/all-files --save"

### ISSUE THREAD

**Issue by RanggaBS** [react-icons/react-icons#820]
### Describe the bug

There is no "BsFillFuelPumpFIll" icon when installed using "npm i @react-icons/all-files --save". But when installed using "npm i react-icons --save", the icon exists.

- @react-icons/all-files v^4.1.0
- react-icons v^4.11.0

Edit:
Also, there are absolutely no icons with the name "fuel" & "magni" (magnifying glass) in the entire folder.

### Expected behavior

Of course, add them.

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search?q=BsFillFuelPump

### Steps To Reproduce

1. Run "npm i @react-icons/all-files --save".
2. Try to import the icon. You will not be given any suggestions for the name of the icon.

### Package version

v4.1.0

**Comment by kamijin-fanta** [comment]
There is a problem and @react-icons/all-files has not released a new version. See #593 for details.
