### ISSUE TITLE
[Bug]: search icon not work!

### ISSUE THREAD

**Issue by zerosoul** [react-icons/react-icons#847]
### Describe the bug

always the tip: Please enter at least 3 characters to search...  even I input three charactors

<img width="423" alt="image" src="https://github.com/react-icons/react-icons/assets/2985895/2a3de395-a527-42be-a22b-9f6ea54ec5ec">

### Expected behavior

search works like the old version

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search/

### Steps To Reproduce

enter https://react-icons.github.io/react-icons/search/

 search something

### Package version

latest

**Comment by laogui** [comment]
+1

**Comment by jr-cast** [comment]
+2

**Comment by thecodermehedi** [comment]
not working........

**Comment by longlong7211** [comment]
me too....

**Comment by thecodermehedi** [comment]
@kamijin-fanta

**Comment by Ce1ling** [comment]
+1, It's so deadly.

**Comment by bombillazo** [comment]
Yup, the search is dead, always asks for more than 3 characters no matter what one inputs...

**Comment by kamijin-fanta** [comment]
I'll fix it soon... 😭

**Comment by Kishan-kr** [comment]
Yup search feature is not working, after entering any keyword it still asks for more than 3 characters.

**Comment by kamijin-fanta** [comment]
Fixed the code. Reload the page and try again. https://github.com/react-icons/react-icons/commit/399b45c3c052cd2666eb6432e1872992a4db5589

**Comment by AnmolDotX** [comment]
okkay, thanks now its working

![Uploading Screenshot from 2023-11-16 10-28-13.png…]()

**Comment by AnmolDotX** [comment]
okkay, thanks now its working

![Uploading Screenshot from 2023-11-16 10-28-13.png…]()

**Comment by kamijin-fanta** [comment]
@AnmolDotX Matched when entered in all lowercase. Perhaps the way capitalization is handled has changed.
