### ISSUE TITLE
[Feature]: Add support for Material Symbols

### ISSUE THREAD

**Issue by mikeabellroo** [react-icons/react-icons#850]
### Describe

https://developers.google.com/fonts/docs/material_symbols

### Solution

add the new font sheet

**Comment by tuananhlai** [comment]
Hi, I was just wondering what's the status of this issue? I noticed it's mark as completed but I haven't found any mentions of material symbols in the latest 4.12.0 release. 💭

**Comment by mikeabellroo** [comment]
yeah same, what's the update??
