### ISSUE TITLE
[Bug]: Icon preview not show in documentation

### ISSUE THREAD

**Issue by lineuxyz** [react-icons/react-icons#852]
### Describe the bug

Icon display not working. All the icons that appear to me, from any library, none are rendered on screen.

![Screenshot 2023-11-17 at 07 02 28](https://github.com/react-icons/react-icons/assets/54123248/edd90b22-6cd2-4b7b-aa59-674ece6dd8b4)
![Screenshot 2023-11-17 at 07 02 41](https://github.com/react-icons/react-icons/assets/54123248/41a5a829-c625-41c6-98f7-1668ee456cef)

### Expected behavior

The icon preview works again as in the previous version

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search/

### Steps To Reproduce

Enter: https://react-icons.github.io/react-icons/icons/di/

### Package version

latest

**Comment by salvatoluice** [comment]
I am encountering the same issue.

**Comment by quocvuong2000** [comment]
+1

**Comment by EdgarasGust** [comment]
Same

**Comment by shayaliza** [comment]
same

**Comment by MayorCachapa** [comment]
same

**Comment by Chandrapalsingh12** [comment]
+1

**Comment by ckpearson** [comment]
Same 👍

**Comment by caffeinatedHuman** [comment]
➕

**Comment by Kishan-kr** [comment]
same, preview of icons is not visible

**Comment by tushar-2223** [comment]
+1

**Comment by baryman** [comment]
+1

**Comment by lbltavares** [comment]
+1

**Comment by ttngocthao** [comment]
same 🥺 .  please fix it 🙏

**Comment by drozdovdn** [comment]
+1

**Comment by Siraj-dev-ui** [comment]
same

**Comment by kaizipaul** [comment]
getting the same problem here...

**Comment by InTheNooB** [comment]
same here

**Comment by toryshadow** [comment]
same, please fix

**Comment by lassegit** [comment]
Same issue here, no errors in the console and doesn't work in Safari or Brave.

**Comment by muharu** [comment]
+1

**Comment by michaelboyles** [comment]
Since it's evening in Japan and the maintainer is probably sleeping, I've forked a mirror on the docs site, rolled back 1 commit before the breaking change:

**https://michaelboyles.github.io/react-icons/**

Let me know if you have any issues and I can try to fix it. Looks good to me though.

**Comment by kamijin-fanta** [comment]
Thank you for the report. I will fix this.

**Comment by kamijin-fanta** [comment]
Sorry. The problem is resolved now. Please reload your browser.

**Comment by michaelboyles** [comment]
Working, thanks!
