### ISSUE TITLE
[Bug]: Icons preview

### ISSUE THREAD

**Issue by sajjadahammad** [react-icons/react-icons#854]
### Describe the bug

The previews for the icon is not showing 

### Expected behavior

![Screenshot (246)](https://github.com/react-icons/react-icons/assets/109269243/434e2e6d-7dc7-4cba-9538-233f25dd959e)

### Minimal sample repository URL

https://github.com/react-icons/react-icons/

### Steps To Reproduce

just visit the site

### Package version

latest

**Comment by Tejasshri** [comment]
I am also facing same problem

**Comment by Dylan-Kentish** [comment]
+1

**Comment by muharu** [comment]
+1

**Comment by ap-justin** [comment]
+1

**Comment by michaelboyles** [comment]
@kamijin-fanta Looks like your commit 06f4ab1eb8dba6eda7e19522ca5f4081fbdf94da may have broken this

**Comment by ubaid0309** [comment]
I am also facing the same issue

**Comment by benlhachemi** [comment]
+1

**Comment by michaelboyles** [comment]
FYI I made a workaround until it's fixed: https://github.com/react-icons/react-icons/issues/852#issuecomment-1816508674 

This is a dupe of that issue

**Comment by kamijin-fanta** [comment]
Thank you for the report. I will fix this.

**Comment by kamijin-fanta** [comment]
dup #852
