### ISSUE TITLE
[Bug]: The Site taking too long to load the icons

### ISSUE THREAD

**Issue by ghost2023** [react-icons/react-icons#857]
### Describe the bug

This is not issue issue with the library but issue with the website. It takes alot of time when loading icons and sometimes it does not load at all. Other thing there seems to be a lot of bugs with the search

### Expected behavior

It should load in a reasonable time

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search/#q=success

### Steps To Reproduce

1. go to `https://react-icons.github.io/react-icons`
2. then search 'success'

### Package version

000

**Comment by kamijin-fanta** [comment]
In my environment, with the cache deleted, the search finishes within 500ms. You need to share more info.
