### ISSUE TITLE
Can I just get a glimpse into the big brain that updated the documentation page?

### ISSUE THREAD

**Issue by 10xchs** [react-icons/react-icons#864]
### Describe

Why did you decide to ruin the design completely? Instead of being able to search for an icon and then simply copy it, now you have to search, try to select, oh that doesn't work because it says "gi GiPlayButton" for some reason and a modal pops up, so you have to copy it from there. Then the next time you have to search you have to click to close the modal.

It's just fascinating to me how ridiculously stupid ideas get implemented. I'd love to hear the thought process!

### Solution

Go back to the old design.

**Comment by RohanM-12** [comment]
Changing familiar workflows can definitely be disruptive, especially when it adds extra steps to a process that used to be straightforward. The older UI likely felt more intuitive and user-friendly in comparison.

I understand the value of simplicity and ease of use. Sometimes, changes are made with the intention of improving functionality or adding new features, but they can inadvertently complicate things for users. I agree with this opinion .....

**Comment by alex-kinokon** [comment]
If anyone wants the old design meanwhile, try [my implementation](https://alex-kinokon.github.io/react-icons/) of the docs.
