### ISSUE TITLE
Ugly icons if size is different then 14px

### ISSUE THREAD

**Issue by noosxe** [react-icons/react-icons#87]
I'm trying to use the library and fa icons look proper only if size is given 14px.
I don't think this was the desired behaviour.
Anybody know how to fix this ?

**Comment by emilbruckner** [comment]
Normal behaviour here
More info?

**Comment by noosxe** [comment]
Here are 2 examples from my use case, same icon with 2 different sizes applied:
[normal quality - 14px](https://ibb.co/e7VUDv)
[bad quality - 15px](https://ibb.co/gVFJ6F)

**Comment by bentatum** [comment]
are you using the size attribute size these?

<Icon size={15} />
<Icon size={14} />

**Comment by noosxe** [comment]
Exactly, I use that, normal quality appears to be only when using 14 size, everything else is a total mess

**Comment by bentatum** [comment]
Which browser are you using? Do you have a codepen or some kind of live example I can take a look at?

**Comment by noosxe** [comment]
Same issue on chrome and firefox, don't have ready to send example, but will make one!

**Comment by dardub** [comment]
The material icons documentation recommends specific sizes for their icons. I've noticed the same issue before with the hamburger icon when using material icons on their own.

See here: http://google.github.io/material-design-icons/#sizing

**Comment by kamijin-fanta** [comment]
If the problem persists, please provide a minimal repository.
