### ISSUE TITLE
Add Icon Nomad

### ISSUE THREAD

**Issue by SimoneGiusso** [react-icons/react-icons#870]
### Describe

https://www.nomadproject.io

### Solution

https://www.nomadproject.io

**Comment by kamijin-fanta** [comment]
This library will add icon sets generally used in Web UI, but will not directly add icons for specific brands.

**Comment by SimoneGiusso** [comment]
> Adds icon sets, but not individual icons.

How the issue should be opened to ask for a SiJooQ component or a SiMockito component?

**Comment by kamijin-fanta** [comment]
It's not possible if Simple Icons doesn't include it. If it's included in any other icon set, please post your idea in the discussion.
