### ISSUE TITLE
[Bug]: How to start locally?

### ISSUE THREAD

**Issue by Praveen03AJJARAPU** [react-icons/react-icons#883]
### Describe the bug

PS C:\Users\Praveen\open-source\react-icons> yarn start
Usage Error: Couldn't find a script named "start".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ... 

This happened to me after yarn install.
I can't run yarn build also.

### Expected behavior

It should be running locally 

### Minimal sample repository URL

https://github.com/Praveen03AJJARAPU/react-icons

### Steps To Reproduce

1. Fork it.
2. Clone the repo 
3. Run yarn install
4. run yarn build/start

### Package version

4.12.0

**Comment by kamijin-fanta** [comment]
Please refer to CI scripts, etc.
