### ISSUE TITLE
[Feature]: Update Remix Icon version 4.2.0

### ISSUE THREAD

**Issue by scottsun94** [react-icons/react-icons#905]
### Describe

Remix has added a lot of useful new icons since 3.5.0 (the latest version).
It will be great if we can update the remix version to 4.2.0

### Solution

The same solution as in https://github.com/react-icons/react-icons/issues/730

**Comment by kamijin-fanta** [comment]
thanks! release in [v5.1.0](https://github.com/react-icons/react-icons/releases/tag/v5.1.0)
