### ISSUE TITLE
[Feature]: how to change icon size

### ISSUE THREAD

**Issue by meddhiaka** [react-icons/react-icons#913]
### Describe

I'm always frustrated when to think about changing the icon size

for example this one does not work with tailwind classes

```html
<button className=' rounded py-2 px-[150px] border border-blue-950'>
     <FcGoogle className=' inline-block w-3' />
     <span className='px-3'>Continuer avec Google</span>
</button>

```

### Solution

make tailwind classes applicable to the all react icons!

**Comment by Emyboy** [comment]
> ### Describe
> I'm always frustrated when to think about changing the icon size
> 
> for example this one does not work with tailwind classes
> 
> ```
> <button className=' rounded py-2 px-[150px] border border-blue-950'>
>      <FcGoogle className=' inline-block w-3' />
>      <span className='px-3'>Continuer avec Google</span>
> </button>
> ```
> 
> ### Solution
> make tailwind classes applicable to the all react icons!
> 
> ### Minimal sample repository URL
> _No response_
> 
> ### Additional context
> _No response_


You can use the size props
```<FcGoogle size={25} />```

or using Tailwind you'll have to use width and height classNames
```<FcGoogle className="w-20 h-20" />```

Hope I was able to help

**Comment by MikeAwad662442** [comment]
# you can use  font size from tailwind *text-2xl*
like that
```js
 <button className=' rounded py-2 px-[150px] border border-blue-950'>
                        <FcGoogle className=' inline-block text-2xl' />
                        <span className='px-3'>Continuer avec Google</span>
                    </button>
```

# OR you can use **IconContext** wrapper all tag in the components
like that 
```js
import { IconContext } from "react-icons";
<IconContext.Provider value={{ className: "text-5xl " }}>
   <button className=' rounded py-2 px-[150px] border border-blue-950'>
                          <FcGoogle className=' inline-block ' />
                          <span className='px-3'>Continuer avec Google</span>
                      </button>
</IconContext.Provider>
```
