### ISSUE TITLE
[Feature]: Update Font Awesome once BlueSky has an icon.

### ISSUE THREAD

**Issue by fluentmoheshwar** [react-icons/react-icons#914]
### Describe

There's no icon for [BlueSky Social](https://bsky.app) in `react-icons`. However, Font Awesome is adding one in their icon set.

### Solution

Upgrade the version of Font Awesome when fortawesome/Font-Awesome#19810 gets closed.

**Comment by fluentmoheshwar** [comment]
Update: It's there now. Upgrade the version of Font-Awesome to 6.5.2

**Comment by tyteen4a03** [comment]
Looks like the 5.1.0 update updated FA6 to 6.5.1, which does not contain the Bluesky logo.

**Comment by fluentmoheshwar** [comment]
:)

**Comment by kamijin-fanta** [comment]
[v5.2.0](https://github.com/react-icons/react-icons/releases/tag/v5.2.0)  released! available FaBluesky in fa6.
