### ISSUE TITLE
Need Appropriate loaders issue please guide me

### ISSUE THREAD

**Issue by Abdul-Hameed001** [react-icons/react-icons#92]
You may need an appropriate loader to handle this file type.
| export Md3dRotation from './3d-rotation';
| export MdAcUnit from './ac-unit';
| export MdAccessAlarm from './access-alarm';

**Comment by mshibl** [comment]
try `import {ICON_NAME} from "react-icons/lib/md"`

replace `md` with any of the available libraries, this worked for me

**Comment by Deliaz** [comment]
Met the same issue, but didn't found a solution, yet.

**Comment by bsurai** [comment]
@mshibl  I can't use with typescript :(

**Comment by jallier** [comment]
@bsurai and anyone else using typescript who is stuck, you can fix this if you declare your own .d.ts file. 

For example using the /md/search icon:
*icons.d.ts*
```
declare module 'react-icons/lib/md' {
  import * as React from 'react';
  import { IconBaseProps } from 'react-icon-base';
  export class MdSearch extends React.Component<IconBaseProps> { }
}
```
Save the file wherever the custom types go, then import in the component page using:
```
import { MdSearch } from 'react-icons/lib/md';
```
 This will only work for the specific icons, but if you wanted everything I guess you could just copy the definitions given from @types/react-icons and rename them to include /lib. 

No idea if this is the correct way to approach it, but it seems to work for me.

**Comment by dyst5422** [comment]
I GOTCHU FAM!

icons-type-shim.d.ts
```ts
declare module 'react-icons/lib/md' {
  export * from 'react-icons/md';
}
declare module 'react-icons/lib/fa' {
  export * from 'react-icons/fa';
}
declare module 'react-icons/lib/ti' {
  export * from 'react-icons/ti';
}
declare module 'react-icons/lib/go' {
  export * from 'react-icons/go';
}
```

**Comment by kamijin-fanta** [comment]
The latest version is 3. If the problem persists, please provide a minimal repository.
