### ISSUE TITLE
[Bug]: Wrong material icon set (eg: delete icon)

### ISSUE THREAD

**Issue by rookledookle** [react-icons/react-icons#926]
### Describe the bug

In the google font search, the trash can icon (delete) has two lines 
![CleanShot 2024-04-03 at 5  30 10@2x](https://github.com/react-icons/react-icons/assets/9147731/70f400f1-8ffe-4eff-9ecd-48cc6b1f62c4) but react icons version still seems to be the older one with no lines on the trash can 
![CleanShot 2024-04-03 at 5  30 02@2x](https://github.com/react-icons/react-icons/assets/9147731/a9fee61c-7b02-4dd2-bb44-a0a1b710a9fe) 

Am new to these icons so I could be missing something obvious here, apologies / thanks in advance! 

### Expected behavior

react 

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search/#q=delete

### Steps To Reproduce

(see screenshot)

### Package version

^4.12.0

**Comment by kamijin-fanta** [comment]
There are cases where the icons differ from those provided on Google's site. https://github.com/google/material-design-icons/blob/master/src/action/delete/materialicons/24px.svg
