### ISSUE TITLE
[Bug]: HiMiniSquaresPlus causes console error in React project!

### ISSUE THREAD

**Issue by DomagojLoncaric** [react-icons/react-icons#935]
### Describe the bug

Icon causes console error.

### Expected behavior

No console log errors.

### Minimal sample repository URL

https://github.com/

### Steps To Reproduce

Use HiMiniSquaresPlus in React project.

### Package version

5.1.0

### Relevant log output

```Shell
Warning: React does not recognize the `dataSlot` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataslot` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at svg
    at IconBase
    at HiMiniSquaresPlus
   ...
```
```


### Additional context

_No response_

**Comment by yburshe** [comment]
Same warning with the icons, HiStar and HiMagnifyingGlass

**Comment by kamijin-fanta** [comment]
dupulicate #931
