### ISSUE TITLE
[Bug]: Module '"react-icons/pi"' has no exported member 'PiPicnicTable'.

### ISSUE THREAD

**Issue by Xizted** [react-icons/react-icons#945]
![Screenshot 2024-05-05 at 10 00 38 AM](https://github.com/react-icons/react-icons/assets/52983571/5eed6ef8-ffe3-4750-b485-b38b2bfc1b4c)

**Comment by puerschel93** [comment]
Same for me at all Filled icons in `react-icons/tb` (i.e. <TbArrowBadgeRightFilled />) since `5.0.2`.
Downgrading to `5.0.1` fixed it for me

**Comment by kanTechfin** [comment]
I have some errors with /pi icons too.
below icons are not working:
pi PiHandWithdraw
pi PiHandWithdrawBold
pi PiHandWithdrawDuotone
pi PiHandWithdrawFill
pi PiHandWithdrawLight
pi PiHandWithdrawThin
pi PiHandDeposit
pi PiHandDepositBold
pi PiHandDepositDuotone
pi PiHandDepositFill
pi PiHandDepositLight
pi PiHandDepositThin
