### ISSUE TITLE
[Bug]: Cannot build project with Vite due to type error.

### ISSUE THREAD

**Issue by cqllin** [react-icons/react-icons#948]
### Describe the bug

Upon attempting to build/compile my TypeScript project to test some things after adding `react-icons` to my project and using them, now I cannot build my project due to a type error from react-icons.

For context: I am using Laravel 10, with Inertia/React frontend.

The error stems from `\react-icons\index.d.ts`. The error is as follows:
`TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './lib/index.js' instead?`

The file contents causing this type error:
```
// THIS FILE IS AUTO GENERATED
export * from './lib/index.d.ts';
```

### Expected behavior

Upon running "npm run build", Vite should be able to compile/build the project from .tsx and .ts file types to .jsx and .js file types, so the app can be ran on the browser. It should be going to `/public/build` as compiled files. However it errors and stops the process due to the type error explained.

### Minimal sample repository URL

?

### Steps To Reproduce

1. Install `react-icons` to Laravel 10, Inertia/React project.
2. Add some `react-icons` components to your project.
3. Run `npm run build` to build/compile the project.
4. Receive compiler error regarding type error.

### Package version

5.2.1

### Relevant log output

```Shell
TS2846: A declaration file cannot be imported without 'import type'. Did you mean to import an implementation file './lib/index.js' instead?
```

**Comment by tasso85** [comment]
I tried manually modifying the file, and I think that instead it should read

```export * from './lib/index';```

However, since it says it is autogenerated, I am not sure how to fix this, or I'd make a PR.

**Comment by kamijin-fanta** [comment]
The situation can vary greatly depending on the build configuration. Please share a minimal repository that reproduces this error.

**Comment by tasso85** [comment]
I am not too sure [this](https://github.com/tasso85/react-icons-issue-948) is "minimal", but it shows the issue.

It should simply be a matter of cloning the repo, running `npm install` and the `npm run build`.

**Comment by kamijin-fanta** [comment]
Thank you for providing the sample code!

It seems that the issue occurs when `compilerOptions.moduleResolution` in `tsconfig.json` is set to `"bundler"`. Changing it to `"node"` should resolve the problem.

However, I still plan to implement the proposed fixes.
