### ISSUE TITLE
[Bug]: react-icons/tb not working for some coins

### ISSUE THREAD

**Issue by darshjain** [react-icons/react-icons#949]
### Describe the bug

While trying to deploy the icon on nextjs 14.0.1 using vercel, the following error pops up
```
Attempted import error: 'TbTransactionBitcoin' is not exported from '__barrel_optimize__?names=TbTransactionBitcoin!=!react-icons/tb' (imported as 'TbTransactionBitcoin').
```

This is some export/import issue in the package

### Expected behavior

The icon should render locally as well as on deployment without any issue

### Minimal sample repository URL

NA

### Steps To Reproduce

While trying to deploy the icon on nextjs 14.0.1 using vercel, the following error pops up
```
Attempted import error: 'TbTransactionBitcoin' is not exported from '__barrel_optimize__?names=TbTransactionBitcoin!=!react-icons/tb' (imported as 'TbTransactionBitcoin').
```

This is some export/import issue in the package

### Package version

v5.0.1

**Comment by LoyalEnv0y** [comment]
I am experiencing the same issue regarding the TbCopyCheck and TbCopyCheckFilled components in React. 

`import { TbCopy, TbCopyCheck TbCopyCheckFilled } from 'react-icons/tb';`

Results in:

`Module '"react-icons/tb"' has no exported member 'TbCopyCheck'.` And `"react-icons/tb"' has no exported member named 'TbCopyCheckFilled'.`

Any fixes yet?

**Comment by kamijin-fanta** [comment]
It works fine with other build systems. We do not support using Next.js.

**Comment by LoyalEnv0y** [comment]
I am using Vite but having the same issue

**Comment by barrettluke** [comment]
> I am experiencing the same issue regarding the `TbCopyCheck `and `TbCopyCheckFilled `components in React.
> 
> `import { TbCopy, TbCopyCheck TbCopyCheckFilled } from 'react-icons/tb';`
> 
> Results in:
> 
> `Module '"react-icons/tb"' has no exported member 'TbCopyCheck'.` And `"react-icons/tb"' has no exported member named 'TbCopyCheckFilled'.`
> 
> Any fixes yet?

@LoyalEnv0y  I tried to recreate the issue you have with Vite and the only issue I had was that a comma was missing between your import of TbCopyCheck and TbCopyCheckFilled. Please see if adding a comma fixes your issue.

**Comment by LoyalEnv0y** [comment]
@barrettluke It seems that adding the comma fixed the issue. I don't know how I missed that. Thank you for your time.

**Comment by barrettluke** [comment]
> It works fine with other build systems. We do not support using Next.js.

@kamijin-fanta Thanks for the clarification about Next.js not being officially supported. I tested this with Next.js 14.2.12, and it worked for me, so I thought it might be helpful to share my experience for anyone else using it.

That said, I was wondering if I missed any mention in the documentation that Next.js isn’t supported. If it’s not mentioned, would it be possible to add a note about that in the docs? It might help avoid confusion for others who are using Next.js.

**Comment by kamijin-fanta** [comment]
Builds with certain systems like Webpack and Astro are always verified with each release. Next.js does not currently do this. It could be added if someone writes and maintains the test code.

https://github.com/react-icons/react-icons/tree/master/packages/webpack4-test

And since this issue seems to have been resolved, I will close it.
