### ISSUE TITLE
[Bug]: Importing anything from Game Icons also import all library probably

### ISSUE THREAD

**Issue by navid9696** [react-icons/react-icons#958]
### Describe the bug

After importing from Game Icons (Gi) any icon it probably importing all library around 6.5MB maybe it looks like there is no treeshaking or something

### Expected behavior

Properly importing

### Minimal sample repository URL

just import any icon from Gi

### Steps To Reproduce

import { GiBottleCap } from "react-icons/gi";
<GiBottleCap />

### Package version

v5.2.1

**Comment by kamijin-fanta** [comment]
It depends on the compiler settings.

**Comment by navid9696** [comment]
> It depends on the compiler settings.

hmmmm, I just made fresh project in nextJS and other icons are fine.
