### ISSUE TITLE
[Feature]: create icon on simple-icons

### ISSUE THREAD

**Issue by ianzone** [react-icons/react-icons#960]
### Describe

people use [simple-icons](https://github.com/simple-icons/simple-icons) to create badge like this <img src='https://img.shields.io/badge/React-149eca?logo=React&labelColor=grey'>, it's nice to have a react-icons badge since it's a popular component. 

### Solution

https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md#adding-or-updating-an-icon

**Comment by sdabhi23** [comment]
this probably belongs to the simple-icons repo as a `new icon` request
