### ISSUE TITLE
[Bug]: Missing Naver icon

### ISSUE THREAD

**Issue by playaz87** [react-icons/react-icons#961]
### Describe the bug

According to the docs, `SiNaver` should be available. However, it's missing from all-icons.

### Expected behavior

Be able to import `SiNaver`

### Minimal sample repository URL

https://react-icons.github.io/react-icons/search/#q=naver

### Steps To Reproduce

1. Install all icons
2. Fail to import SiNaver

### Package version

4.1.0

**Comment by johnt1838** [comment]
Its working for me

**Comment by kamijin-fanta** [comment]
Please take a look at this. It hasn't been updated for a while #593

**Comment by playaz87** [comment]
@johnt1838 Where did you import it from?

**Comment by johnt1838** [comment]
> @johnt1838 Where did you import it from?
https://www.npmjs.com/package/react-icons
