### ISSUE TITLE
[Bug]: The search bar should be focused by default

### ISSUE THREAD

**Issue by muaaz-raza-dev** [react-icons/react-icons#963]
### Describe the bug

By default the search bar is not focused at the landing page.

### Expected behavior

It should be focused to enhance user experience.

### Minimal sample repository URL

https://react-icons.github.io/react-icons/

### Steps To Reproduce

-Navigate to the file
-Go to input tag
-Add autoFocus attribute.
-That's it!

### Package version

^5.2.1

**Comment by Kumar06Lav** [comment]
Fixed the bug and created a pr

**Comment by kamijin-fanta** [comment]
It can't be described as a general UI.
