### ISSUE TITLE
[Bug]: Some warning when use it in Next Js 

### ISSUE THREAD

**Issue by THERIZKY** [react-icons/react-icons#969]
### Describe the bug

I don't know whether this library can be used in next JS or not, I've always used this library since I learned React, because it's easy to use. Since I used this library in Next JS to create projects, I often get warnings like this ***Warning: React does not recognize the `dataSlot` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataslot` instead. If you accidentally passed it from a parent component, remove it from the DOM element.*** I was confused about what was happening, and I asked in the community and found out that the warning came from the use of these icons

![image](https://github.com/user-attachments/assets/d61fa388-4a7a-4e48-b311-72ffe9d6004a)

### Expected behavior

If this is a bug, I want it fixed, and if this is not a bug but rather my mistake in using this library, please forgive me

### Minimal sample repository URL

nothing

### Steps To Reproduce

I just used the icon according to the documentation, and when I looked at my console, there was a warning written as above

### Package version

5.0.1

### Relevant log output
Warning: React does not recognize the `dataSlot` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dataslot` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

_No response_

**Comment by kamijin-fanta** [comment]
When reporting a bug, please provide a repository that includes only the minimal packages and code necessary to reproduce the issue.
