### ISSUE TITLE
[Feature]: Add copy to clipboard to installation command of react-icons

### ISSUE THREAD

**Issue by motuncoded** [react-icons/react-icons#987]
### Describe

It would be nice to have a copy icon on react-icons installation command in order to allow users to copy the command and paste it in the terminal for installation

### Solution

I would like to create a  copy icon on react-icons installation command in order to allow users to copy the command .

### Additional context

With this, it will be easier for users to copy the installation command.

**Comment by kamijin-fanta** [comment]
I will close this as I believe the demand is low.

**Comment by motuncoded** [comment]
Why? This is not properly discussed with out closing

**Comment by motuncoded** [comment]
I want to work on it, please assign this to me and open it
