### ISSUE TITLE
[Bug]: PiSealPercent doesn't exist (even though listed)

### ISSUE THREAD

**Issue by murm** [react-icons/react-icons#990]
### Describe the bug

PiSealPercent doesn't exist in the package, even though it is listed here https://react-icons.github.io/react-icons/icons/pi/

### Expected behavior

For it to exist :)

### Minimal sample repository URL

https://react-icons.github.io/react-icons/icons/pi/

### Steps To Reproduce

1. Import
2. See error that it doesn't exist

### Package version

v5.3.0

**Comment by kamijin-fanta** [comment]
Please update the package. It will be included in version 5.4.0.
