### ISSUE TITLE
[Bug]: MdArrowCircleUp and MdArrowCircleDown aren't filled.

### ISSUE THREAD

**Issue by nicod-pc** [react-icons/react-icons#995]
### Describe the bug

`MdArrowCircleUp` and `MdArrowCircleDown` are not filled, while `MdArrowCircleLeft` and `MdArrowCircleRight` are filled.
<img width="439" alt="Screenshot 2024-11-26 at 17 04 43" src="https://github.com/user-attachments/assets/4786d1c2-7a7b-4974-b70a-a345ba772a71">

There are also `MdOutlineArrowCircleDown`, `MdOutlineArrowCircleLeft`, `MdOutlineArrowCircleRight` and `MdOutlineArrowCircleUp` who all are not filled. 
<img width="440" alt="Screenshot 2024-11-26 at 17 05 05" src="https://github.com/user-attachments/assets/1c3dddf5-fa72-4be4-a054-dbe24b2b31f4">

So currently `MdArrowCircleUp` kind of duplicates `MdOutlineArrowCircleUp` and `MdArrowCircleDown` duplicates `MdOutlineArrowCircleDown`.

### Expected behavior

`MdArrowCircleUp` and `MdArrowCircleDown` are filled

### Minimal sample repository URL

https://react-icons.github.io/react-icons/icons/md/

### Steps To Reproduce

Open https://react-icons.github.io/react-icons/icons/md/ and look at `MdArrowCircleUp` and `MdArrowCircleDown`.

### Package version

v5.3.0

**Comment by kamijin-fanta** [comment]
Please create an issue in the repository that provides the icon set. https://github.com/google/material-design-icons
